IF OBJECT_ID ( 'VW_ARTIFACT_SOURCE_CODE_REVISION_LIST', 'V' ) IS NOT NULL 
    DROP VIEW [VW_ARTIFACT_SOURCE_CODE_REVISION_LIST];
GO
CREATE VIEW [VW_ARTIFACT_SOURCE_CODE_REVISION_LIST]
AS
	SELECT	ASR.ARTIFACT_SOURCE_CODE_REVISION_ID, ASR.ARTIFACT_TYPE_ID, ASR.ARTIFACT_ID, ASR.REVISION_KEY, ASR.COMMENT, ASR.CREATION_DATE, TYP.NAME AS ARTIFACT_TYPE_NAME, TYP.PREFIX AS ARTIFACT_TYPE_PREFIX
	FROM	TST_ARTIFACT_SOURCE_CODE_REVISION ASR
	INNER JOIN TST_ARTIFACT_TYPE TYP ON ASR.ARTIFACT_TYPE_ID = TYP.ARTIFACT_TYPE_ID	
	UNION ALL
	SELECT	-1 AS ARTIFACT_SOURCE_CODE_REVISION_ID, SCA.ARTIFACT_TYPE_ID, SCA.ARTIFACT_ID, SCC.REVISION_KEY, SCC.MESSAGE AS COMMENT, SCC.UPDATE_DATE AS CREATION_DATE, TYP.NAME AS ARTIFACT_TYPE_NAME, TYP.PREFIX AS ARTIFACT_TYPE_PREFIX
	FROM	TST_SOURCE_CODE_COMMIT_ARTIFACT SCA
	INNER JOIN TST_SOURCE_CODE_COMMIT SCC ON
		SCA.REVISION_ID = SCC.REVISION_ID AND
		SCA.VERSION_CONTROL_SYSTEM_ID = SCC.VERSION_CONTROL_SYSTEM_ID AND
		SCA.PROJECT_ID = SCC.PROJECT_ID
	INNER JOIN TST_ARTIFACT_TYPE TYP ON SCA.ARTIFACT_TYPE_ID = TYP.ARTIFACT_TYPE_ID	
GO
