IF OBJECT_ID ( 'VW_ARTIFACT_LIST', 'V' ) IS NOT NULL 
    DROP VIEW [VW_ARTIFACT_LIST];
GO
CREATE VIEW [VW_ARTIFACT_LIST]
AS
	-- Artifact Records
	SELECT	1 AS ARTIFACT_TYPE_ID, ART.REQUIREMENT_ID AS ARTIFACT_ID, ART.PROJECT_ID, ART.NAME,
			ART.DESCRIPTION, ART.IS_DELETED, ART.CREATION_DATE, ART.LAST_UPDATE_DATE,
			PRJ.NAME PROJECT_NAME, 0 AS RANK
	FROM	TST_REQUIREMENT ART INNER JOIN TST_PROJECT PRJ ON ART.PROJECT_ID = PRJ.PROJECT_ID
	WHERE	PRJ.IS_ACTIVE = 1
	UNION ALL
	SELECT	2 AS ARTIFACT_TYPE_ID, ART.TEST_CASE_ID AS ARTIFACT_ID, ART.PROJECT_ID, ART.NAME,
			ART.DESCRIPTION, ART.IS_DELETED, ART.CREATION_DATE, ART.LAST_UPDATE_DATE,
			PRJ.NAME PROJECT_NAME, 0 AS RANK
	FROM	TST_TEST_CASE ART INNER JOIN TST_PROJECT PRJ ON ART.PROJECT_ID = PRJ.PROJECT_ID
	WHERE	PRJ.IS_ACTIVE = 1
	UNION ALL
	SELECT	3 AS ARTIFACT_TYPE_ID, ART.INCIDENT_ID AS ARTIFACT_ID, ART.PROJECT_ID, ART.NAME,
			ART.DESCRIPTION, ART.IS_DELETED, ART.CREATION_DATE, ART.LAST_UPDATE_DATE,
			PRJ.NAME PROJECT_NAME, 0 AS RANK
	FROM	TST_INCIDENT ART INNER JOIN TST_PROJECT PRJ ON ART.PROJECT_ID = PRJ.PROJECT_ID
	WHERE	PRJ.IS_ACTIVE = 1
	UNION ALL
	SELECT	4 AS ARTIFACT_TYPE_ID, ART.RELEASE_ID AS ARTIFACT_ID, ART.PROJECT_ID, ART.NAME,
			ART.DESCRIPTION, ART.IS_DELETED, ART.CREATION_DATE, ART.LAST_UPDATE_DATE,
			PRJ.NAME PROJECT_NAME, 0 AS RANK
	FROM	TST_RELEASE ART INNER JOIN TST_PROJECT PRJ ON ART.PROJECT_ID = PRJ.PROJECT_ID
	WHERE	PRJ.IS_ACTIVE = 1
	UNION ALL
	SELECT	5 AS ARTIFACT_TYPE_ID, TRN.TEST_RUN_ID AS ARTIFACT_ID, TST.PROJECT_ID, TRN.NAME,
			TST.DESCRIPTION, TST.IS_DELETED, TRN.START_DATE AS CREATION_DATE,
			TRN.END_DATE AS LAST_UPDATE_DATE, PRJ.NAME AS PROJECT_NAME, 0 AS RANK
	FROM	TST_TEST_RUN TRN INNER JOIN TST_TEST_CASE TST
	ON		TRN.TEST_CASE_ID = TST.TEST_CASE_ID INNER JOIN TST_PROJECT PRJ
	ON		TST.PROJECT_ID = PRJ.PROJECT_ID
	WHERE	PRJ.IS_ACTIVE = 1
	UNION ALL
	SELECT	6 AS ARTIFACT_TYPE_ID, ART.TASK_ID AS ARTIFACT_ID, ART.PROJECT_ID, ART.NAME,
			ART.DESCRIPTION, ART.IS_DELETED, ART.CREATION_DATE, ART.LAST_UPDATE_DATE,
			PRJ.NAME PROJECT_NAME, 0 AS RANK
	FROM	TST_TASK ART INNER JOIN TST_PROJECT PRJ ON ART.PROJECT_ID = PRJ.PROJECT_ID
	WHERE	PRJ.IS_ACTIVE = 1
	UNION ALL
	SELECT	7 AS ARTIFACT_TYPE_ID, STP.TEST_STEP_ID AS ARTIFACT_ID, TST.PROJECT_ID, TST.NAME,
			STP.DESCRIPTION, STP.IS_DELETED, STP.LAST_UPDATE_DATE AS CREATION_DATE,
			STP.LAST_UPDATE_DATE, PRJ.NAME PROJECT_NAME, 0 AS RANK
	FROM	TST_TEST_STEP STP INNER JOIN TST_TEST_CASE TST
	ON		STP.TEST_CASE_ID = TST.TEST_CASE_ID INNER JOIN TST_PROJECT PRJ
	ON		TST.PROJECT_ID = PRJ.PROJECT_ID
	WHERE	PRJ.IS_ACTIVE = 1
	UNION ALL
	SELECT	8 AS ARTIFACT_TYPE_ID, ART.TEST_SET_ID AS ARTIFACT_ID, ART.PROJECT_ID, ART.NAME,
			ART.DESCRIPTION, ART.IS_DELETED, ART.CREATION_DATE, ART.LAST_UPDATE_DATE,
			PRJ.NAME PROJECT_NAME, 0 AS RANK
	FROM	TST_TEST_SET ART INNER JOIN TST_PROJECT PRJ ON ART.PROJECT_ID = PRJ.PROJECT_ID
	WHERE	PRJ.IS_ACTIVE = 1
	UNION ALL
	SELECT	9 AS ARTIFACT_TYPE_ID, ART.AUTOMATION_HOST_ID AS ARTIFACT_ID, ART.PROJECT_ID, ART.NAME,
			ART.DESCRIPTION, ART.IS_DELETED, ART.LAST_UPDATE_DATE, ART.LAST_UPDATE_DATE,
			PRJ.NAME PROJECT_NAME, 0 AS RANK
	FROM	TST_AUTOMATION_HOST ART INNER JOIN TST_PROJECT PRJ ON ART.PROJECT_ID = PRJ.PROJECT_ID
	WHERE	PRJ.IS_ACTIVE = 1
	UNION ALL
	SELECT	13 AS ARTIFACT_TYPE_ID, ART.ATTACHMENT_ID AS ARTIFACT_ID, PRA.PROJECT_ID, ART.FILENAME,
			ART.DESCRIPTION, CAST (0 AS BIT) AS IS_DELETED, ART.UPLOAD_DATE AS CREATION_DATE, ART.EDITED_DATE AS LAST_UPDATE_DATE,
			PRJ.NAME PROJECT_NAME, 0 AS RANK
	FROM	TST_ATTACHMENT ART INNER JOIN TST_PROJECT_ATTACHMENT PRA ON ART.ATTACHMENT_ID = PRA.ATTACHMENT_ID
			INNER JOIN TST_PROJECT PRJ ON PRA.PROJECT_ID = PRJ.PROJECT_ID
	WHERE	PRJ.IS_ACTIVE = 1
	UNION ALL
	SELECT	14 AS ARTIFACT_TYPE_ID, ART.RISK_ID AS ARTIFACT_ID, ART.PROJECT_ID, ART.NAME,
			ART.DESCRIPTION, ART.IS_DELETED, ART.CREATION_DATE, ART.LAST_UPDATE_DATE,
			PRJ.NAME PROJECT_NAME, 0 AS RANK
	FROM	TST_RISK ART INNER JOIN TST_PROJECT PRJ ON ART.PROJECT_ID = PRJ.PROJECT_ID
	WHERE	PRJ.IS_ACTIVE = 1
	UNION ALL
	SELECT	-3 AS ARTIFACT_TYPE_ID, USR.USER_ID AS ARTIFACT_ID, -1 AS PROJECT_ID,
			(RTRIM(USP.FIRST_NAME + ' ' + ISNULL(USP.MIDDLE_INITIAL,'')) + ' ' + USP.LAST_NAME) AS NAME,
			'' AS DESCRIPTION, CAST (0 AS BIT) AS IS_DELETED, USR.CREATION_DATE, USP.LAST_UPDATE_DATE, '' AS PROJECT_NAME, 0 AS RANK
	FROM	TST_USER_PROFILE USP INNER JOIN TST_USER USR ON USP.USER_ID = USR.USER_ID
	WHERE	USR.IS_ACTIVE = 1 AND USR.IS_APPROVED = 1
GO
