IF OBJECT_ID ('VW_ADMINHISTORYCHANGE_LIST', 'V') IS NOT NULL 
    DROP VIEW [VW_ADMINHISTORYCHANGE_LIST];
GO

CREATE VIEW [dbo].[VW_ADMINHISTORYCHANGE_LIST]
AS
	SELECT 
		HC.*,
		HD.ADMIN_HISTORY_DETAIL_ID
      ,HD.ADMIN_ARTIFACT_FIELD_NAME
      ,HD.OLD_VALUE
      ,HD.ADMIN_ARTIFACT_FIELD_CAPTION
      ,HD.NEW_VALUE
      ,HD.OLD_VALUE_INT
      ,HD.OLD_VALUE_DATE
      ,HD.NEW_VALUE_INT
      ,HD.NEW_VALUE_DATE
      ,HD.ADMIN_CHANGESET_ID
      ,HD.ADMIN_ARTIFACT_FIELD_ID
      ,HD.ADMIN_CUSTOM_PROPERTY_ID,
	  AD.NAME AS ADMIN_SECTION_NAME,
		HT.CHANGE_NAME AS CHANGETYPE_NAME,
		(RTRIM(US.FIRST_NAME + ' ' + ISNULL(US.MIDDLE_INITIAL,'')) + ' ' + US.LAST_NAME) AS USER_NAME
		
	FROM [ValidationMasterAudit].dbo.TST_ADMIN_HISTORY_CHANGESET_AUDIT AS HC
		INNER JOIN [ValidationMasterAudit].dbo.TST_ADMIN_HISTORY_DETAILS_AUDIT AS HD ON HC.CHANGESET_ID = HD.ADMIN_CHANGESET_ID
		INNER JOIN [ValidationMasterAudit].dbo.TST_ADMIN_SECTION_AUDIT AS AD ON HC.ADMIN_SECTION_ID = AD.ADMIN_SECTION_ID
		INNER JOIN TST_HISTORY_CHANGESET_TYPE AS HT ON HC.HISTORY_CHANGESET_TYPE_ID = HT.CHANGETYPE_ID
		INNER JOIN TST_USER_PROFILE AS US ON HC.ADMIN_USER_ID = US.USER_ID
GO