IF OBJECT_ID ( 'VW_DATATOOLS_REQUIREMENT', 'V' ) IS NOT NULL 
    DROP VIEW [VW_DATATOOLS_REQUIREMENT];
GO

CREATE VIEW [VW_DATATOOLS_REQUIREMENT]
AS
	SELECT REQUIREMENT_ID, IS_SUMMARY, INDENT_LEVEL, IS_DELETED, PROJECT_ID
	FROM TST_REQUIREMENT
GO
