IF OBJECT_ID ( 'VW_OLD_HISTORY_LIST', 'V' ) IS NOT NULL 
    DROP VIEW [VW_OLD_HISTORY_LIST];
GO
CREATE VIEW [dbo].[VW_OLD_HISTORY_LIST]
AS
	SELECT
		HD.ARTIFACT_HISTORY_ID, HD.FIELD_NAME, HD.FIELD_CAPTION,
		HD.OLD_VALUE, HD.NEW_VALUE,
		HD.OLD_VALUE_INT, HD.NEW_VALUE_INT,
		HD.OLD_VALUE_DATE, HD.NEW_VALUE_DATE,
		HD.CHANGESET_ID, HD.FIELD_ID, CUSTOM_PROPERTY_ID,
		HC.ARTIFACT_ID, HC.USER_ID, HC.ARTIFACT_TYPE_ID, HC.CHANGE_DATE,
		(RTRIM(US.FIRST_NAME + ' ' + ISNULL(US.MIDDLE_INITIAL,'')) + ' ' + US.LAST_NAME) AS CHANGER_NAME,
		HT.CHANGE_NAME, HC.CHANGETYPE_ID, AF.ARTIFACT_FIELD_TYPE_ID
	FROM TST_HISTORY_DETAIL AS HD
	INNER JOIN TST_HISTORY_CHANGESET AS HC ON HD.CHANGESET_ID = HC.CHANGESET_ID
	INNER JOIN TST_USER_PROFILE AS US ON HC.USER_ID = US.USER_ID
	INNER JOIN TST_HISTORY_CHANGESET_TYPE AS HT ON HC.CHANGETYPE_ID = HT.CHANGETYPE_ID
	LEFT JOIN TST_ARTIFACT_FIELD AS AF ON HD.FIELD_ID = AF.ARTIFACT_FIELD_ID
	UNION ALL
	SELECT
		HP.HISTORY_POSITION_ID AS ARTIFACT_HISTORY_ID,
		'_Position' AS FIELD_NAME,
		(ART.NAME + ' [' + ART.PREFIX + ':' + CAST(HP.CHILD_ARTIFACT_ID AS NVARCHAR) + '] Position') AS FIELD_CAPTION,
		CAST (HP.OLD_POSITION AS NVARCHAR) AS OLD_VALUE,
		CAST (HP.NEW_POSITION AS NVARCHAR) AS NEW_VALUE,
		NULL AS OLD_VALUE_INT, NULL AS NEW_VALUE_INT,
		NULL AS OLD_VALUE_DATE, NULL AS NEW_VALUE_DATE,
		HP.CHANGESET_ID,
		NULL AS FIELD_ID,
		NULL AS CUSTOM_PROPERTY_ID,
		HC.ARTIFACT_ID, HC.USER_ID, HC.ARTIFACT_TYPE_ID, HC.CHANGE_DATE,
		(RTRIM(US.FIRST_NAME + ' ' + ISNULL(US.MIDDLE_INITIAL,'')) + ' ' + US.LAST_NAME) AS CHANGER_NAME,
		HT.CHANGE_NAME,
		HC.CHANGETYPE_ID,
		NULL AS ARTIFACT_FIELD_TYPE_ID
	FROM TST_HISTORY_POSITION AS HP
	INNER JOIN TST_HISTORY_CHANGESET AS HC ON HP.CHANGESET_ID = HC.CHANGESET_ID
	INNER JOIN TST_USER_PROFILE AS US ON HC.USER_ID = US.USER_ID
	INNER JOIN TST_HISTORY_CHANGESET_TYPE AS HT ON HC.CHANGETYPE_ID = HT.CHANGETYPE_ID
	INNER JOIN TST_ARTIFACT_TYPE ART ON HP.CHILD_ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID
	UNION ALL
	SELECT
		HA.ASSOCIATION_HISTORY_ID AS ARTIFACT_HISTORY_ID,
		'_Association' AS FIELD_NAME,
		HT.CHANGE_NAME AS FIELD_CAPTION,
		CASE WHEN HC.CHANGETYPE_ID = /*Association Remove*/14 THEN (SART.NAME + ' [' + SART.PREFIX + ':' + CAST(HA.SOURCE_ARTIFACT_ID AS NVARCHAR) + '] -> ' + DART.NAME + ' [' + DART.PREFIX + ':' + CAST(HA.DEST_ARTIFACT_ID AS NVARCHAR) + ']') ELSE '' END AS OLD_VALUE,
		CASE WHEN HC.CHANGETYPE_ID = /*Association Add*/13 THEN (SART.NAME + ' [' + SART.PREFIX + ':' + CAST(HA.SOURCE_ARTIFACT_ID AS NVARCHAR) + '] -> ' + DART.NAME + ' [' + DART.PREFIX + ':' + CAST(HA.DEST_ARTIFACT_ID AS NVARCHAR) + ']') ELSE '' END AS NEW_VALUE,
		NULL AS OLD_VALUE_INT, NULL AS NEW_VALUE_INT,
		NULL AS OLD_VALUE_DATE, NULL AS NEW_VALUE_DATE,
		HA.CHANGESET_ID,
		NULL AS FIELD_ID,
		NULL AS CUSTOM_PROPERTY_ID,
		HC.ARTIFACT_ID, HC.USER_ID, HC.ARTIFACT_TYPE_ID, HC.CHANGE_DATE,
		(RTRIM(US.FIRST_NAME + ' ' + ISNULL(US.MIDDLE_INITIAL,'')) + ' ' + US.LAST_NAME) AS CHANGER_NAME,
		HT.CHANGE_NAME,
		HC.CHANGETYPE_ID,
		NULL AS ARTIFACT_FIELD_TYPE_ID
	FROM TST_HISTORY_ASSOCIATION AS HA
	INNER JOIN TST_HISTORY_CHANGESET AS HC ON HA.CHANGESET_ID = HC.CHANGESET_ID
	INNER JOIN TST_USER_PROFILE AS US ON HC.USER_ID = US.USER_ID
	INNER JOIN TST_HISTORY_CHANGESET_TYPE AS HT ON HC.CHANGETYPE_ID = HT.CHANGETYPE_ID
	INNER JOIN TST_ARTIFACT_TYPE SART ON HA.SOURCE_ARTIFACT_TYPE_ID = SART.ARTIFACT_TYPE_ID
	INNER JOIN TST_ARTIFACT_TYPE DART ON HA.DEST_ARTIFACT_TYPE_ID = DART.ARTIFACT_TYPE_ID
GO