IF OBJECT_ID ( 'VW_OLD_HISTORY_CHANGE_LIST', 'V' ) IS NOT NULL 
    DROP VIEW [VW_OLD_HISTORY_CHANGE_LIST];
GO

CREATE VIEW [dbo].[VW_OLD_HISTORY_CHANGE_LIST]
AS
	SELECT 
		HC.*,
		HT.CHANGE_NAME AS CHANGETYPE_NAME,
		(RTRIM(US.FIRST_NAME + ' ' + ISNULL(US.MIDDLE_INITIAL,'')) + ' ' + US.LAST_NAME) AS USER_NAME,
		AT.NAME AS ARTIFACT_TYPE_NAME
		
	FROM TST_HISTORY_CHANGESET AS HC
		INNER JOIN TST_HISTORY_CHANGESET_TYPE AS HT ON HC.CHANGETYPE_ID = HT.CHANGETYPE_ID
		INNER JOIN TST_USER_PROFILE AS US ON HC.USER_ID = US.USER_ID
		INNER JOIN TST_ARTIFACT_TYPE AS AT ON HC.ARTIFACT_TYPE_ID = AT.ARTIFACT_TYPE_ID
GO
