IF OBJECT_ID ( 'VW_OLD_HISTORY_CHANGESET_NET_CHANGES', 'V' ) IS NOT NULL 
    DROP VIEW [VW_OLD_HISTORY_CHANGESET_NET_CHANGES];
GO
CREATE VIEW [dbo].[VW_OLD_HISTORY_CHANGESET_NET_CHANGES]
AS
	SELECT 
		MAX(HC.CHANGESET_ID) AS CHANGESET_ID,
		MAX(HC.USER_ID) AS USER_ID,
		HC.ARTIFACT_TYPE_ID,
		HC.ARTIFACT_ID,
		MAX(HC.CHANGE_DATE) AS CHANGE_DATE,
		HCT.CHANGETYPE_CANONICAL_ID AS CHANGETYPE_ID,
		HC.PROJECT_ID,
		MAX(HC.ARTIFACT_DESC) AS ARTIFACT_NAME,
		MAX(HT.CHANGE_NAME) AS CHANGETYPE_NAME,
		MAX((RTRIM(US.FIRST_NAME + ' ' + ISNULL(US.MIDDLE_INITIAL,'')) + ' ' + US.LAST_NAME)) AS USER_NAME,
		MAX(AT.NAME) AS ARTIFACT_TYPE_NAME,
		BL.BASELINE_ID AS BASELINE_ID,
		MAX(BL.NAME) AS BASELINE_NAME		
	FROM TST_HISTORY_CHANGESET AS HC
		INNER JOIN (
			SELECT
				CHANGETYPE_ID,
				CHANGE_NAME,
				CHANGETYPE_CANONICAL_ID = CASE CHANGETYPE_ID
					WHEN 1 THEN 1	/* Modified -> Modified */
					WHEN 2 THEN 2	/* Deleted -> Deleted */
					WHEN 3 THEN 3	/* Added -> Added */
									/* Purged -> */
					WHEN 5 THEN 1	/* Rollback -> Modified */
					WHEN 6 THEN 6	/* Undelete -> Undeleted */
					WHEN 7 THEN 3	/* Imported -> Added */
									/* Exported -> */
					WHEN 9 THEN 2	/* Deleted_Parent -> Deleted */
					WHEN 10 THEN 3	/* Added_Parent -> Added */
									/* Purged_parent -> */
					WHEN 12 THEN 6	/* Undelete_Parent -> Undelete */
					WHEN 13 THEN 13	/* Assc_Add -> Assc_Add */
					WHEN 14 THEN 14	/* Assc_Del -> Assc_Del */
					WHEN 15 THEN 1	/* Assc_Mod -> Modified */
				END
			FROM TST_HISTORY_CHANGESET_TYPE
			) AS HCT ON HC.CHANGETYPE_ID = HCT.CHANGETYPE_ID
		INNER JOIN TST_HISTORY_CHANGESET_TYPE AS HT ON HCT.CHANGETYPE_CANONICAL_ID = HT.CHANGETYPE_ID
		INNER JOIN TST_USER_PROFILE AS US ON HC.USER_ID = US.USER_ID
		INNER JOIN TST_ARTIFACT_TYPE AS AT ON HC.ARTIFACT_TYPE_ID = AT.ARTIFACT_TYPE_ID
		INNER JOIN (
			SELECT 
				HC.CHANGESET_ID,
				MIN(BL.CHANGESET_ID) AS BASELINE_CHANGESET_ID
			FROM TST_HISTORY_CHANGESET AS HC
			LEFT JOIN TST_PROJECT_BASELINE AS BL ON HC.CHANGESET_ID <= BL.CHANGESET_ID
			GROUP BY 
				HC.CHANGESET_ID) AS BLC ON HC.CHANGESET_ID = BLC.CHANGESET_ID
		INNER JOIN TST_PROJECT_BASELINE BL ON BL.CHANGESET_ID = BASELINE_CHANGESET_ID
	GROUP BY
		HC.ARTIFACT_TYPE_ID,
		HC.ARTIFACT_ID,
		BL.BASELINE_ID,
		HC.PROJECT_ID,
		HCT.CHANGETYPE_CANONICAL_ID
GO

