IF OBJECT_ID ( 'VW_PROJECT_GROUP_USER', 'V' ) IS NOT NULL 
    DROP VIEW VW_PROJECT_GROUP_USER;
GO

CREATE VIEW VW_PROJECT_GROUP_USER
AS
    SELECT	PGU.PROJECT_GROUP_ID, PGU.USER_ID, PGU.PROJECT_GROUP_ROLE_ID, PRG.NAME AS PROJECT_GROUP_NAME,
			PGR.NAME AS PROJECT_GROUP_ROLE_NAME, PRG.IS_ACTIVE, USR.USER_NAME,
			(RTRIM(UPL.FIRST_NAME + ' ' + ISNULL(UPL.MIDDLE_INITIAL,'')) + ' ' + UPL.LAST_NAME) AS FULL_NAME,
			PRG.PORTFOLIO_ID
    FROM	TST_PROJECT_GROUP PRG INNER JOIN TST_PROJECT_GROUP_USER PGU
    ON		PRG.PROJECT_GROUP_ID = PGU.PROJECT_GROUP_ID INNER JOIN TST_USER USR
    ON		PGU.USER_ID = USR.USER_ID INNER JOIN TST_PROJECT_GROUP_ROLE PGR
    ON		PGU.PROJECT_GROUP_ROLE_ID = PGR.PROJECT_GROUP_ROLE_ID INNER JOIN TST_USER_PROFILE UPL
    ON		USR.USER_ID = UPL.USER_ID
GO
