/* ---------------------------------------------------------------------- */
/* Add View "VW_PROJECT_ATTACHMENT_LIST"                                */
/* ---------------------------------------------------------------------- */

IF OBJECT_ID ( 'VW_PROJECT_ATTACHMENT_LIST', 'V' ) IS NOT NULL 
    DROP VIEW [VW_PROJECT_ATTACHMENT_LIST];
GO

CREATE VIEW [dbo].[VW_PROJECT_ATTACHMENT_LIST]
AS
SELECT        PAT.ATTACHMENT_ID, PAT.PROJECT_ID, PAT.DOCUMENT_TYPE_ID, PAT.PROJECT_ATTACHMENT_FOLDER_ID, PAT.IS_KEY_DOCUMENT, ATC.ATTACHMENT_TYPE_ID, ATC.AUTHOR_ID, ATC.EDITOR_ID, ATC.FILENAME, 
                         ATC.DESCRIPTION, ATC.UPLOAD_DATE, ATC.EDITED_DATE, ATC.SIZE, ATC.CURRENT_VERSION, TGS.TAGS, ATC.CONCURRENCY_DATE, ATC.DOCUMENT_STATUS_ID, 
                         DCS.IS_OPEN_STATUS AS DOCUMENT_STATUS_IS_OPEN_STATUS, PRJ.IS_ACTIVE AS PROJECT_IS_ACTIVE, PRJ.PROJECT_GROUP_ID, PRJ.NAME AS PROJECT_NAME, 
                         RTRIM(USR1.FIRST_NAME + ' ' + ISNULL(USR1.MIDDLE_INITIAL, '')) + ' ' + USR1.LAST_NAME AS AUTHOR_NAME, RTRIM(USR2.FIRST_NAME + ' ' + ISNULL(USR2.MIDDLE_INITIAL, '')) 
                         + ' ' + USR2.LAST_NAME AS EDITOR_NAME, ATT.NAME AS ATTACHMENT_TYPE_NAME, PAE.NAME AS DOCUMENT_TYPE_NAME, DCS.NAME AS DOCUMENT_STATUS_NAME, ACP.CUST_01, ACP.CUST_02, ACP.CUST_03, 
                         ACP.CUST_04, ACP.CUST_05, ACP.CUST_06, ACP.CUST_07, ACP.CUST_08, ACP.CUST_09, ACP.CUST_10, ACP.CUST_11, ACP.CUST_12, ACP.CUST_13, ACP.CUST_14, ACP.CUST_15, ACP.CUST_16, ACP.CUST_17, ACP.CUST_18, 
                         ACP.CUST_19, ACP.CUST_20, ACP.CUST_21, ACP.CUST_22, ACP.CUST_23, ACP.CUST_24, ACP.CUST_25, ACP.CUST_26, ACP.CUST_27, ACP.CUST_28, ACP.CUST_29, ACP.CUST_30, ACP.CUST_31, ACP.CUST_32, ACP.CUST_33, 
                         ACP.CUST_34, ACP.CUST_35, ACP.CUST_36, ACP.CUST_37, ACP.CUST_38, ACP.CUST_39, ACP.CUST_40, ACP.CUST_41, ACP.CUST_42, ACP.CUST_43, ACP.CUST_44, ACP.CUST_45, ACP.CUST_46, ACP.CUST_47, ACP.CUST_48, 
                         ACP.CUST_49, ACP.CUST_50, ACP.CUST_51, ACP.CUST_52, ACP.CUST_53, ACP.CUST_54, ACP.CUST_55, ACP.CUST_56, ACP.CUST_57, ACP.CUST_58, ACP.CUST_59, ACP.CUST_60, ACP.CUST_61, ACP.CUST_62, ACP.CUST_63, 
                         ACP.CUST_64, ACP.CUST_65, ACP.CUST_66, ACP.CUST_67, ACP.CUST_68, ACP.CUST_69, ACP.CUST_70, ACP.CUST_71, ACP.CUST_72, ACP.CUST_73, ACP.CUST_74, ACP.CUST_75, ACP.CUST_76, ACP.CUST_77, ACP.CUST_78, 
                         ACP.CUST_79, ACP.CUST_80, ACP.CUST_81, ACP.CUST_82, ACP.CUST_83, ACP.CUST_84, ACP.CUST_85, ACP.CUST_86, ACP.CUST_87, ACP.CUST_88, ACP.CUST_89, ACP.CUST_90, ACP.CUST_91, ACP.CUST_92, ACP.CUST_93, 
                         ACP.CUST_94, ACP.CUST_95, ACP.CUST_96, ACP.CUST_97, ACP.CUST_98, ACP.CUST_99, ATC.IS_DELETED
FROM            dbo.TST_PROJECT_ATTACHMENT AS PAT INNER JOIN
                         dbo.TST_ATTACHMENT AS ATC ON PAT.ATTACHMENT_ID = ATC.ATTACHMENT_ID INNER JOIN
                         dbo.TST_USER_PROFILE AS USR1 ON ATC.AUTHOR_ID = USR1.USER_ID INNER JOIN
                         dbo.TST_USER_PROFILE AS USR2 ON ATC.EDITOR_ID = USR2.USER_ID INNER JOIN
                         dbo.TST_ATTACHMENT_TYPE AS ATT ON ATC.ATTACHMENT_TYPE_ID = ATT.ATTACHMENT_TYPE_ID INNER JOIN
                         dbo.TST_DOCUMENT_TYPE AS PAE ON PAT.DOCUMENT_TYPE_ID = PAE.DOCUMENT_TYPE_ID INNER JOIN
                         dbo.TST_DOCUMENT_STATUS AS DCS ON ATC.DOCUMENT_STATUS_ID = DCS.DOCUMENT_STATUS_ID INNER JOIN
                         dbo.TST_PROJECT_ATTACHMENT_FOLDER AS PAF ON PAT.PROJECT_ATTACHMENT_FOLDER_ID = PAF.PROJECT_ATTACHMENT_FOLDER_ID INNER JOIN
                         dbo.TST_PROJECT AS PRJ ON PAT.PROJECT_ID = PRJ.PROJECT_ID LEFT OUTER JOIN
                             (SELECT        ARTIFACT_ID, ARTIFACT_TYPE_ID, TAGS, PROJECT_ID
                               FROM            dbo.TST_ARTIFACT_TAGS
                               WHERE        (ARTIFACT_TYPE_ID = 13)) AS TGS ON ATC.ATTACHMENT_ID = TGS.ARTIFACT_ID LEFT OUTER JOIN
                             (SELECT        ARTIFACT_ID, ARTIFACT_TYPE_ID, PROJECT_ID, CUST_01, CUST_02, CUST_03, CUST_04, CUST_05, CUST_06, CUST_07, CUST_08, CUST_09, CUST_10, CUST_11, CUST_12, CUST_13, CUST_14, CUST_15, 
                                                         CUST_16, CUST_17, CUST_18, CUST_19, CUST_20, CUST_21, CUST_22, CUST_23, CUST_24, CUST_25, CUST_26, CUST_27, CUST_28, CUST_29, CUST_30, CUST_31, CUST_32, CUST_33, CUST_34, CUST_35, 
                                                         CUST_36, CUST_37, CUST_38, CUST_39, CUST_40, CUST_41, CUST_42, CUST_43, CUST_44, CUST_45, CUST_46, CUST_47, CUST_48, CUST_49, CUST_50, CUST_51, CUST_52, CUST_53, CUST_54, CUST_55, 
                                                         CUST_56, CUST_57, CUST_58, CUST_59, CUST_60, CUST_61, CUST_62, CUST_63, CUST_64, CUST_65, CUST_66, CUST_67, CUST_68, CUST_69, CUST_70, CUST_71, CUST_72, CUST_73, CUST_74, CUST_75, 
                                                         CUST_76, CUST_77, CUST_78, CUST_79, CUST_80, CUST_81, CUST_82, CUST_83, CUST_84, CUST_85, CUST_86, CUST_87, CUST_88, CUST_89, CUST_90, CUST_91, CUST_92, CUST_93, CUST_94, CUST_95, 
                                                         CUST_96, CUST_97, CUST_98, CUST_99
                               FROM            dbo.TST_ARTIFACT_CUSTOM_PROPERTY
                               WHERE        (ARTIFACT_TYPE_ID = 13)) AS ACP ON ATC.ATTACHMENT_ID = ACP.ARTIFACT_ID
GO