IF OBJECT_ID ( 'VW_PROJECT_LIST', 'V' ) IS NOT NULL 
    DROP VIEW VW_PROJECT_LIST;
GO

CREATE VIEW VW_PROJECT_LIST
AS
SELECT
	PRJ.*, PRG.NAME AS PROJECT_GROUP_NAME, PRT.NAME AS PROJECT_TEMPLATE_NAME
FROM TST_PROJECT AS PRJ
	INNER JOIN TST_PROJECT_GROUP PRG ON PRJ.PROJECT_GROUP_ID = PRG.PROJECT_GROUP_ID
	INNER JOIN TST_PROJECT_TEMPLATE PRT ON PRJ.PROJECT_TEMPLATE_ID = PRT.PROJECT_TEMPLATE_ID
GO
