IF OBJECT_ID ( 'VW_PULL_REQUEST', 'V' ) IS NOT NULL 
    DROP VIEW [VW_PULL_REQUEST];
GO
CREATE VIEW [VW_PULL_REQUEST]
AS
	SELECT	
	TSK.TASK_ID,
	TSK.PROJECT_ID,
	TSK.NAME,
	TSK.DESCRIPTION,
	TSK.TASK_FOLDER_ID,
	TSK.TASK_STATUS_ID,
	TSK.TASK_TYPE_ID,
	TSK.TASK_PRIORITY_ID,
	TSK.CREATOR_ID,
	TSK.OWNER_ID,
	TSK.RELEASE_ID,
	TSK.CREATION_DATE,
	TSK.LAST_UPDATE_DATE,
	TSK.CONCURRENCY_DATE,
	TSK.IS_ATTACHMENTS,
	TSK.IS_DELETED,	
	TKS.NAME AS TASK_STATUS_NAME, 
	(RTRIM(USR2.FIRST_NAME + ' ' + ISNULL(USR2.MIDDLE_INITIAL,'')) + ' ' + USR2.LAST_NAME) AS OWNER_NAME,
	(RTRIM(USR1.FIRST_NAME + ' ' + ISNULL(USR1.MIDDLE_INITIAL,'')) + ' ' + USR1.LAST_NAME) AS CREATOR_NAME,
	TKP.NAME AS TASK_PRIORITY_NAME,
	TKP.COLOR AS TASK_PRIORITY_COLOR,
	PRJ.NAME AS PROJECT_NAME, 
	PRJ.PROJECT_TEMPLATE_ID,
	REL.VERSION_NUMBER AS RELEASE_VERSION_NUMBER,
	TKT.NAME AS TASK_TYPE_NAME,
	VCBS.BRANCH_ID AS SOURCE_BRANCH_ID,
	VCBS.NAME AS SOURCE_BRANCH_NAME,
	VCBD.BRANCH_ID AS DEST_BRANCH_ID,
	VCBD.NAME AS DEST_BRANCH_NAME
    FROM TST_TASK AS TSK
		INNER JOIN TST_TASK_STATUS AS TKS ON TSK.TASK_STATUS_ID = TKS.TASK_STATUS_ID
		INNER JOIN TST_TASK_TYPE AS TKT ON TSK.TASK_TYPE_ID = TKT.TASK_TYPE_ID
		LEFT JOIN TST_TASK_PRIORITY AS TKP ON TSK.TASK_PRIORITY_ID = TKP.TASK_PRIORITY_ID
		LEFT JOIN TST_USER_PROFILE AS USR2 ON TSK.OWNER_ID = USR2.USER_ID 
		INNER JOIN TST_USER_PROFILE AS USR1 ON TSK.CREATOR_ID = USR1.USER_ID
		INNER JOIN TST_PROJECT AS PRJ ON TSK.PROJECT_ID = PRJ.PROJECT_ID
		LEFT JOIN TST_RELEASE AS REL ON TSK.RELEASE_ID = REL.RELEASE_ID
		LEFT JOIN TST_VERSION_CONTROL_PULL_REQUEST AS VCP ON TSK.TASK_ID = VCP.TASK_ID
		LEFT JOIN TST_VERSION_CONTROL_BRANCH AS VCBS ON VCP.SOURCE_BRANCH_ID = VCBS.BRANCH_ID
		LEFT JOIN TST_VERSION_CONTROL_BRANCH AS VCBD ON VCP.DEST_BRANCH_ID = VCBD.BRANCH_ID
	WHERE
		PRJ.IS_ACTIVE = 1 AND
		TSK.IS_DELETED = 0 AND
		TKT.IS_PULL_REQUEST = 1
GO
