IF OBJECT_ID ( '[VW_PROJECT_USERS]', 'V' ) IS NOT NULL 
    DROP VIEW [VW_PROJECT_USERS];
GO
CREATE VIEW [VW_PROJECT_USERS]
AS
SELECT	PRU.USER_ID, PRJ.PROJECT_ID, PRJ.PROJECT_GROUP_ID, PRJ.NAME, PRJ.DESCRIPTION, PRJ.WEBSITE, PRJ.CREATION_DATE, PRJ.IS_ACTIVE, 
	PRJ.WORKING_HOURS, PRJ.WORKING_DAYS, PRJ.NON_WORKING_HOURS, PRJ.IS_TIME_TRACK_INCIDENTS, 	PRJ.IS_TIME_TRACK_TASKS, PRJ.IS_EFFORT_INCIDENTS, PRJ.IS_EFFORT_TASKS,
	PRJ.IS_TASKS_AUTO_CREATE, PRJ.REQ_DEFAULT_ESTIMATE, PRJ.REQ_POINT_EFFORT, PRJ.TASK_DEFAULT_EFFORT,
	PRG.NAME AS PROJECT_GROUP_NAME, PRG.PORTFOLIO_ID, PRT.NAME AS PORTFOLIO_NAME, PRJ.PROJECT_TEMPLATE_ID
FROM	TST_PROJECT PRJ INNER JOIN TST_PROJECT_USER PRU
ON		PRJ.PROJECT_ID = PRU.PROJECT_ID INNER JOIN TST_PROJECT_GROUP PRG
ON		PRJ.PROJECT_GROUP_ID = PRG.PROJECT_GROUP_ID LEFT JOIN TST_PORTFOLIO PRT
ON		PRG.PORTFOLIO_ID = PRT.PORTFOLIO_ID
WHERE	PRJ.IS_ACTIVE = 1
UNION ALL
SELECT	PGU.USER_ID, PRJ.PROJECT_ID, PRJ.PROJECT_GROUP_ID, PRJ.NAME, PRJ.DESCRIPTION, PRJ.WEBSITE, PRJ.CREATION_DATE, PRJ.IS_ACTIVE, 
	PRJ.WORKING_HOURS, PRJ.WORKING_DAYS, PRJ.NON_WORKING_HOURS, PRJ.IS_TIME_TRACK_INCIDENTS, 	PRJ.IS_TIME_TRACK_TASKS, PRJ.IS_EFFORT_INCIDENTS, PRJ.IS_EFFORT_TASKS,
	PRJ.IS_TASKS_AUTO_CREATE, PRJ.REQ_DEFAULT_ESTIMATE, PRJ.REQ_POINT_EFFORT, PRJ.TASK_DEFAULT_EFFORT,
	PRG.NAME AS PROJECT_GROUP_NAME, PRG.PORTFOLIO_ID, PRT.NAME AS PORTFOLIO_NAME, PRJ.PROJECT_TEMPLATE_ID
FROM	TST_PROJECT PRJ INNER JOIN TST_PROJECT_GROUP PRG
ON		PRJ.PROJECT_GROUP_ID = PRG.PROJECT_GROUP_ID INNER JOIN TST_PROJECT_GROUP_USER PGU
ON		PRG.PROJECT_GROUP_ID = PGU.PROJECT_GROUP_ID LEFT JOIN TST_PORTFOLIO PRT
ON		PRG.PORTFOLIO_ID = PRT.PORTFOLIO_ID
WHERE	PRJ.IS_ACTIVE = 1 AND PGU.USER_ID NOT IN (SELECT USER_ID FROM TST_PROJECT_USER PRU2 WHERE PRU2.PROJECT_ID = PRJ.PROJECT_ID)
GO
