IF OBJECT_ID ( 'VW_REPORT_SAVED', 'V' ) IS NOT NULL 
    DROP VIEW [VW_REPORT_SAVED];
GO
CREATE VIEW [VW_REPORT_SAVED]
AS
SELECT	RPS.REPORT_SAVED_ID, RPS.REPORT_ID, RPS.REPORT_FORMAT_ID, RPS.USER_ID, RPS.PROJECT_ID, RPS.NAME,
		RPS.PARAMETERS, RPS.IS_SHARED , RPS.CREATION_DATE, PRJ.NAME AS PROJECT_NAME, 
		(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS USER_NAME
FROM	TST_REPORT_SAVED RPS INNER JOIN TST_USER_PROFILE USR
ON		RPS.USER_ID = USR.USER_ID LEFT JOIN TST_PROJECT PRJ
ON		RPS.PROJECT_ID = PRJ.PROJECT_ID
GO
