IF OBJECT_ID ( 'VW_RISK_LIST', 'V' ) IS NOT NULL 
    DROP VIEW [VW_RISK_LIST];
GO
CREATE VIEW [VW_RISK_LIST]
AS
	SELECT	RSK.*,
			RPB.NAME AS RISK_PROBABILITY_NAME,
			RPB.COLOR AS RISK_PROBABILITY_COLOR,
			RPB.SCORE AS RISK_PROBABILITY_SCORE,
			RIM.NAME AS RISK_IMPACT_NAME,
			RIM.COLOR AS RISK_IMPACT_COLOR,
			RIM.SCORE AS RISK_IMPACT_SCORE,
			(RPB.SCORE * RIM.SCORE) AS RISK_EXPOSURE,
			IST.NAME AS RISK_STATUS_NAME,
			IST.IS_OPEN AS RISK_STATUS_IS_OPEN,
			ITP.NAME AS RISK_TYPE_NAME,
			(RTRIM(USR1.FIRST_NAME + ' ' + ISNULL(USR1.MIDDLE_INITIAL,'')) + ' ' + USR1.LAST_NAME) AS CREATOR_NAME,
			(RTRIM(USR2.FIRST_NAME + ' ' + ISNULL(USR2.MIDDLE_INITIAL,'')) + ' ' + USR2.LAST_NAME) AS OWNER_NAME,
            REL.VERSION_NUMBER AS RELEASE_VERSION_NUMBER,
            REL.NAME AS RELEASE_NAME,
            CMP.NAME AS COMPONENT_NAME,
            PGL.NAME AS GOAL_NAME,
			PRJ.IS_ACTIVE AS PROJECT_IS_ACTIVE,
			PRJ.PROJECT_GROUP_ID AS PROJECT_PROJECT_GROUP_ID,
			PRJ.NAME AS PROJECT_NAME,
            ACP.CUST_01, ACP.CUST_02, ACP.CUST_03, ACP.CUST_04, ACP.CUST_05, ACP.CUST_06, ACP.CUST_07, ACP.CUST_08, ACP.CUST_09, ACP.CUST_10,
            ACP.CUST_11, ACP.CUST_12, ACP.CUST_13, ACP.CUST_14, ACP.CUST_15, ACP.CUST_16, ACP.CUST_17, ACP.CUST_18, ACP.CUST_19, ACP.CUST_20,
            ACP.CUST_21, ACP.CUST_22, ACP.CUST_23, ACP.CUST_24, ACP.CUST_25, ACP.CUST_26, ACP.CUST_27, ACP.CUST_28, ACP.CUST_29, ACP.CUST_30,
			ACP.CUST_31, ACP.CUST_32, ACP.CUST_33, ACP.CUST_34, ACP.CUST_35, ACP.CUST_36, ACP.CUST_37, ACP.CUST_38, ACP.CUST_39, ACP.CUST_40,
			ACP.CUST_41, ACP.CUST_42, ACP.CUST_43, ACP.CUST_44, ACP.CUST_45, ACP.CUST_46, ACP.CUST_47, ACP.CUST_48, ACP.CUST_49, ACP.CUST_50,
			ACP.CUST_51, ACP.CUST_52, ACP.CUST_53, ACP.CUST_54, ACP.CUST_55, ACP.CUST_56, ACP.CUST_57, ACP.CUST_58, ACP.CUST_59, ACP.CUST_60,
			ACP.CUST_61, ACP.CUST_62, ACP.CUST_63, ACP.CUST_64, ACP.CUST_65, ACP.CUST_66, ACP.CUST_67, ACP.CUST_68, ACP.CUST_69, ACP.CUST_70,
			ACP.CUST_71, ACP.CUST_72, ACP.CUST_73, ACP.CUST_74, ACP.CUST_75, ACP.CUST_76, ACP.CUST_77, ACP.CUST_78, ACP.CUST_79, ACP.CUST_80,
			ACP.CUST_81, ACP.CUST_82, ACP.CUST_83, ACP.CUST_84, ACP.CUST_85, ACP.CUST_86, ACP.CUST_87, ACP.CUST_88, ACP.CUST_89, ACP.CUST_90,
			ACP.CUST_91, ACP.CUST_92, ACP.CUST_93, ACP.CUST_94, ACP.CUST_95, ACP.CUST_96, ACP.CUST_97, ACP.CUST_98, ACP.CUST_99
    FROM TST_RISK RSK
		LEFT JOIN TST_RISK_PROBABILITY RPB ON RSK.RISK_PROBABILITY_ID = RPB.RISK_PROBABILITY_ID
		INNER JOIN TST_RISK_TYPE ITP ON RSK.RISK_TYPE_ID = ITP.RISK_TYPE_ID
		LEFT JOIN TST_USER_PROFILE USR2 ON RSK.OWNER_ID = USR2.USER_ID
		INNER JOIN TST_RISK_STATUS IST ON RSK.RISK_STATUS_ID = IST.RISK_STATUS_ID
		INNER JOIN TST_USER_PROFILE USR1 ON	RSK.CREATOR_ID = USR1.USER_ID
		INNER JOIN TST_PROJECT PRJ ON RSK.PROJECT_ID = PRJ.PROJECT_ID
		LEFT JOIN TST_RISK_IMPACT RIM ON RSK.RISK_IMPACT_ID = RIM.RISK_IMPACT_ID
		LEFT JOIN TST_RELEASE REL ON RSK.RELEASE_ID = REL.RELEASE_ID
		LEFT JOIN TST_COMPONENT CMP ON RSK.COMPONENT_ID = CMP.COMPONENT_ID
		LEFT JOIN TST_PROJECT_GOAL PGL ON RSK.GOAL_ID = PGL.GOAL_ID
		LEFT JOIN (SELECT * FROM TST_ARTIFACT_CUSTOM_PROPERTY WHERE ARTIFACT_TYPE_ID = 14) ACP ON RSK.RISK_ID = ACP.ARTIFACT_ID
GO
