IF OBJECT_ID ( 'VW_TESTSET_TESTCASE_LIST_INTERNAL', 'V' ) IS NOT NULL 
    DROP VIEW [VW_TESTSET_TESTCASE_LIST_INTERNAL];
GO
CREATE VIEW [VW_TESTSET_TESTCASE_LIST_INTERNAL]
AS
	SELECT
		TSC.*,
		TSE.PROJECT_ID, TST.NAME, TST.DESCRIPTION, TST.AUTHOR_ID, TST.AUTHOR_NAME,
		TST.CREATION_DATE, TST.LAST_UPDATE_DATE, TST.CONCURRENCY_DATE, 
		TST.ESTIMATED_DURATION, TST.TEST_CASE_PRIORITY_ID, TST.TEST_CASE_PRIORITY_NAME, TST.TEST_CASE_PRIORITY_COLOR,
		TST.TEST_CASE_TYPE_ID, TST.TEST_CASE_STATUS_ID, TST.TEST_CASE_TYPE_NAME, TST.TEST_CASE_STATUS_NAME,
		TST.IS_ATTACHMENTS, TST.IS_TEST_STEPS, TSE.RELEASE_ID,
		(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS OWNER_NAME,
		TSE.IS_DELETED AS IS_TEST_SET_DELETED,
		TST.IS_DELETED AS IS_TEST_CASE_DELETED,
		TST.CUST_01, TST.CUST_02, TST.CUST_03, TST.CUST_04, TST.CUST_05, TST.CUST_06, TST.CUST_07, TST.CUST_08, TST.CUST_09, TST.CUST_10,
		TST.CUST_11, TST.CUST_12, TST.CUST_13, TST.CUST_14, TST.CUST_15, TST.CUST_16, TST.CUST_17, TST.CUST_18, TST.CUST_19, TST.CUST_20,
		TST.CUST_21, TST.CUST_22, TST.CUST_23, TST.CUST_24, TST.CUST_25, TST.CUST_26, TST.CUST_27, TST.CUST_28, TST.CUST_29, TST.CUST_30,
		TST.CUST_31, TST.CUST_32, TST.CUST_33, TST.CUST_34, TST.CUST_35, TST.CUST_36, TST.CUST_37, TST.CUST_38, TST.CUST_39, TST.CUST_40,
		TST.CUST_41, TST.CUST_42, TST.CUST_43, TST.CUST_44, TST.CUST_45, TST.CUST_46, TST.CUST_47, TST.CUST_48, TST.CUST_49, TST.CUST_50,
		TST.CUST_51, TST.CUST_52, TST.CUST_53, TST.CUST_54, TST.CUST_55, TST.CUST_56, TST.CUST_57, TST.CUST_58, TST.CUST_59, TST.CUST_60,
		TST.CUST_61, TST.CUST_62, TST.CUST_63, TST.CUST_64, TST.CUST_65, TST.CUST_66, TST.CUST_67, TST.CUST_68, TST.CUST_69, TST.CUST_70,
		TST.CUST_71, TST.CUST_72, TST.CUST_73, TST.CUST_74, TST.CUST_75, TST.CUST_76, TST.CUST_77, TST.CUST_78, TST.CUST_79, TST.CUST_80,
		TST.CUST_81, TST.CUST_82, TST.CUST_83, TST.CUST_84, TST.CUST_85, TST.CUST_86, TST.CUST_87, TST.CUST_88, TST.CUST_89, TST.CUST_90,
		TST.CUST_91, TST.CUST_92, TST.CUST_93, TST.CUST_94, TST.CUST_95, TST.CUST_96, TST.CUST_97, TST.CUST_98, TST.CUST_99

	FROM TST_TEST_SET_TEST_CASE AS TSC
		INNER JOIN TST_TEST_SET AS TSE ON TSC.TEST_SET_ID = TSE.TEST_SET_ID
		INNER JOIN VW_TESTCASE_LIST AS TST ON TSC.TEST_CASE_ID = TST.TEST_CASE_ID
		LEFT JOIN TST_USER_PROFILE USR ON TSC.OWNER_ID = USR.USER_ID
GO
