IF OBJECT_ID ( 'VW_TESTCASE_FOLDER_RELEASE', 'V' ) IS NOT NULL 
    DROP VIEW [VW_TESTCASE_FOLDER_RELEASE];
GO
CREATE VIEW [VW_TESTCASE_FOLDER_RELEASE]
AS
	SELECT
		TST.TEST_CASE_FOLDER_ID, TST.PARENT_TEST_CASE_FOLDER_ID, TST.PROJECT_ID,
		TST.NAME, TST.DESCRIPTION, TST.ESTIMATED_DURATION, TST.LAST_UPDATE_DATE,
		RTC.EXECUTION_DATE, RTC.ACTUAL_DURATION, RTC.RELEASE_ID,
		RTC.COUNT_PASSED,
		RTC.COUNT_FAILED,
		RTC.COUNT_BLOCKED,
		RTC.COUNT_CAUTION,
		RTC.COUNT_NOT_RUN,
		RTC.COUNT_NOT_APPLICABLE
	FROM
		TST_TEST_CASE_FOLDER TST
		INNER JOIN TST_RELEASE_TEST_CASE_FOLDER RTC ON TST.TEST_CASE_FOLDER_ID = RTC.TEST_CASE_FOLDER_ID
		
		
GO
