IF OBJECT_ID ( 'VW_TESTSET_TESTCASE_LIST', 'V' ) IS NOT NULL 
    DROP VIEW [VW_TESTSET_TESTCASE_LIST];
GO
CREATE VIEW [VW_TESTSET_TESTCASE_LIST]
AS
	SELECT
		TSC.*,
		CAST (NULL AS INT) AS EXECUTION_STATUS_ID,
		CAST (NULL AS NVARCHAR) AS EXECUTION_STATUS_NAME,
		CAST (NULL AS DATETIME) AS EXECUTION_DATE,
		CAST (NULL AS INT) AS ACTUAL_DURATION
	FROM VW_TESTSET_TESTCASE_LIST_INTERNAL AS TSC
GO
