-- =============================================
-- Author:			Inflectra Corporation
-- Business Object: ArtifactLink
-- Description:		Retrieves by artifact when dest type specified
-- =============================================
IF OBJECT_ID ( 'ARTIFACTLINK_RETRIEVE_BY_ARTIFACT_WITH_DEST_TYPE', 'P' ) IS NOT NULL 
    DROP PROCEDURE ARTIFACTLINK_RETRIEVE_BY_ARTIFACT_WITH_DEST_TYPE;
GO
CREATE PROCEDURE ARTIFACTLINK_RETRIEVE_BY_ARTIFACT_WITH_DEST_TYPE
	@SourceArtifactTypeId INT,
	@SourceArtifactId INT,
	@DestArtifactTypeId INT
AS
BEGIN
    SELECT	ARL.ARTIFACT_LINK_ID, ARL.DEST_ARTIFACT_ID AS ARTIFACT_ID, ARL.DEST_ARTIFACT_TYPE_ID AS ARTIFACT_TYPE_ID,
    		ARL.CREATOR_ID, ARL.CREATION_DATE, ARL.COMMENT, REQ.NAME AS ARTIFACT_NAME, ART.NAME AS ARTIFACT_TYPE_NAME,
    		(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME,
    		ALT.ARTIFACT_LINK_TYPE_ID, ALT.NAME AS ARTIFACT_LINK_TYPE_NAME, STA.NAME AS ARTIFACT_STATUS_NAME, REQ.PROJECT_ID
    FROM	TST_ARTIFACT_LINK ARL INNER JOIN TST_ARTIFACT_TYPE ART
    ON		ARL.DEST_ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID LEFT JOIN TST_USER_PROFILE USR
    ON		ARL.CREATOR_ID = USR.USER_ID INNER JOIN TST_REQUIREMENT REQ
    ON		ARL.DEST_ARTIFACT_ID = REQ.REQUIREMENT_ID INNER JOIN TST_ARTIFACT_LINK_TYPE ALT
    ON		ARL.ARTIFACT_LINK_TYPE_ID = ALT.ARTIFACT_LINK_TYPE_ID INNER JOIN TST_REQUIREMENT_STATUS STA
    ON		REQ.REQUIREMENT_STATUS_ID = STA.REQUIREMENT_STATUS_ID
    WHERE	ARL.SOURCE_ARTIFACT_TYPE_ID = @SourceArtifactTypeId
    AND	ARL.SOURCE_ARTIFACT_ID = @SourceArtifactId
    AND	ARL.DEST_ARTIFACT_TYPE_ID = @DestArtifactTypeId
    ORDER BY ARL.CREATION_DATE DESC, ARL.ARTIFACT_LINK_ID
END
GO
