-- =============================================
-- Author:			Inflectra Corporation
-- Business Object: Project
-- Description:		Deletes Project Test Sets
-- =============================================
IF OBJECT_ID ( 'PROJECT_DELETE_TEST_SETS', 'P' ) IS NOT NULL 
    DROP PROCEDURE PROJECT_DELETE_TEST_SETS;
GO
CREATE PROCEDURE PROJECT_DELETE_TEST_SETS
	@ProjectId INT
AS
BEGIN
	SET NOCOUNT ON;
    --We need to delete all the test sets associated with the project
    --including all mapped test cases and user navigation data
    DELETE FROM TST_TEST_SET_TEST_CASE_PARAMETER WHERE TEST_SET_TEST_CASE_ID IN (SELECT TEST_SET_TEST_CASE_ID FROM TST_TEST_SET_TEST_CASE WHERE TEST_SET_ID IN (SELECT TEST_SET_ID FROM TST_TEST_SET WHERE PROJECT_ID = @ProjectId))
    DELETE FROM TST_TEST_SET_TEST_CASE WHERE TEST_SET_ID IN (SELECT TEST_SET_ID FROM TST_TEST_SET WHERE PROJECT_ID = @ProjectId)
    DELETE FROM TST_TEST_SET_PARAMETER WHERE TEST_SET_ID IN (SELECT TEST_SET_ID FROM TST_TEST_SET WHERE PROJECT_ID = @ProjectId)
    DELETE FROM TST_TEST_SET_FOLDER WHERE PROJECT_ID = @ProjectId
    DELETE FROM TST_TEST_SET WHERE PROJECT_ID = @ProjectId
    
    --Now we can safely delete all of the test configuration sets
    DELETE FROM TST_TEST_CONFIGURATION_PARAMETER_VALUE WHERE TEST_CONFIGURATION_SET_ID IN (SELECT TEST_CONFIGURATION_SET_ID FROM TST_TEST_CONFIGURATION_SET WHERE PROJECT_ID = @ProjectId)
    DELETE FROM TST_TEST_CONFIGURATION WHERE TEST_CONFIGURATION_SET_ID IN (SELECT TEST_CONFIGURATION_SET_ID FROM TST_TEST_CONFIGURATION_SET WHERE PROJECT_ID = @ProjectId)
    DELETE FROM TST_TEST_CONFIGURATION_SET_PARAMETER WHERE TEST_CONFIGURATION_SET_ID IN (SELECT TEST_CONFIGURATION_SET_ID FROM TST_TEST_CONFIGURATION_SET WHERE PROJECT_ID = @ProjectId)
    DELETE FROM TST_TEST_CONFIGURATION_SET WHERE PROJECT_ID = @ProjectId
END
GO
