-- ===================================================================================================
-- Author:			Inflectra Corporation
-- Business Object: ProjectGroup
-- Description:		Refreshes the requirement count, overall percent complete for the project group
--					and also rolls up to the parent portfolio (if any)
-- ===================================================================================================
IF OBJECT_ID ( 'PROJECTGROUP_REFRESH_REQUIREMENT_COMPLETION', 'P' ) IS NOT NULL 
    DROP PROCEDURE PROJECTGROUP_REFRESH_REQUIREMENT_COMPLETION;
GO
CREATE PROCEDURE PROJECTGROUP_REFRESH_REQUIREMENT_COMPLETION
	@ProjectGroupId INT
AS
DECLARE
	@PortfolioId INT
BEGIN				
	--First we update the program with the percentage complete and requirement counts
	MERGE TST_PROJECT_GROUP AS TARGET	
	USING (
		SELECT
			PRJ.PROJECT_GROUP_ID,
			SUM(PRJ.REQUIREMENT_COUNT) AS REQUIREMENT_COUNT,
			SUM(PRJ.PERCENT_COMPLETE * PRJ.REQUIREMENT_COUNT) / SUM(PRJ.REQUIREMENT_COUNT) AS PERCENT_COMPLETE
		FROM
			TST_PROJECT PRJ
		WHERE
			PRJ.PROJECT_GROUP_ID = @ProjectGroupId AND
			PRJ.IS_ACTIVE = 1 AND
			PRJ.REQUIREMENT_COUNT > 0
		GROUP BY PRJ.PROJECT_GROUP_ID
	) AS SOURCE
	ON
		TARGET.PROJECT_GROUP_ID = SOURCE.PROJECT_GROUP_ID
	WHEN MATCHED THEN
		UPDATE
			SET	
				TARGET.REQUIREMENT_COUNT = SOURCE.REQUIREMENT_COUNT,
				TARGET.PERCENT_COMPLETE = SOURCE.PERCENT_COMPLETE
	WHEN NOT MATCHED BY SOURCE AND TARGET.PROJECT_GROUP_ID = @ProjectGroupId THEN
			UPDATE
			SET	
				TARGET.REQUIREMENT_COUNT = 0,
				TARGET.PERCENT_COMPLETE = 0;
				
	--Next we update the program with the min/max start/end dates
	MERGE TST_PROJECT_GROUP AS TARGET	
	USING (
		SELECT
			PRJ.PROJECT_GROUP_ID,
			MIN(PRJ.START_DATE) AS MIN_START_DATE,
			MAX(PRJ.END_DATE) AS MAX_END_DATE
		FROM
			TST_PROJECT PRJ
		WHERE
			PRJ.PROJECT_GROUP_ID = @ProjectGroupId AND
			PRJ.IS_ACTIVE = 1 AND
			PRJ.START_DATE IS NOT NULL AND
			PRJ.END_DATE IS NOT NULL
		GROUP BY PRJ.PROJECT_GROUP_ID
	) AS SOURCE
	ON
		TARGET.PROJECT_GROUP_ID = SOURCE.PROJECT_GROUP_ID
	WHEN MATCHED THEN
		UPDATE
			SET	
				TARGET.START_DATE = SOURCE.MIN_START_DATE,
				TARGET.END_DATE = SOURCE.MAX_END_DATE
	WHEN NOT MATCHED BY SOURCE AND TARGET.PROJECT_GROUP_ID = @ProjectGroupId THEN
			UPDATE
			SET	
				TARGET.START_DATE = NULL,
				TARGET.END_DATE = NULL;
				
	--Next we update the portfolio (if exists) with the percentage complete and requirement counts
	SELECT @PortfolioId = PORTFOLIO_ID FROM TST_PROJECT_GROUP WHERE PROJECT_GROUP_ID = @ProjectGroupId;
	IF @PortfolioId IS NOT NULL
	BEGIN
		MERGE TST_PORTFOLIO AS TARGET	
		USING (
			SELECT
				PRG.PORTFOLIO_ID,
				SUM(PRG.REQUIREMENT_COUNT) AS REQUIREMENT_COUNT,
				SUM(PRG.PERCENT_COMPLETE * PRG.REQUIREMENT_COUNT) / SUM(PRG.REQUIREMENT_COUNT) AS PERCENT_COMPLETE
			FROM
				TST_PROJECT_GROUP PRG
			WHERE
				PRG.PORTFOLIO_ID = @PortfolioId AND
				PRG.IS_ACTIVE = 1 AND
				PRG.REQUIREMENT_COUNT > 0
			GROUP BY PRG.PORTFOLIO_ID
		) AS SOURCE
		ON
			TARGET.PORTFOLIO_ID = SOURCE.PORTFOLIO_ID
		WHEN MATCHED THEN
			UPDATE
				SET	
					TARGET.REQUIREMENT_COUNT = SOURCE.REQUIREMENT_COUNT,
					TARGET.PERCENT_COMPLETE = SOURCE.PERCENT_COMPLETE
		WHEN NOT MATCHED BY SOURCE AND TARGET.PORTFOLIO_ID = @PortfolioId THEN
				UPDATE
				SET	
					TARGET.REQUIREMENT_COUNT = 0,
					TARGET.PERCENT_COMPLETE = 0;
					
		--Next we update the portfolio with the min/max start/end dates
		MERGE TST_PORTFOLIO AS TARGET	
		USING (
			SELECT
				PRG.PORTFOLIO_ID,
				MIN(PRG.START_DATE) AS MIN_START_DATE,
				MAX(PRG.END_DATE) AS MAX_END_DATE
			FROM
				TST_PROJECT_GROUP PRG
			WHERE
				PRG.PORTFOLIO_ID = @PortfolioId AND
				PRG.IS_ACTIVE = 1 AND
				PRG.START_DATE IS NOT NULL AND
				PRG.END_DATE IS NOT NULL
			GROUP BY PRG.PORTFOLIO_ID
		) AS SOURCE
		ON
			TARGET.PORTFOLIO_ID = SOURCE.PORTFOLIO_ID
		WHEN MATCHED THEN
			UPDATE
				SET	
					TARGET.START_DATE = SOURCE.MIN_START_DATE,
					TARGET.END_DATE = SOURCE.MAX_END_DATE
		WHEN NOT MATCHED BY SOURCE AND TARGET.PORTFOLIO_ID = @PortfolioId THEN
				UPDATE
				SET	
					TARGET.START_DATE = NULL,
					TARGET.END_DATE = NULL;
	END
END
GO
