-- =============================================
-- Author:			Inflectra Corporation
-- Business Object: Release
-- Description:		Inserts a new 'filler' release when we're fixing any hierarchy errors
-- =============================================
IF OBJECT_ID ( 'RELEASE_INSERT_FILLER', 'P' ) IS NOT NULL 
    DROP PROCEDURE RELEASE_INSERT_FILLER;
GO
CREATE PROCEDURE RELEASE_INSERT_FILLER
	@ProjectId INT,
	@Name NVARCHAR(255),
	@IndentLevel NVARCHAR(100),
	@VersionNumber NVARCHAR(20)
AS
BEGIN
	--Now insert the filler release
    INSERT INTO TST_RELEASE (CREATOR_ID, PROJECT_ID, RELEASE_STATUS_ID, RELEASE_TYPE_ID, NAME, VERSION_NUMBER, CREATION_DATE, INDENT_LEVEL, LAST_UPDATE_DATE, CONCURRENCY_DATE, START_DATE, END_DATE, RESOURCE_COUNT, IS_SUMMARY, IS_ATTACHMENTS, IS_DELETED, DAYS_NON_WORKING, PLANNED_EFFORT, AVAILABLE_EFFORT, COUNT_BLOCKED, COUNT_CAUTION, COUNT_FAILED, COUNT_NOT_APPLICABLE, COUNT_NOT_RUN, COUNT_PASSED, TASK_COUNT, TASK_PERCENT_ON_TIME, TASK_PERCENT_LATE_FINISH, TASK_PERCENT_NOT_START, TASK_PERCENT_LATE_START, PERCENT_COMPLETE)
	VALUES (1, @ProjectId, 1, 1, @Name, @VersionNumber, GETUTCDATE(), @IndentLevel, GETUTCDATE(), GETUTCDATE(), GETUTCDATE(), GETUTCDATE(), 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
END
GO
