-- =============================================
-- Author:			Inflectra Corporation
-- Business Object: Template
-- Description:		Changes the risk fields in a project from one template to another
-- Remarks:			It maps field by name where possible, otherwise just uses the defaults
-- =============================================
IF OBJECT_ID ( 'TEMPLATE_REMAP_RISK_FIELDS', 'P' ) IS NOT NULL 
    DROP PROCEDURE TEMPLATE_REMAP_RISK_FIELDS;
GO
CREATE PROCEDURE TEMPLATE_REMAP_RISK_FIELDS
	@ProjectId INT,
	@OldTemplateId INT,
	@NewTemplateId INT
AS
BEGIN
	SET NOCOUNT ON;

-- Risk Types	
UPDATE INC
	SET INC.RISK_TYPE_ID = MAP.NEW_TYPE_ID
FROM 
	TST_RISK INC INNER JOIN (
	SELECT INC.RISK_ID, T1.RISK_TYPE_ID AS OLD_TYPE_ID, T2.RISK_TYPE_ID AS NEW_TYPE_ID
	FROM TST_RISK INC
		INNER JOIN TST_RISK_TYPE T1 ON INC.RISK_TYPE_ID = T1.RISK_TYPE_ID
		INNER JOIN TST_RISK_TYPE T2 ON T1.NAME = T2.NAME		
	WHERE INC.PROJECT_ID = @ProjectId
		AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
		AND T2.PROJECT_TEMPLATE_ID = @NewTemplateId
	UNION	
	SELECT INC.RISK_ID, T1.RISK_TYPE_ID AS OLD_TYPE_ID, (SELECT TOP 1 RISK_TYPE_ID FROM TST_RISK_TYPE WHERE IS_DEFAULT = 1 AND PROJECT_TEMPLATE_ID = @NewTemplateId) AS NEW_TYPE_ID
	FROM TST_RISK INC
		INNER JOIN TST_RISK_TYPE T1 ON INC.RISK_TYPE_ID = T1.RISK_TYPE_ID
	WHERE INC.PROJECT_ID = @ProjectId
		AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
		AND T1.NAME NOT IN (SELECT NAME FROM TST_RISK_TYPE WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)
	) MAP
	ON INC.RISK_ID = MAP.RISK_ID
WHERE 
	MAP.RISK_ID = INC.RISK_ID

-- Risk Status
UPDATE INC
	SET INC.RISK_STATUS_ID = MAP.NEW_STATUS_ID
FROM 
	TST_RISK INC INNER JOIN (
	SELECT INC.RISK_ID, T1.RISK_STATUS_ID AS OLD_STATUS_ID, T2.RISK_STATUS_ID AS NEW_STATUS_ID
	FROM TST_RISK INC
		INNER JOIN TST_RISK_STATUS T1 ON INC.RISK_STATUS_ID = T1.RISK_STATUS_ID
		INNER JOIN TST_RISK_STATUS T2 ON T1.NAME = T2.NAME		
	WHERE INC.PROJECT_ID = @ProjectId
		AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
		AND T2.PROJECT_TEMPLATE_ID = @NewTemplateId
	UNION	
	SELECT INC.RISK_ID, T1.RISK_STATUS_ID AS OLD_STATUS_ID, (SELECT TOP 1 RISK_STATUS_ID FROM TST_RISK_STATUS WHERE IS_DEFAULT = 1 AND PROJECT_TEMPLATE_ID = @NewTemplateId) AS NEW_STATUS_ID
	FROM TST_RISK INC
		INNER JOIN TST_RISK_STATUS T1 ON INC.RISK_STATUS_ID = T1.RISK_STATUS_ID
	WHERE INC.PROJECT_ID = @ProjectId
		AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
		AND T1.NAME NOT IN (SELECT NAME FROM TST_RISK_STATUS WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)
	) MAP
	ON INC.RISK_ID = MAP.RISK_ID
WHERE 
	MAP.RISK_ID = INC.RISK_ID
	
--Risk Priority
UPDATE INC
	SET INC.RISK_PROBABILITY_ID = MAP.NEW_PROBABILITY_ID
FROM 
	TST_RISK INC INNER JOIN (
	SELECT INC.RISK_ID, T1.RISK_PROBABILITY_ID AS OLD_PROBABILITY_ID, T2.RISK_PROBABILITY_ID AS NEW_PROBABILITY_ID
	FROM TST_RISK INC
		INNER JOIN TST_RISK_PROBABILITY T1 ON INC.RISK_PROBABILITY_ID = T1.RISK_PROBABILITY_ID
		INNER JOIN TST_RISK_PROBABILITY T2 ON T1.NAME = T2.NAME		
	WHERE INC.PROJECT_ID = @ProjectId
		AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
		AND T2.PROJECT_TEMPLATE_ID = @NewTemplateId
	UNION	
	SELECT INC.RISK_ID, T1.RISK_PROBABILITY_ID AS OLD_PROBABILITY_ID, NULL AS NEW_PROBABILITY_ID
	FROM TST_RISK INC
		INNER JOIN TST_RISK_PROBABILITY T1 ON INC.RISK_PROBABILITY_ID = T1.RISK_PROBABILITY_ID
	WHERE INC.PROJECT_ID = @ProjectId
		AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
		AND T1.NAME NOT IN (SELECT NAME FROM TST_RISK_PROBABILITY WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)
	) MAP
	ON INC.RISK_ID = MAP.RISK_ID
WHERE 
	MAP.RISK_ID = INC.RISK_ID
		
--Risk Severity
UPDATE INC
	SET INC.RISK_IMPACT_ID = MAP.NEW_IMPACT_ID
FROM 
	TST_RISK INC INNER JOIN (
	SELECT INC.RISK_ID, T1.RISK_IMPACT_ID AS OLD_IMPACT_ID, T2.RISK_IMPACT_ID AS NEW_IMPACT_ID
	FROM TST_RISK INC
		INNER JOIN TST_RISK_IMPACT T1 ON INC.RISK_IMPACT_ID = T1.RISK_IMPACT_ID
		INNER JOIN TST_RISK_IMPACT T2 ON T1.NAME = T2.NAME		
	WHERE INC.PROJECT_ID = @ProjectId
		AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
		AND T2.PROJECT_TEMPLATE_ID = @NewTemplateId
	UNION	
	SELECT INC.RISK_ID, T1.RISK_IMPACT_ID AS OLD_IMPACT_ID, NULL AS NEW_IMPACT_ID
	FROM TST_RISK INC
		INNER JOIN TST_RISK_IMPACT T1 ON INC.RISK_IMPACT_ID = T1.RISK_IMPACT_ID
	WHERE INC.PROJECT_ID = @ProjectId
		AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
		AND T1.NAME NOT IN (SELECT NAME FROM TST_RISK_IMPACT WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)
	) MAP
	ON INC.RISK_ID = MAP.RISK_ID
WHERE 
	MAP.RISK_ID = INC.RISK_ID
END
GO
