-- =============================================
-- Author:			Inflectra Corporation
-- Business Object: Template
-- Description:		Displays the number of standard fields that will be defaulted/nulled if a template change occurs
-- =============================================
IF OBJECT_ID ( 'TEMPLATE_REMAP_STANDARD_FIELDS_INFORMATION', 'P' ) IS NOT NULL 
    DROP PROCEDURE TEMPLATE_REMAP_STANDARD_FIELDS_INFORMATION;
GO
CREATE PROCEDURE TEMPLATE_REMAP_STANDARD_FIELDS_INFORMATION
	@ProjectId INT,
	@OldTemplateId INT,
	@NewTemplateId INT
AS
BEGIN
	SET NOCOUNT ON;

-- Requirement Type
SELECT 'Requirement' AS ARTIFACT_TYPE, 'Type' AS ARTIFACT_FIELD, COUNT(INC.REQUIREMENT_ID) AS AFFECTED_ITEMS
FROM TST_REQUIREMENT INC
	INNER JOIN TST_REQUIREMENT_TYPE T1 ON INC.REQUIREMENT_TYPE_ID = T1.REQUIREMENT_TYPE_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_REQUIREMENT_TYPE WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION

--Requirement Importance
SELECT 'Requirement' AS ARTIFACT_TYPE, 'Importance' AS ARTIFACT_FIELD, COUNT(INC.REQUIREMENT_ID) AS AFFECTED_ITEMS
FROM TST_REQUIREMENT INC
	INNER JOIN TST_IMPORTANCE T1 ON INC.IMPORTANCE_ID = T1.IMPORTANCE_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_IMPORTANCE WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION

-- Test Case Types	
SELECT 'Test Case' AS ARTIFACT_TYPE, 'Type' AS ARTIFACT_FIELD, COUNT(INC.TEST_CASE_ID) AS AFFECTED_ITEMS
FROM TST_TEST_CASE INC
	INNER JOIN TST_TEST_CASE_TYPE T1 ON INC.TEST_CASE_TYPE_ID = T1.TEST_CASE_TYPE_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_TEST_CASE_TYPE WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION

--Test Case Priority
SELECT 'Test Case' AS ARTIFACT_TYPE, 'Priority' AS ARTIFACT_FIELD, COUNT(INC.TEST_CASE_ID) AS AFFECTED_ITEMS
FROM TST_TEST_CASE INC
	INNER JOIN TST_TEST_CASE_PRIORITY T1 ON INC.TEST_CASE_PRIORITY_ID = T1.TEST_CASE_PRIORITY_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_TEST_CASE_PRIORITY WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION

-- Task Types	
SELECT 'Task' AS ARTIFACT_TYPE, 'Type' AS ARTIFACT_FIELD, COUNT(INC.TASK_ID) AS AFFECTED_ITEMS
FROM TST_TASK INC
	INNER JOIN TST_TASK_TYPE T1 ON INC.TASK_TYPE_ID = T1.TASK_TYPE_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_TASK_TYPE WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION

--Task Priority
SELECT 'Task' AS ARTIFACT_TYPE, 'Priority' AS ARTIFACT_FIELD, COUNT(INC.TASK_ID) AS AFFECTED_ITEMS
FROM TST_TASK INC
	INNER JOIN TST_TASK_PRIORITY T1 ON INC.TASK_PRIORITY_ID = T1.TASK_PRIORITY_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_TASK_PRIORITY WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION

-- Incident Types	
SELECT 'Incident' AS ARTIFACT_TYPE, 'Type' AS ARTIFACT_FIELD, COUNT(INC.INCIDENT_ID) AS AFFECTED_ITEMS
FROM TST_INCIDENT INC
	INNER JOIN TST_INCIDENT_TYPE T1 ON INC.INCIDENT_TYPE_ID = T1.INCIDENT_TYPE_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_INCIDENT_TYPE WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION

-- Incident Status
SELECT 'Incident' AS ARTIFACT_TYPE, 'Status' AS ARTIFACT_FIELD, COUNT(INC.INCIDENT_ID) AS AFFECTED_ITEMS
FROM TST_INCIDENT INC
	INNER JOIN TST_INCIDENT_STATUS T1 ON INC.INCIDENT_STATUS_ID = T1.INCIDENT_STATUS_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_INCIDENT_STATUS WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION
	
--Incident Priority
SELECT 'Incident' AS ARTIFACT_TYPE, 'Priority' AS ARTIFACT_FIELD, COUNT(INC.INCIDENT_ID) AS AFFECTED_ITEMS
FROM TST_INCIDENT INC
	INNER JOIN TST_INCIDENT_PRIORITY T1 ON INC.PRIORITY_ID = T1.PRIORITY_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_INCIDENT_PRIORITY WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION
		
--Incident Severity
SELECT 'Incident' AS ARTIFACT_TYPE, 'Severity' AS ARTIFACT_FIELD, COUNT(INC.INCIDENT_ID) AS AFFECTED_ITEMS
FROM TST_INCIDENT INC
	INNER JOIN TST_INCIDENT_SEVERITY T1 ON INC.SEVERITY_ID = T1.SEVERITY_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_INCIDENT_SEVERITY WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION

-- Risk Types	
SELECT 'Risk' AS ARTIFACT_TYPE, 'Type' AS ARTIFACT_FIELD, COUNT(INC.RISK_ID) AS AFFECTED_ITEMS
FROM TST_RISK INC
	INNER JOIN TST_RISK_TYPE T1 ON INC.RISK_TYPE_ID = T1.RISK_TYPE_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_RISK_TYPE WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION

-- Risk Status
SELECT 'Risk' AS ARTIFACT_TYPE, 'Status' AS ARTIFACT_FIELD, COUNT(INC.RISK_ID) AS AFFECTED_ITEMS
FROM TST_RISK INC
	INNER JOIN TST_RISK_STATUS T1 ON INC.RISK_STATUS_ID = T1.RISK_STATUS_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_RISK_STATUS WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION

--Risk Probability
SELECT 'Risk' AS ARTIFACT_TYPE, 'Probability' AS ARTIFACT_FIELD, COUNT(INC.RISK_ID) AS AFFECTED_ITEMS
FROM TST_RISK INC
	INNER JOIN TST_RISK_PROBABILITY T1 ON INC.RISK_PROBABILITY_ID = T1.RISK_PROBABILITY_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_RISK_PROBABILITY WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)
		
UNION
		
--Risk Impact
SELECT 'Risk' AS ARTIFACT_TYPE, 'Impact' AS ARTIFACT_FIELD, COUNT(INC.RISK_ID) AS AFFECTED_ITEMS
FROM TST_RISK INC
	INNER JOIN TST_RISK_IMPACT T1 ON INC.RISK_IMPACT_ID = T1.RISK_IMPACT_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_RISK_IMPACT WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION

-- Document Types	
SELECT 'Document' AS ARTIFACT_TYPE, 'Type' AS ARTIFACT_FIELD, COUNT(INC.ATTACHMENT_ID) AS AFFECTED_ITEMS
FROM TST_PROJECT_ATTACHMENT INC
	INNER JOIN TST_DOCUMENT_TYPE T1 ON INC.DOCUMENT_TYPE_ID = T1.DOCUMENT_TYPE_ID
WHERE INC.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_DOCUMENT_TYPE WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

UNION

-- Document Status
SELECT 'Document' AS ARTIFACT_TYPE, 'Status' AS ARTIFACT_FIELD, COUNT(INC.ATTACHMENT_ID) AS AFFECTED_ITEMS
FROM TST_ATTACHMENT INC
	INNER JOIN TST_DOCUMENT_STATUS T1 ON INC.DOCUMENT_STATUS_ID = T1.DOCUMENT_STATUS_ID
	INNER JOIN TST_PROJECT_ATTACHMENT PAT ON INC.ATTACHMENT_ID = PAT.ATTACHMENT_ID
WHERE PAT.PROJECT_ID = @ProjectId
	AND T1.PROJECT_TEMPLATE_ID = @OldTemplateId
	AND T1.NAME NOT IN (SELECT NAME FROM TST_DOCUMENT_STATUS WHERE PROJECT_TEMPLATE_ID = @NewTemplateId)

--Order Clause
ORDER BY ARTIFACT_TYPE, ARTIFACT_FIELD

END
GO
