SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('[dbo].[VM_Report_ActualResults]', 'P') IS NOT NULL 
	DROP PROCEDURE [dbo].[VM_Report_ActualResults]
GO

-- =============================================
-- Author:		Gerald Green
-- Create date: 2021.03.31
-- Description:	Build a dataset that replaces the Attachment_ID with the Attachment_Version_ID in both the EXPECTED_RESULT and ACTUAL_RESULT
-- =============================================
CREATE PROCEDURE VM_Report_ActualResults
	@TestRunId INT = 0
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @ResutsTable TABLE(
		TEST_RUN_ID INT, 
		TEST_STEP_ID INT, 
		POSITION INT, 
		DESCRIPTION NVARCHAR(MAX), 

		/*** EXPECTED RESULTS ***/
		ER_ATTACHMENT_VERSION_ID NVARCHAR(50), 
		ER_ATTACHMENT_ID NVARCHAR(50),
		EXPECTED_RESULT_Original NVARCHAR(MAX),
		EXPECTED_RESULT NVARCHAR(MAX), 
		/*** ACTUAL RESULTS ***/
		AR_ATTACHMENT_VERSION_ID NVARCHAR(50), 
		AR_ATTACHMENT_ID NVARCHAR(50),
		ACTUAL_RESULT_Original NVARCHAR(MAX),
		ACTUAL_RESULT NVARCHAR(MAX),

		EXECUTION_STATUS_NAME NVARCHAR(50),
		END_DATE DATETIME,
		CUST_14 NVARCHAR(50),
		CUST_02 NVARCHAR(50)
	)
 
	INSERT INTO @ResutsTable 
		SELECT 
			VW_TESTRUNSTEP_LIST.TEST_RUN_ID, 
			VW_TESTRUNSTEP_LIST.TEST_STEP_ID, 
			VW_TESTRUNSTEP_LIST.POSITION, 
			VW_TESTRUNSTEP_LIST.DESCRIPTION, 
			0,0,
			VW_TESTRUNSTEP_LIST.EXPECTED_RESULT, 
			VW_TESTRUNSTEP_LIST.EXPECTED_RESULT, 
			0,0,
			VW_TESTRUNSTEP_LIST.ACTUAL_RESULT, 
			VW_TESTRUNSTEP_LIST.ACTUAL_RESULT, 
			VW_TESTRUNSTEP_LIST.EXECUTION_STATUS_NAME, 
			VW_TESTRUNSTEP_LIST.END_DATE, 
			VW_TESTCASE_LIST.CUST_14, 
			VW_TESTRUN_LIST.CUST_02 
		FROM (dbo.VW_TESTRUNSTEP_LIST 
			INNER JOIN dbo.VW_TESTCASE_LIST 
				ON dbo.VW_TESTRUNSTEP_LIST.TEST_CASE_ID = dbo.VW_TESTCASE_LIST.TEST_CASE_ID) 
			INNER JOIN dbo.VW_TESTRUN_LIST 
				ON dbo.VW_TESTRUNSTEP_LIST.TEST_RUN_ID = dbo.VW_TESTRUN_LIST.TEST_RUN_ID 
		WHERE (VW_TESTRUNSTEP_LIST.TEST_RUN_ID = @TestRunId) 
		ORDER BY VW_TESTRUNSTEP_LIST.TEST_RUN_ID, VW_TESTRUNSTEP_LIST.TEST_STEP_ID

-- EXPECTED RESULTS
	UPDATE @ResutsTable
	SET ER_ATTACHMENT_ID = SUBSTRING(EXPECTED_RESULT, PATINDEX('%Attachment/%', EXPECTED_RESULT)+11, (PATINDEX('%.aspx%', EXPECTED_RESULT)) - (PATINDEX('%Attachment/%', EXPECTED_RESULT)+11))
	WHERE EXPECTED_RESULT LIKE '%img src%'

	UPDATE @ResutsTable
	SET ER_ATTACHMENT_VERSION_ID = moo.ATTACHMENT_VERSION_ID
	FROM @ResutsTable ert INNER JOIN TST_ATTACHMENT_VERSION moo ON ert.ER_ATTACHMENT_ID = moo.ATTACHMENT_ID AND IS_CURRENT = 1

	UPDATE @ResutsTable
	SET EXPECTED_RESULT = REPLACE(EXPECTED_RESULT,ER_ATTACHMENT_ID, ER_ATTACHMENT_VERSION_ID)
	WHERE ER_ATTACHMENT_ID > 0



-- ACTUAL RESULTS
	UPDATE @ResutsTable
	SET AR_ATTACHMENT_ID = SUBSTRING(ACTUAL_RESULT, PATINDEX('%Attachment/%', ACTUAL_RESULT)+11, (PATINDEX('%.aspx%', ACTUAL_RESULT)) - (PATINDEX('%Attachment/%', ACTUAL_RESULT)+11))
	WHERE ACTUAL_RESULT LIKE '%img src%'

	UPDATE @ResutsTable
	SET AR_ATTACHMENT_VERSION_ID = moo.ATTACHMENT_VERSION_ID
	FROM @ResutsTable ert INNER JOIN TST_ATTACHMENT_VERSION moo ON ert.AR_ATTACHMENT_ID = moo.ATTACHMENT_ID AND IS_CURRENT = 1

	UPDATE @ResutsTable
	SET ACTUAL_RESULT = REPLACE(ACTUAL_RESULT,AR_ATTACHMENT_ID, AR_ATTACHMENT_VERSION_ID)
	WHERE AR_ATTACHMENT_ID > 0


	--FINAL RESULTS
	SELECT * FROM @ResutsTable
	ORDER BY POSITION

END
GO
