-- ===================================================================================================
-- Author:			Inflectra Corporation
-- Business Object: Portfolio
-- Description:		Refreshes the requirement count, overall percent complete for the portfolio
-- ===================================================================================================
IF OBJECT_ID ( 'PORTFOLIO_REFRESH_REQUIREMENT_COMPLETION', 'P' ) IS NOT NULL 
    DROP PROCEDURE PORTFOLIO_REFRESH_REQUIREMENT_COMPLETION;
GO
CREATE PROCEDURE PORTFOLIO_REFRESH_REQUIREMENT_COMPLETION
	@PortfolioId INT
AS
BEGIN							
	--Next we update the portfolio (if exists) with the percentage complete and requirement counts
	MERGE TST_PORTFOLIO AS TARGET	
	USING (
		SELECT
			PRG.PORTFOLIO_ID,
			SUM(PRG.REQUIREMENT_COUNT) AS REQUIREMENT_COUNT,
			SUM(PRG.PERCENT_COMPLETE * PRG.REQUIREMENT_COUNT) / SUM(PRG.REQUIREMENT_COUNT) AS PERCENT_COMPLETE
		FROM
			TST_PROJECT_GROUP PRG
		WHERE
			PRG.PORTFOLIO_ID = @PortfolioId AND
			PRG.IS_ACTIVE = 1 AND
			PRG.REQUIREMENT_COUNT > 0
		GROUP BY PRG.PORTFOLIO_ID
	) AS SOURCE
	ON
		TARGET.PORTFOLIO_ID = SOURCE.PORTFOLIO_ID
	WHEN MATCHED THEN
		UPDATE
			SET	
				TARGET.REQUIREMENT_COUNT = SOURCE.REQUIREMENT_COUNT,
				TARGET.PERCENT_COMPLETE = SOURCE.PERCENT_COMPLETE
	WHEN NOT MATCHED BY SOURCE AND TARGET.PORTFOLIO_ID = @PortfolioId THEN
			UPDATE
			SET	
				TARGET.REQUIREMENT_COUNT = 0,
				TARGET.PERCENT_COMPLETE = 0;
				
	--Next we update the portfolio with the min/max start/end dates
	MERGE TST_PORTFOLIO AS TARGET	
	USING (
		SELECT
			PRG.PORTFOLIO_ID,
			MIN(PRG.START_DATE) AS MIN_START_DATE,
			MAX(PRG.END_DATE) AS MAX_END_DATE
		FROM
			TST_PROJECT_GROUP PRG
		WHERE
			PRG.PORTFOLIO_ID = @PortfolioId AND
			PRG.IS_ACTIVE = 1 AND
			PRG.START_DATE IS NOT NULL AND
			PRG.END_DATE IS NOT NULL
		GROUP BY PRG.PORTFOLIO_ID
	) AS SOURCE
	ON
		TARGET.PORTFOLIO_ID = SOURCE.PORTFOLIO_ID
	WHEN MATCHED THEN
		UPDATE
			SET	
				TARGET.START_DATE = SOURCE.MIN_START_DATE,
				TARGET.END_DATE = SOURCE.MAX_END_DATE
	WHEN NOT MATCHED BY SOURCE AND TARGET.PORTFOLIO_ID = @PortfolioId THEN
			UPDATE
			SET	
				TARGET.START_DATE = NULL,
				TARGET.END_DATE = NULL;
END
GO
