-- =============================================
-- Author:			Inflectra Corporation
-- Business Object: Project
-- Description:		Deletes Project Requirements
-- =============================================
IF OBJECT_ID ( 'PROJECT_DELETE_REQUIREMENTS', 'P' ) IS NOT NULL 
    DROP PROCEDURE PROJECT_DELETE_REQUIREMENTS;
GO
CREATE PROCEDURE PROJECT_DELETE_REQUIREMENTS
	@ProjectId INT
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM TST_REQUIREMENT_TEST_CASE WHERE REQUIREMENT_ID IN (SELECT REQUIREMENT_ID FROM TST_REQUIREMENT WHERE PROJECT_ID = @ProjectId)
	DELETE FROM TST_REQUIREMENT_USER WHERE REQUIREMENT_ID IN (SELECT REQUIREMENT_ID FROM TST_REQUIREMENT WHERE PROJECT_ID = @ProjectId)
	DELETE FROM TST_REQUIREMENT WHERE PROJECT_ID = @ProjectId
END
GO
