-- =============================================
-- Author:			Inflectra Corporation
-- Business Object: Project
-- Description:		Deletes Project Test Cases & Tasks
-- =============================================
IF OBJECT_ID ( 'PROJECT_DELETE_TEST_CASES_TASKS', 'P' ) IS NOT NULL 
    DROP PROCEDURE PROJECT_DELETE_TEST_CASES_TASKS;
GO
CREATE PROCEDURE PROJECT_DELETE_TEST_CASES_TASKS
	@ProjectId INT
AS
BEGIN
	SET NOCOUNT ON;
    --Next we need to delete all the test cases associated with the project
    --including test steps, parameters, release/req mappings and all user navigation
    --The association between test steps and incidents will already have been handled by the
    --incident delete section
    DELETE FROM TST_TEST_STEP_PARAMETER WHERE TEST_STEP_ID IN (SELECT TEST_STEP_ID FROM TST_TEST_STEP WHERE TEST_CASE_ID IN (SELECT TEST_CASE_ID FROM TST_TEST_CASE WHERE PROJECT_ID = @ProjectId))
    DELETE FROM TST_REQUIREMENT_TEST_STEP WHERE TEST_STEP_ID IN (SELECT TEST_STEP_ID FROM TST_TEST_STEP WHERE TEST_CASE_ID IN (SELECT TEST_CASE_ID FROM TST_TEST_CASE WHERE PROJECT_ID = @ProjectId))
    DELETE FROM TST_TEST_STEP WHERE TEST_CASE_ID IN (SELECT TEST_CASE_ID FROM TST_TEST_CASE WHERE PROJECT_ID = @ProjectId)
    DELETE FROM TST_TEST_CASE_PARAMETER WHERE TEST_CASE_ID IN (SELECT TEST_CASE_ID FROM TST_TEST_CASE WHERE PROJECT_ID = @ProjectId)
    DELETE FROM TST_REQUIREMENT_TEST_CASE WHERE TEST_CASE_ID IN (SELECT TEST_CASE_ID FROM TST_TEST_CASE WHERE PROJECT_ID = @ProjectId)
    DELETE FROM TST_RELEASE_TEST_CASE WHERE TEST_CASE_ID IN (SELECT TEST_CASE_ID FROM TST_TEST_CASE WHERE PROJECT_ID = @ProjectId)
    DELETE FROM TST_TEST_CASE WHERE PROJECT_ID = @ProjectId
    UPDATE TST_TEST_CASE_FOLDER SET PARENT_TEST_CASE_FOLDER_ID = NULL WHERE PROJECT_ID = @ProjectId
    DELETE FROM TST_TEST_CASE_FOLDER WHERE PROJECT_ID = @ProjectId

    --Now we need to delete all the project task folders (tasks are cascaded automatically)
    UPDATE TST_TASK_FOLDER SET PARENT_TASK_FOLDER_ID = NULL WHERE PROJECT_ID = @ProjectId
    DELETE FROM TST_TASK_FOLDER WHERE PROJECT_ID = @ProjectId
	DELETE FROM TST_VERSION_CONTROL_PULL_REQUEST WHERE TASK_ID IN (SELECT TASK_ID FROM TST_TASK WHERE PROJECT_ID = @ProjectId)
END
GO
