-- =============================================
-- Author:			Inflectra Corporation
-- Business Object: Project
-- Description:		Deletes Project Associations
-- =============================================
IF OBJECT_ID ( 'PROJECT_DELETE_ASSOCIATIONS', 'P' ) IS NOT NULL 
    DROP PROCEDURE PROJECT_DELETE_ASSOCIATIONS;
GO
CREATE PROCEDURE PROJECT_DELETE_ASSOCIATIONS
	@ProjectId INT
AS
BEGIN
	SET NOCOUNT ON;
	--Requirements
    DELETE FROM TST_ARTIFACT_LINK WHERE SOURCE_ARTIFACT_TYPE_ID = 1 AND SOURCE_ARTIFACT_ID IN (SELECT REQUIREMENT_ID FROM TST_REQUIREMENT WHERE PROJECT_ID = @ProjectId)
    DELETE FROM TST_ARTIFACT_LINK WHERE DEST_ARTIFACT_TYPE_ID = 1 AND DEST_ARTIFACT_ID IN (SELECT REQUIREMENT_ID FROM TST_REQUIREMENT WHERE PROJECT_ID = @ProjectId)
	--Incidents
    DELETE FROM TST_ARTIFACT_LINK WHERE SOURCE_ARTIFACT_TYPE_ID = 3 AND SOURCE_ARTIFACT_ID IN (SELECT INCIDENT_ID FROM TST_INCIDENT WHERE PROJECT_ID = @ProjectId)
    DELETE FROM TST_ARTIFACT_LINK WHERE DEST_ARTIFACT_TYPE_ID = 3 AND DEST_ARTIFACT_ID IN (SELECT INCIDENT_ID FROM TST_INCIDENT WHERE PROJECT_ID = @ProjectId)
	--Tasks
    DELETE FROM TST_ARTIFACT_LINK WHERE SOURCE_ARTIFACT_TYPE_ID = 6 AND SOURCE_ARTIFACT_ID IN (SELECT TASK_ID FROM TST_TASK WHERE PROJECT_ID = @ProjectId)
    DELETE FROM TST_ARTIFACT_LINK WHERE DEST_ARTIFACT_TYPE_ID = 6 AND DEST_ARTIFACT_ID IN (SELECT TASK_ID FROM TST_TASK WHERE PROJECT_ID = @ProjectId)
	--Test Runs
    DELETE FROM TST_ARTIFACT_LINK WHERE SOURCE_ARTIFACT_TYPE_ID = 5 AND SOURCE_ARTIFACT_ID IN (SELECT TR.TEST_RUN_ID FROM TST_TEST_RUN TR INNER JOIN TST_TEST_CASE TC ON TR.TEST_CASE_ID = TC.TEST_CASE_ID WHERE TC.PROJECT_ID = @ProjectId)
    DELETE FROM TST_ARTIFACT_LINK WHERE DEST_ARTIFACT_TYPE_ID = 5 AND DEST_ARTIFACT_ID IN (SELECT TR.TEST_RUN_ID FROM TST_TEST_RUN TR INNER JOIN TST_TEST_CASE TC ON TR.TEST_CASE_ID = TC.TEST_CASE_ID WHERE TC.PROJECT_ID = @ProjectId)
	--Test Steps
    DELETE FROM TST_ARTIFACT_LINK WHERE SOURCE_ARTIFACT_TYPE_ID = 7 AND SOURCE_ARTIFACT_ID IN (SELECT TS.TEST_STEP_ID FROM TST_TEST_STEP TS INNER JOIN TST_TEST_CASE TC ON TS.TEST_CASE_ID = TC.TEST_CASE_ID WHERE TC.PROJECT_ID = @ProjectId)
    DELETE FROM TST_ARTIFACT_LINK WHERE DEST_ARTIFACT_TYPE_ID = 7 AND DEST_ARTIFACT_ID IN (SELECT TS.TEST_STEP_ID FROM TST_TEST_STEP TS INNER JOIN TST_TEST_CASE TC ON TS.TEST_CASE_ID = TC.TEST_CASE_ID WHERE TC.PROJECT_ID = @ProjectId)
END
GO
