-- =====================================================================
-- Author:			Inflectra Corporation
-- Business Object: TestConfiguration
-- Description:		Retrieves a crosstab of all the configuration values in a set
-- =====================================================================
IF OBJECT_ID ( 'TESTCONFIGURATION_RETRIEVE_CONFIG_VALUES', 'P' ) IS NOT NULL 
    DROP PROCEDURE [TESTCONFIGURATION_RETRIEVE_CONFIG_VALUES];
GO
CREATE PROCEDURE [TESTCONFIGURATION_RETRIEVE_CONFIG_VALUES]
	@TestConfigurationSetId INT
AS
BEGIN
	SELECT	TCG.TEST_CONFIGURATION_ID, TCG.POSITION, TPV.TEST_CASE_PARAMETER_ID, TPV.CUSTOM_PROPERTY_VALUE_ID,
			TCP.NAME AS PARAMETER_NAME, CPV.NAME AS PARAMETER_VALUE
	FROM TST_TEST_CONFIGURATION TCG
	INNER JOIN TST_TEST_CONFIGURATION_PARAMETER_VALUE TPV ON TCG.TEST_CONFIGURATION_ID = TPV.TEST_CONFIGURATION_ID
	INNER JOIN TST_CUSTOM_PROPERTY_VALUE CPV ON TPV.CUSTOM_PROPERTY_VALUE_ID = CPV.CUSTOM_PROPERTY_VALUE_ID
	INNER JOIN TST_TEST_CASE_PARAMETER TCP ON TPV.TEST_CASE_PARAMETER_ID = TCP.TEST_CASE_PARAMETER_ID
	WHERE TCG.TEST_CONFIGURATION_SET_ID = @TestConfigurationSetId
ORDER BY TCG.POSITION ASC, TEST_CASE_PARAMETER_ID ASC, TCG.TEST_CONFIGURATION_ID
END
GO
