-- =====================================================================
-- Author:			Inflectra Corporation
-- Description:		Adds the requirement count and some other fields needed in 6.5
-- =====================================================================

IF COL_LENGTH('TST_RELEASE', 'REQUIREMENT_COUNT') IS NULL
BEGIN
	ALTER TABLE [TST_RELEASE]
	ADD [REQUIREMENT_COUNT] INTEGER DEFAULT 0 NOT NULL
END
GO

IF COL_LENGTH('TST_RELEASE', 'PLANNED_POINTS') IS NULL
BEGIN
	ALTER TABLE [TST_RELEASE]
	ADD [PLANNED_POINTS] DECIMAL(9,1)
END
GO

IF COL_LENGTH('TST_RELEASE', 'REQUIREMENT_POINTS') IS NULL
BEGIN
	ALTER TABLE [TST_RELEASE]
	ADD [REQUIREMENT_POINTS] DECIMAL(9,1)
END
GO

IF COL_LENGTH('TST_PROJECT', 'REQUIREMENT_COUNT') IS NULL
BEGIN
	ALTER TABLE [TST_PROJECT]
	ADD [REQUIREMENT_COUNT] INTEGER DEFAULT 0 NOT NULL
END
GO

IF COL_LENGTH('TST_PROJECT_GROUP', 'REQUIREMENT_COUNT') IS NULL
BEGIN
	ALTER TABLE [TST_PROJECT_GROUP]
	ADD [REQUIREMENT_COUNT] INTEGER DEFAULT 0 NOT NULL
END
GO

IF COL_LENGTH('TST_PORTFOLIO', 'REQUIREMENT_COUNT') IS NULL
BEGIN
	ALTER TABLE [TST_PORTFOLIO]
	ADD [REQUIREMENT_COUNT] INTEGER DEFAULT 0 NOT NULL
END
GO
