-- Inserts the 'Planned POints' into the Artifact Field table.
IF NOT EXISTS (
	SELECT * FROM [TST_ARTIFACT_FIELD]
	WHERE [NAME] = 'PlannedPoints')
BEGIN
	INSERT INTO [TST_ARTIFACT_FIELD]
		([ARTIFACT_TYPE_ID],[NAME],[LOOKUP_PROPERTY],[CAPTION],[ARTIFACT_FIELD_TYPE_ID],[IS_WORKFLOW_CONFIG],[IS_LIST_CONFIG],[IS_LIST_DEFAULT],[LIST_DEFAULT_POSITION],[IS_ACTIVE],[IS_DATA_MAPPING],[IS_REPORT],[IS_NOTIFY],[IS_HISTORY_RECORDED],[DESCRIPTION]) VALUES
		(4,'PlannedPoints',NULL,'Planned Points',13,1,1,0,24,1,0,1,1,1,'The planned story points')
END
GO

---Creates the hierarchy tables.
IF OBJECT_ID('TST_TEST_CASE_FOLDER_HIERARCHY', 'U') IS NULL
BEGIN
	CREATE TABLE [TST_TEST_CASE_FOLDER_HIERARCHY] (
		[TEST_CASE_FOLDER_ID] INTEGER NOT NULL,
		[PROJECT_ID] INTEGER NOT NULL,
		[NAME] NVARCHAR(255),
		[PARENT_TEST_CASE_FOLDER_ID] INTEGER,
		[HIERARCHY_LEVEL] INTEGER,
		[INDENT_LEVEL] NVARCHAR(255) COLLATE Latin1_General_BIN,
		CONSTRAINT [PK_TST_TEST_CASE_FOLDER_HIERARCHY] PRIMARY KEY ([TEST_CASE_FOLDER_ID])
	)
	CREATE INDEX [IDX_TST_TEST_CASE_FOLDER_HIERARCHY_1_FK] ON [TST_TEST_CASE_FOLDER_HIERARCHY] ([PROJECT_ID])
	ALTER TABLE [TST_TEST_CASE_FOLDER_HIERARCHY] ADD CONSTRAINT [FK_TST_PROJECT_TST_TEST_CASE_FOLDER_HIERARCHY] 
		FOREIGN KEY ([PROJECT_ID]) REFERENCES [TST_PROJECT] ([PROJECT_ID]) ON DELETE CASCADE
END
GO

IF OBJECT_ID('TST_TEST_SET_FOLDER_HIERARCHY', 'U') IS NULL
BEGIN
	CREATE TABLE [TST_TEST_SET_FOLDER_HIERARCHY] (
		[TEST_SET_FOLDER_ID] INTEGER NOT NULL,
		[PROJECT_ID] INTEGER NOT NULL,
		[NAME] NVARCHAR(255),
		[PARENT_TEST_SET_FOLDER_ID] INTEGER,
		[HIERARCHY_LEVEL] INTEGER,
		[INDENT_LEVEL] NVARCHAR(255) COLLATE Latin1_General_BIN,
		CONSTRAINT [PK_TST_TEST_SET_FOLDER_HIERARCHY] PRIMARY KEY ([TEST_SET_FOLDER_ID])
	)
	CREATE INDEX [IDX_TST_TEST_SET_FOLDER_HIERARCHY_1_FK] ON [TST_TEST_SET_FOLDER_HIERARCHY] ([PROJECT_ID])
	ALTER TABLE [TST_TEST_SET_FOLDER_HIERARCHY] ADD CONSTRAINT [FK_TST_PROJECT_TST_TEST_SET_FOLDER_HIERARCHY] 
		FOREIGN KEY ([PROJECT_ID]) REFERENCES [TST_PROJECT] ([PROJECT_ID]) ON DELETE CASCADE
END
GO

IF OBJECT_ID('TST_TASK_FOLDER_HIERARCHY', 'U') IS NULL
BEGIN
	CREATE TABLE [TST_TASK_FOLDER_HIERARCHY] (
		[TASK_FOLDER_ID] INTEGER NOT NULL,
		[PROJECT_ID] INTEGER NOT NULL,
		[NAME] NVARCHAR(255),
		[PARENT_TASK_FOLDER_ID] INTEGER,
		[HIERARCHY_LEVEL] INTEGER,
		[INDENT_LEVEL] NVARCHAR(255) COLLATE Latin1_General_BIN,
		CONSTRAINT [PK_TST_TASK_FOLDER_HIERARCHY] PRIMARY KEY ([TASK_FOLDER_ID])
	)
	CREATE INDEX [IDX_TST_TASK_FOLDER_HIERARCHY_1_FK] ON [TST_TASK_FOLDER_HIERARCHY] ([PROJECT_ID])
	ALTER TABLE [TST_TASK_FOLDER_HIERARCHY] ADD CONSTRAINT [FK_TST_PROJECT_TST_TASK_FOLDER_HIERARCHY] 
		FOREIGN KEY ([PROJECT_ID]) REFERENCES [TST_PROJECT] ([PROJECT_ID]) ON DELETE CASCADE
END
GO

IF OBJECT_ID('TST_PROJECT_ATTACHMENT_FOLDER_HIERARCHY', 'U') IS NULL
BEGIN
	CREATE TABLE [TST_PROJECT_ATTACHMENT_FOLDER_HIERARCHY] (
		[PROJECT_ATTACHMENT_FOLDER_ID] INTEGER NOT NULL,
		[PROJECT_ID] INTEGER NOT NULL,
		[NAME] NVARCHAR(255),
		[PARENT_PROJECT_ATTACHMENT_FOLDER_ID] INTEGER,
		[HIERARCHY_LEVEL] INTEGER,
		[INDENT_LEVEL] NVARCHAR(255) COLLATE Latin1_General_BIN,
		CONSTRAINT [PK_TST_PROJECT_ATTACHMENT_FOLDER_HIERARCHY] PRIMARY KEY ([PROJECT_ATTACHMENT_FOLDER_ID])
	)
	CREATE  INDEX [IDX_TST_PROJECT_ATTACHMENT_FOLDER_HIERARCHY_1_FK] ON [TST_PROJECT_ATTACHMENT_FOLDER_HIERARCHY] ([PROJECT_ID])
	ALTER TABLE [TST_PROJECT_ATTACHMENT_FOLDER_HIERARCHY] ADD CONSTRAINT [FK_TST_PROJECT_TST_PROJECT_ATTACHMENT_FOLDER_HIERARCHY] 
		FOREIGN KEY ([PROJECT_ID]) REFERENCES [TST_PROJECT] ([PROJECT_ID]) ON DELETE CASCADE
END
GO

IF OBJECT_ID('TST_TEST_CASE_PARAMETER_HIERARCHY', 'U') IS NULL
BEGIN
	CREATE TABLE [TST_TEST_CASE_PARAMETER_HIERARCHY] (
		[TEST_CASE_PARAMETER_ID] INTEGER NOT NULL,
		[PROJECT_ID] INTEGER NOT NULL,
		[TEST_CASE_ID] INTEGER NOT NULL,
		[NAME] NVARCHAR(50) NOT NULL,
		[DEFAULT_VALUE] NVARCHAR(255),
		PRIMARY KEY ([TEST_CASE_PARAMETER_ID], [PROJECT_ID], [TEST_CASE_ID], [NAME])
	)
	CREATE  INDEX [IDX_TST_TEST_CASE_PARAMETER_HIERARCHY_1_FK] ON [TST_TEST_CASE_PARAMETER_HIERARCHY] ([PROJECT_ID])
	ALTER TABLE [TST_TEST_CASE_PARAMETER_HIERARCHY] ADD CONSTRAINT [FK_TST_PROJECT_TST_TEST_CASE_PARAMETER_HIERARCHY] 
		FOREIGN KEY ([PROJECT_ID]) REFERENCES [TST_PROJECT] ([PROJECT_ID]) ON DELETE CASCADE
END
GO

IF OBJECT_ID('TST_TEST_CASE_PARAMETER_HIERARCHY_ALREADY_SET', 'U') IS NULL
BEGIN
	CREATE TABLE [TST_TEST_CASE_PARAMETER_HIERARCHY_ALREADY_SET] (
		[TEST_CASE_PARAMETER_ID] INTEGER NOT NULL,
		[PROJECT_ID] INTEGER NOT NULL,
		[TEST_CASE_ID] INTEGER NOT NULL,
		[NAME] NVARCHAR(50) NOT NULL,
		[DEFAULT_VALUE] NVARCHAR(255),
		PRIMARY KEY ([TEST_CASE_PARAMETER_ID], [PROJECT_ID], [TEST_CASE_ID], [NAME])
	)
	CREATE  INDEX [IDX_TST_TEST_CASE_PARAMETER_HIERARCHY_ALREADY_SET_1_FK] ON [TST_TEST_CASE_PARAMETER_HIERARCHY_ALREADY_SET] ([PROJECT_ID])
	ALTER TABLE [TST_TEST_CASE_PARAMETER_HIERARCHY_ALREADY_SET] ADD CONSTRAINT [FK_TST_PROJECT_TST_TEST_CASE_PARAMETER_HIERARCHY_ALREADY_SET] 
		FOREIGN KEY ([PROJECT_ID]) REFERENCES [TST_PROJECT] ([PROJECT_ID]) ON DELETE CASCADE
END
GO

-- Add Project Collection properties.
IF (SELECT COUNT(*) FROM [TST_PROJECT_COLLECTION] WHERE [NAME] = 'Admin.Baseline.Filters') = 0
	INSERT INTO [TST_PROJECT_COLLECTION] VALUES
		('Admin.Baseline.Filters', 'Y');
GO

IF (SELECT COUNT(*) FROM [TST_PROJECT_COLLECTION] WHERE [NAME] = 'Admin.Baseline.SortExpression') = 0
	INSERT INTO [TST_PROJECT_COLLECTION] VALUES
		('Admin.Baseline.SortExpression', 'Y');
GO

IF (SELECT COUNT(*) FROM [TST_PROJECT_COLLECTION] WHERE [NAME] = 'Admin.Baseline.Pagination') = 0
	INSERT INTO [TST_PROJECT_COLLECTION] VALUES
		('Admin.Baseline.Pagination', 'Y');
GO

IF (SELECT COUNT(*) FROM [TST_PROJECT_COLLECTION] WHERE [NAME] = 'Artifact.Baseline.Filters') = 0
	INSERT INTO [TST_PROJECT_COLLECTION] VALUES
		('Artifact.Baseline.Filters', 'Y');
GO

IF (SELECT COUNT(*) FROM [TST_PROJECT_COLLECTION] WHERE [NAME] = 'Artifact.Baseline.SortExpression') = 0
	INSERT INTO [TST_PROJECT_COLLECTION] VALUES
		('Artifact.Baseline.SortExpression', 'Y');
GO

IF (SELECT COUNT(*) FROM [TST_PROJECT_COLLECTION] WHERE [NAME] = 'Artifact.Baseline.Pagination') = 0
	INSERT INTO [TST_PROJECT_COLLECTION] VALUES
		('Artifact.Baseline.Pagination', 'Y');
GO
