-- =====================================================================
-- Author:			Inflectra Corporation
-- Description:		Adds/updates artifact fields
-- =====================================================================

IF NOT EXISTS(SELECT NAME FROM TST_ARTIFACT_FIELD WHERE ARTIFACT_FIELD_ID = 202)
BEGIN
	SET IDENTITY_INSERT TST_ARTIFACT_FIELD ON;
	INSERT INTO TST_ARTIFACT_FIELD
	(
	ARTIFACT_FIELD_ID, ARTIFACT_TYPE_ID, NAME, LOOKUP_PROPERTY, CAPTION, ARTIFACT_FIELD_TYPE_ID, IS_WORKFLOW_CONFIG, IS_LIST_CONFIG, IS_LIST_DEFAULT, LIST_DEFAULT_POSITION, IS_ACTIVE, IS_DATA_MAPPING, IS_REPORT, IS_NOTIFY, IS_HISTORY_RECORDED, DESCRIPTION
	)
	VALUES
	(
	202, 4, 'RequirementCount', NULL, 'Req. Count', 8, 1, 1, 0, 22, 1, 0, 1, 1, 1, 'The number of requirements in the release/sprint'
	);
	SET IDENTITY_INSERT TST_ARTIFACT_FIELD OFF;
END
GO

IF NOT EXISTS(SELECT NAME FROM TST_ARTIFACT_FIELD WHERE ARTIFACT_FIELD_ID = 203)
BEGIN
	SET IDENTITY_INSERT TST_ARTIFACT_FIELD ON;
	INSERT INTO TST_ARTIFACT_FIELD
	(
	ARTIFACT_FIELD_ID, ARTIFACT_TYPE_ID, NAME, LOOKUP_PROPERTY, CAPTION, ARTIFACT_FIELD_TYPE_ID, IS_WORKFLOW_CONFIG, IS_LIST_CONFIG, IS_LIST_DEFAULT, LIST_DEFAULT_POSITION, IS_ACTIVE, IS_DATA_MAPPING, IS_REPORT, IS_NOTIFY, IS_HISTORY_RECORDED, DESCRIPTION
	)
	VALUES
	(
	203, 4, 'RequirementPoints', NULL, 'Req. Points', 13, 1, 1, 0, 23, 1, 0, 1, 1, 1, 'The count of requirements points'
	);
	SET IDENTITY_INSERT TST_ARTIFACT_FIELD OFF;
END
GO

IF NOT EXISTS(SELECT NAME FROM TST_ARTIFACT_FIELD WHERE ARTIFACT_FIELD_ID = 204)
BEGIN
	SET IDENTITY_INSERT TST_ARTIFACT_FIELD ON;
	INSERT INTO TST_ARTIFACT_FIELD
	(
	ARTIFACT_FIELD_ID, ARTIFACT_TYPE_ID, NAME, LOOKUP_PROPERTY, CAPTION, ARTIFACT_FIELD_TYPE_ID, IS_WORKFLOW_CONFIG, IS_LIST_CONFIG, IS_LIST_DEFAULT, LIST_DEFAULT_POSITION, IS_ACTIVE, IS_DATA_MAPPING, IS_REPORT, IS_NOTIFY, IS_HISTORY_RECORDED, DESCRIPTION
	)
	VALUES
	(
	204, 4, 'CompletionId', NULL, 'Req. Completion', 5, 0, 1, 1, 3, 1, 0, 1, 1, 0, 'The % complete of the release by requirement'
	);
	SET IDENTITY_INSERT TST_ARTIFACT_FIELD OFF;
END
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 4 WHERE ARTIFACT_FIELD_ID = 74;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 5 WHERE ARTIFACT_FIELD_ID = 75;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 6 WHERE ARTIFACT_FIELD_ID = 80;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 7 WHERE ARTIFACT_FIELD_ID = 81;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 8, IS_LIST_DEFAULT = 0 WHERE ARTIFACT_FIELD_ID = 76;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 9 WHERE ARTIFACT_FIELD_ID = 77;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 10, IS_LIST_DEFAULT = 0 WHERE ARTIFACT_FIELD_ID = 78;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 11 WHERE ARTIFACT_FIELD_ID = 79;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 13 WHERE ARTIFACT_FIELD_ID = 82;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 12 WHERE ARTIFACT_FIELD_ID = 163;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 14 WHERE ARTIFACT_FIELD_ID = 83;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 15 WHERE ARTIFACT_FIELD_ID = 30;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 16 WHERE ARTIFACT_FIELD_ID = 31;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 17 WHERE ARTIFACT_FIELD_ID = 162;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 18 WHERE ARTIFACT_FIELD_ID = 133;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 19 WHERE ARTIFACT_FIELD_ID = 134;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 20 WHERE ARTIFACT_FIELD_ID = 98;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 21 WHERE ARTIFACT_FIELD_ID = 164;
GO
UPDATE TST_ARTIFACT_FIELD SET LIST_DEFAULT_POSITION = 22 WHERE ARTIFACT_FIELD_ID = 165;
GO
