--- FK_TST_HISTORY_CHANGESET_TST_HISTORY_ASSOCIATION
IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_TST_HISTORY_CHANGESET_TST_HISTORY_ASSOCIATION') > 0
	ALTER TABLE [TST_HISTORY_ASSOCIATION]
		DROP CONSTRAINT [FK_TST_HISTORY_CHANGESET_TST_HISTORY_ASSOCIATION]
GO

ALTER TABLE [TST_HISTORY_ASSOCIATION] 
	ADD CONSTRAINT [FK_TST_HISTORY_CHANGESET_TST_HISTORY_ASSOCIATION] 
		FOREIGN KEY ([CHANGESET_ID]) REFERENCES [TST_HISTORY_CHANGESET] ([CHANGESET_ID]) 
		ON DELETE CASCADE
GO


--- FK_TST_VERSION_CONTROL_PROJECT_TST_VERSION_CONTROL_BRANCH
IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_TST_VERSION_CONTROL_PROJECT_TST_VERSION_CONTROL_BRANCH') > 0
	ALTER TABLE [TST_VERSION_CONTROL_BRANCH]
		DROP CONSTRAINT [FK_TST_VERSION_CONTROL_PROJECT_TST_VERSION_CONTROL_BRANCH]
GO

ALTER TABLE [TST_VERSION_CONTROL_BRANCH]
	ADD CONSTRAINT [FK_TST_VERSION_CONTROL_PROJECT_TST_VERSION_CONTROL_BRANCH] 
		FOREIGN KEY ([VERSION_CONTROL_SYSTEM_ID], [PROJECT_ID]) REFERENCES [TST_VERSION_CONTROL_PROJECT] ([VERSION_CONTROL_SYSTEM_ID],[PROJECT_ID]) 
		ON DELETE CASCADE
GO

