-- Tables used for Release.
IF OBJECT_ID('TST_PERIODIC_REVIEW_ALERT', 'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[TST_PERIODIC_REVIEW_ALERT](
	[AlertId] INTEGER IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(40) NOT NULL,
	[Position] [smallint] NOT NULL,
	[AlertInDays] [smallint] NOT NULL,
	[IsActive] BIT NOT NULL,
 CONSTRAINT [XPKTST_PERIODIC_REVIEW_ALERT] PRIMARY KEY CLUSTERED ([AlertId])
) ON [PRIMARY]
END
GO


IF OBJECT_ID('TST_PERIODIC_REVIEW_NOTIFICATIONS', 'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[TST_PERIODIC_REVIEW_NOTIFICATIONS](
	[NOTIFICATION_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[RELEASE_ID] [bigint] NOT NULL,
	[SCHEDULED_DATE] [datetime] NOT NULL,
	[STATUS] NVARCHAR(20) NOT NULL,
	[IS_ACTIVE] BIT NOT NULL,
 CONSTRAINT [XPKTST_PERIODIC_REVIEW_NOTIFICATIONS] PRIMARY KEY ([NOTIFICATION_ID])
) ON [PRIMARY]
END
GO

-- Add the PERIODIC_REVIEW_ALERT_ID field to the RELEASE table.
IF COL_LENGTH('TST_RELEASE', 'PERIODIC_REVIEW_ALERT_ID') IS NULL
BEGIN
	ALTER TABLE [TST_RELEASE] ADD [PERIODIC_REVIEW_ALERT_ID] INTEGER NULL
	ALTER TABLE [TST_RELEASE] ADD CONSTRAINT [FK_TST_PERIODIC_REVIEW_ALERT_TST_RELEASE] 
		FOREIGN KEY ([PERIODIC_REVIEW_ALERT_ID]) REFERENCES [TST_PERIODIC_REVIEW_ALERT] ([AlertId]) ON DELETE SET NULL
END
GO

-- Add the [PERIODIC_REVIEW_DATE] field to the RELEASE table.
IF COL_LENGTH('TST_RELEASE', 'PERIODIC_REVIEW_ALERT_ID') IS NULL
BEGIN
	ALTER TABLE [TST_RELEASE] ADD [PERIODIC_REVIEW_DATE] DATETIME NULL
END
GO
