-- Add project collection (StaticUpdates())
IF NOT EXISTS (SELECT * FROM [TST_PROJECT_COLLECTION] WHERE [NAME] = 'RequirementsList.DocumentView')
	INSERT INTO [TST_PROJECT_COLLECTION] VALUES ('RequirementsList.DocumentView', 'Y')
GO

-- Update Notification flag (StaticUpdates())
UPDATE [TST_ARTIFACT_TYPE] SET [IS_NOTIFY] = 1 WHERE [ARTIFACT_TYPE_ID] = 4
GO

-- Update the Version Control System/Project password fields for Encryption (UpdateVersionPasswordFields())
ALTER TABLE [TST_VERSION_CONTROL_SYSTEM] ALTER COLUMN [PASSWORD] NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE [TST_VERSION_CONTROL_PROJECT] ALTER COLUMN [PASSWORD] NVARCHAR(MAX) NULL
GO
IF (COL_LENGTH('TST_VERSION_CONTROL_SYSTEM','IS_ENCRYPTED') IS NULL)
BEGIN
	ALTER TABLE [TST_VERSION_CONTROL_SYSTEM] 
		ADD [IS_ENCRYPTED] BIT NOT NULL 
			CONSTRAINT [DEF_TST_VERSION_CONTROL_SYSTEM_IS_ENCRYPTED] 
			DEFAULT (0)
END
GO
IF (COL_LENGTH('TST_VERSION_CONTROL_PROJECT','IS_ENCRYPTED') IS NULL)
BEGIN
	ALTER TABLE [TST_VERSION_CONTROL_PROJECT] 
		ADD [IS_ENCRYPTED] BIT NOT NULL 
			CONSTRAINT [DEF_TST_VERSION_CONTROL_PROJECT_IS_ENCRYPTED] 
			DEFAULT (0)
END
GO

-- Update the webhooks table. (UpdateWebhook())
ALTER TABLE [TST_NOTIFICATION_EVENT_WEBHOOK] ALTER COLUMN [PASSWORD] NVARCHAR(MAX) NULL
GO
IF (COL_LENGTH('TST_NOTIFICATION_EVENT_WEBHOOK','METHOD') IS NULL)
BEGIN
	ALTER TABLE [TST_NOTIFICATION_EVENT_WEBHOOK] 
		ADD [METHOD] NVARCHAR(10) NULL
END
GO

-- Add the new Cust Prop field. (AddCustPropField())
IF (COL_LENGTH('TST_CUSTOM_PROPERTY','DESCRIPTION') IS NULL)
BEGIN
	ALTER TABLE [TST_CUSTOM_PROPERTY] 
		ADD [DESCRIPTION] NVARCHAR(512) NULL
END
GO

-- Add new Index to Version Control table.
If (INDEXPROPERTY(Object_Id('TST_SOURCE_CODE_COMMIT'), 'AK_TST_SOURCE_CODE_COMMIT_2', 'IndexID') IS NULL)
	CREATE NONCLUSTERED INDEX [AK_TST_SOURCE_CODE_COMMIT_2] ON [TST_SOURCE_CODE_COMMIT] ([UPDATE_DATE] desc)
ELSE
	PRINT N'Skipping Idx Drop on "AK_TST_SOURCE_CODE_COMMIT_2".';
GO
