-- =====================================================================
-- Author:			Inflectra Corporation
-- Description:		Adds any new user collections
-- =====================================================================

IF NOT EXISTS(SELECT NAME FROM TST_USER_COLLECTION WHERE USER_COLLECTION_ID = 40)
BEGIN
	SET IDENTITY_INSERT TST_USER_COLLECTION ON;
	INSERT INTO TST_USER_COLLECTION
	(
	USER_COLLECTION_ID, NAME, ACTIVE_YN
	)
	VALUES
	(
	40, 'ProjectGroupHome.General', 'Y'
	);
	SET IDENTITY_INSERT TST_USER_COLLECTION OFF;
END
GO

IF NOT EXISTS(SELECT NAME FROM TST_USER_COLLECTION WHERE USER_COLLECTION_ID = 41)
BEGIN
	SET IDENTITY_INSERT TST_USER_COLLECTION ON;
	INSERT INTO TST_USER_COLLECTION
	(
	USER_COLLECTION_ID, NAME, ACTIVE_YN
	)
	VALUES
	(
	41, 'Administration.PortfolioList.Filters', 'Y'
	);
	SET IDENTITY_INSERT TST_USER_COLLECTION OFF;
END
GO

IF NOT EXISTS(SELECT NAME FROM TST_USER_COLLECTION WHERE USER_COLLECTION_ID = 42)
BEGIN
	SET IDENTITY_INSERT TST_USER_COLLECTION ON;
	INSERT INTO TST_USER_COLLECTION
	(
	USER_COLLECTION_ID, NAME, ACTIVE_YN
	)
	VALUES
	(
	42, 'Administration.PortfolioList.General', 'Y'
	);
	SET IDENTITY_INSERT TST_USER_COLLECTION OFF;
END
GO

IF NOT EXISTS(SELECT NAME FROM TST_USER_COLLECTION WHERE USER_COLLECTION_ID = 43)
BEGIN
	SET IDENTITY_INSERT TST_USER_COLLECTION ON;
	INSERT INTO TST_USER_COLLECTION
	(
	USER_COLLECTION_ID, NAME, ACTIVE_YN
	)
	VALUES
	(
	43, 'MyPage.RecentWorkspaces', 'Y'
	);
	SET IDENTITY_INSERT TST_USER_COLLECTION OFF;
END
GO

IF NOT EXISTS(SELECT NAME FROM TST_USER_COLLECTION WHERE USER_COLLECTION_ID = 44)
BEGIN
	SET IDENTITY_INSERT TST_USER_COLLECTION ON;
	INSERT INTO TST_USER_COLLECTION
	(
	USER_COLLECTION_ID, NAME, ACTIVE_YN
	)
	VALUES
	(
	44, 'MyPage.RecentArtifacts', 'Y'
	);
	SET IDENTITY_INSERT TST_USER_COLLECTION OFF;
END
GO
