//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inflectra.SpiraTest.Web.Administration.ProjectTemplate {
    
    
    public partial class CustomListDetails {
        
        /// <summary>
        /// lblListName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblListName;
        
        /// <summary>
        /// lnkCustomList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.HyperLinkEx lnkCustomList;
        
        /// <summary>
        /// lblMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.MessageBox lblMessage;
        
        /// <summary>
        /// LabelEx1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx LabelEx1;
        
        /// <summary>
        /// listName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.TextBoxEx listName;
        
        /// <summary>
        /// LabelEx3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx LabelEx3;
        
        /// <summary>
        /// listSort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropDownListEx listSort;
        
        /// <summary>
        /// Localize1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize1;
        
        /// <summary>
        /// ddlFilterType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropDownListEx ddlFilterType;
        
        /// <summary>
        /// grdCustomListValues control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.GridViewEx grdCustomListValues;
        
        /// <summary>
        /// gridCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.TextBoxEx gridCount;
        
        /// <summary>
        /// btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.ButtonEx btnSave;
        
        /// <summary>
        /// btnCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.ButtonEx btnCancel;
    }
}
