//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inflectra.SpiraTest.Web.Administration.ProjectTemplate {
    
    
    public partial class Default {
        
        /// <summary>
        /// themeStylePlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.ThemeStylePlaceHolder themeStylePlaceHolder;
        
        /// <summary>
        /// ajaxWebParts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.UpdatePanelEx ajaxWebParts;
        
        /// <summary>
        /// prtManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.WebPartManagerEx prtManager;
        
        /// <summary>
        /// lblProjectTemplateName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProjectTemplateName;
        
        /// <summary>
        /// lblMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.MessageBox lblMessage;
        
        /// <summary>
        /// ValidationSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary;
        
        /// <summary>
        /// btnBrowseView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LinkButtonEx btnBrowseView;
        
        /// <summary>
        /// btnDesignView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LinkButtonEx btnDesignView;
        
        /// <summary>
        /// btnCustomize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LinkButtonEx btnCustomize;
        
        /// <summary>
        /// MessageBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.MessageBox MessageBox1;
        
        /// <summary>
        /// prtCatalogZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.WebParts.CatalogZone prtCatalogZone;
        
        /// <summary>
        /// prtPageCatalog control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.WebParts.PageCatalogPart prtPageCatalog;
        
        /// <summary>
        /// prtDeclarativeCatalog control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.WebParts.DeclarativeCatalogPart prtDeclarativeCatalog;
        
        /// <summary>
        /// prtEditorZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.WebParts.EditorZone prtEditorZone;
        
        /// <summary>
        /// prtPropertyGridEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.WebParts.PropertyGridEditorPart prtPropertyGridEditor;
        
        /// <summary>
        /// prtLeftZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.WebPartZoneEx prtLeftZone;
        
        /// <summary>
        /// ucProjectTemplateOverview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.UserControls.WebParts.ProjectTemplateAdmin.ProjectTemplateOverview ucProjectTemplateOverview;
        
        /// <summary>
        /// ucProjectList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.UserControls.WebParts.ProjectTemplateAdmin.ProjectList ucProjectList;
        
        /// <summary>
        /// prtRightZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.WebPartZoneEx prtRightZone;
        
        /// <summary>
        /// ProjectTemplateLinks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.UserControls.WebParts.ProjectTemplateAdmin.ProjectTemplateLinks ProjectTemplateLinks;
    }
}
