//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Inflectra.SpiraTest.DataModel
{
    
    public partial class DataSyncUserMappingView : INotifyComplexPropertyChanging, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int DataSyncSystemId
        {
            get { return _dataSyncSystemId; }
            set
            {
                if (_dataSyncSystemId != value)
                {
                    OnComplexPropertyChanging();
                    _dataSyncSystemId = value;
                    OnPropertyChanged("DataSyncSystemId");
                }
            }
        }
        private int _dataSyncSystemId;
    
        [DataMember]
        public Nullable<int> UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    OnComplexPropertyChanging();
                    _userId = value;
                    OnPropertyChanged("UserId");
                }
            }
        }
        private Nullable<int> _userId;
    
        [DataMember]
        public string ExternalKey
        {
            get { return _externalKey; }
            set
            {
                if (_externalKey != value)
                {
                    OnComplexPropertyChanging();
                    _externalKey = value;
                    OnPropertyChanged("ExternalKey");
                }
            }
        }
        private string _externalKey;
    
        [DataMember]
        public string DataSyncSystemName
        {
            get { return _dataSyncSystemName; }
            set
            {
                if (_dataSyncSystemName != value)
                {
                    OnComplexPropertyChanging();
                    _dataSyncSystemName = value;
                    OnPropertyChanged("DataSyncSystemName");
                }
            }
        }
        private string _dataSyncSystemName;
    
        [DataMember]
        public string DataSyncSystemDisplayName
        {
            get { return _dataSyncSystemDisplayName; }
            set
            {
                if (_dataSyncSystemDisplayName != value)
                {
                    OnComplexPropertyChanging();
                    _dataSyncSystemDisplayName = value;
                    OnPropertyChanged("DataSyncSystemDisplayName");
                }
            }
        }
        private string _dataSyncSystemDisplayName;

        #endregion

        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        public static void RecordComplexOriginalValues(String parentPropertyName, DataSyncUserMappingView complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("String parameter cannot be null or empty.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.DataSyncSystemId", parentPropertyName), complexObject == null ? null : (object)complexObject.DataSyncSystemId);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.UserId", parentPropertyName), complexObject == null ? null : (object)complexObject.UserId);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ExternalKey", parentPropertyName), complexObject == null ? null : (object)complexObject.ExternalKey);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.DataSyncSystemName", parentPropertyName), complexObject == null ? null : (object)complexObject.DataSyncSystemName);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.DataSyncSystemDisplayName", parentPropertyName), complexObject == null ? null : (object)complexObject.DataSyncSystemDisplayName);
        }

        #endregion

    }
}
