//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Inflectra.SpiraTest.DataModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(HistoryChangeSet))]
    public partial class HistoryTag: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int HistoryTagsId
        {
            get { return _historyTagsId; }
            set
            {
                if (_historyTagsId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'HistoryTagsId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _historyTagsId = value;
                    OnPropertyChanged("HistoryTagsId");
                }
            }
        }
        private int _historyTagsId;
    
        [DataMember]
        public long ChangeSetId
        {
            get { return _changeSetId; }
            set
            {
                if (_changeSetId != value)
                {
                    ChangeTracker.RecordOriginalValue("ChangeSetId", _changeSetId);
                    if (!IsDeserializing)
                    {
                        if (ChangeSet != null && ChangeSet.ChangeSetId != value)
                        {
                            ChangeSet = null;
                        }
                    }
                    _changeSetId = value;
                    OnPropertyChanged("ChangeSetId");
                }
            }
        }
        private long _changeSetId;
    
        [DataMember]
        public string OldTags
        {
            get { return _oldTags; }
            set
            {
                if (_oldTags != value)
                {
                    ChangeTracker.RecordOriginalValue("OldTags", _oldTags);
                    _oldTags = value;
                    OnPropertyChanged("OldTags");
                }
            }
        }
        private string _oldTags;
    
        [DataMember]
        public string NewTags
        {
            get { return _newTags; }
            set
            {
                if (_newTags != value)
                {
                    ChangeTracker.RecordOriginalValue("NewTags", _newTags);
                    _newTags = value;
                    OnPropertyChanged("NewTags");
                }
            }
        }
        private string _newTags;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public HistoryChangeSet ChangeSet
        {
            get { return _changeSet; }
            set
            {
                if (!ReferenceEquals(_changeSet, value))
                {
                    var previousValue = _changeSet;
                    _changeSet = value;
                    FixupChangeSet(previousValue);
                    OnNavigationPropertyChanged("ChangeSet");
                }
            }
        }
        private HistoryChangeSet _changeSet;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            ChangeSet = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupChangeSet(HistoryChangeSet previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TST_HISTORY_TAGS.Contains(this))
            {
                previousValue.TST_HISTORY_TAGS.Remove(this);
            }
    
            if (ChangeSet != null)
            {
                if (!ChangeSet.TST_HISTORY_TAGS.Contains(this))
                {
                    ChangeSet.TST_HISTORY_TAGS.Add(this);
                }
    
                ChangeSetId = ChangeSet.ChangeSetId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ChangeSet")
                    && (ChangeTracker.OriginalValues["ChangeSet"] == ChangeSet))
                {
                    ChangeTracker.OriginalValues.Remove("ChangeSet");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ChangeSet", previousValue);
                }
                if (ChangeSet != null && !ChangeSet.ChangeTracker.ChangeTrackingEnabled)
                {
                    ChangeSet.StartTracking();
                }
            }
        }

        #endregion

    }
}
