//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Inflectra.SpiraTest.DataModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ArtifactType))]
    [KnownType(typeof(MultiApprover))]
    public partial class MultiApproverType: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int MultiApproverTypeId
        {
            get { return _multiApproverTypeId; }
            set
            {
                if (_multiApproverTypeId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'MultiApproverTypeId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _multiApproverTypeId = value;
                    OnPropertyChanged("MultiApproverTypeId");
                }
            }
        }
        private int _multiApproverTypeId;
    
        [DataMember]
        public Nullable<int> ArtifactTypeId
        {
            get { return _artifactTypeId; }
            set
            {
                if (_artifactTypeId != value)
                {
                    ChangeTracker.RecordOriginalValue("ArtifactTypeId", _artifactTypeId);
                    if (!IsDeserializing)
                    {
                        if (ArtfiactType != null && ArtfiactType.ArtifactTypeId != value)
                        {
                            ArtfiactType = null;
                        }
                    }
                    _artifactTypeId = value;
                    OnPropertyChanged("ArtifactTypeId");
                }
            }
        }
        private Nullable<int> _artifactTypeId;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    ChangeTracker.RecordOriginalValue("Name", _name);
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public bool IsActive
        {
            get { return _isActive; }
            set
            {
                if (_isActive != value)
                {
                    ChangeTracker.RecordOriginalValue("IsActive", _isActive);
                    _isActive = value;
                    OnPropertyChanged("IsActive");
                }
            }
        }
        private bool _isActive;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public ArtifactType ArtfiactType
        {
            get { return _artfiactType; }
            set
            {
                if (!ReferenceEquals(_artfiactType, value))
                {
                    var previousValue = _artfiactType;
                    _artfiactType = value;
                    FixupArtfiactType(previousValue);
                    OnNavigationPropertyChanged("ArtfiactType");
                }
            }
        }
        private ArtifactType _artfiactType;
    
        [DataMember]
        public TrackableCollection<MultiApprover> Approvals
        {
            get
            {
                if (_approvals == null)
                {
                    _approvals = new TrackableCollection<MultiApprover>();
                    _approvals.CollectionChanged += FixupApprovals;
                }
                return _approvals;
            }
            set
            {
                if (!ReferenceEquals(_approvals, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_approvals != null)
                    {
                        _approvals.CollectionChanged -= FixupApprovals;
                    }
                    _approvals = value;
                    if (_approvals != null)
                    {
                        _approvals.CollectionChanged += FixupApprovals;
                    }
                    OnNavigationPropertyChanged("Approvals");
                }
            }
        }
        private TrackableCollection<MultiApprover> _approvals;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            ArtfiactType = null;
            Approvals.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupArtfiactType(ArtifactType previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.MultiApproverTypes.Contains(this))
            {
                previousValue.MultiApproverTypes.Remove(this);
            }
    
            if (ArtfiactType != null)
            {
                if (!ArtfiactType.MultiApproverTypes.Contains(this))
                {
                    ArtfiactType.MultiApproverTypes.Add(this);
                }
    
                ArtifactTypeId = ArtfiactType.ArtifactTypeId;
            }
            else if (!skipKeys)
            {
                ArtifactTypeId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ArtfiactType")
                    && (ChangeTracker.OriginalValues["ArtfiactType"] == ArtfiactType))
                {
                    ChangeTracker.OriginalValues.Remove("ArtfiactType");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ArtfiactType", previousValue);
                }
                if (ArtfiactType != null && !ArtfiactType.ChangeTracker.ChangeTrackingEnabled)
                {
                    ArtfiactType.StartTracking();
                }
            }
        }
    
        private void FixupApprovals(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (MultiApprover item in e.NewItems)
                {
                    item.ApproverType = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Approvals", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MultiApprover item in e.OldItems)
                {
                    if (ReferenceEquals(item.ApproverType, this))
                    {
                        item.ApproverType = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Approvals", item);
                    }
                }
            }
        }

        #endregion

    }
}
