//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Inflectra.SpiraTest.DataModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ReleaseStatus))]
    [KnownType(typeof(ReleaseWorkflow))]
    [KnownType(typeof(ReleaseWorkflowTransitionRole))]
    public partial class ReleaseWorkflowTransition: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int WorkflowTransitionId
        {
            get { return _workflowTransitionId; }
            set
            {
                if (_workflowTransitionId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'WorkflowTransitionId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _workflowTransitionId = value;
                    OnPropertyChanged("WorkflowTransitionId");
                }
            }
        }
        private int _workflowTransitionId;
    
        [DataMember]
        public int ReleaseWorkflowId
        {
            get { return _releaseWorkflowId; }
            set
            {
                if (_releaseWorkflowId != value)
                {
                    ChangeTracker.RecordOriginalValue("ReleaseWorkflowId", _releaseWorkflowId);
                    if (!IsDeserializing)
                    {
                        if (Workflow != null && Workflow.ReleaseWorkflowId != value)
                        {
                            Workflow = null;
                        }
                    }
                    _releaseWorkflowId = value;
                    OnPropertyChanged("ReleaseWorkflowId");
                }
            }
        }
        private int _releaseWorkflowId;
    
        [DataMember]
        public int InputReleaseStatusId
        {
            get { return _inputReleaseStatusId; }
            set
            {
                if (_inputReleaseStatusId != value)
                {
                    ChangeTracker.RecordOriginalValue("InputReleaseStatusId", _inputReleaseStatusId);
                    if (!IsDeserializing)
                    {
                        if (InputReleaseStatus != null && InputReleaseStatus.ReleaseStatusId != value)
                        {
                            InputReleaseStatus = null;
                        }
                    }
                    _inputReleaseStatusId = value;
                    OnPropertyChanged("InputReleaseStatusId");
                }
            }
        }
        private int _inputReleaseStatusId;
    
        [DataMember]
        public int OutputReleaseStatusId
        {
            get { return _outputReleaseStatusId; }
            set
            {
                if (_outputReleaseStatusId != value)
                {
                    ChangeTracker.RecordOriginalValue("OutputReleaseStatusId", _outputReleaseStatusId);
                    if (!IsDeserializing)
                    {
                        if (OutputReleaseStatus != null && OutputReleaseStatus.ReleaseStatusId != value)
                        {
                            OutputReleaseStatus = null;
                        }
                    }
                    _outputReleaseStatusId = value;
                    OnPropertyChanged("OutputReleaseStatusId");
                }
            }
        }
        private int _outputReleaseStatusId;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    ChangeTracker.RecordOriginalValue("Name", _name);
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public bool IsExecuteByCreator
        {
            get { return _isExecuteByCreator; }
            set
            {
                if (_isExecuteByCreator != value)
                {
                    ChangeTracker.RecordOriginalValue("IsExecuteByCreator", _isExecuteByCreator);
                    _isExecuteByCreator = value;
                    OnPropertyChanged("IsExecuteByCreator");
                }
            }
        }
        private bool _isExecuteByCreator;
    
        [DataMember]
        public bool IsExecuteByOwner
        {
            get { return _isExecuteByOwner; }
            set
            {
                if (_isExecuteByOwner != value)
                {
                    ChangeTracker.RecordOriginalValue("IsExecuteByOwner", _isExecuteByOwner);
                    _isExecuteByOwner = value;
                    OnPropertyChanged("IsExecuteByOwner");
                }
            }
        }
        private bool _isExecuteByOwner;
    
        [DataMember]
        public bool IsSignatureRequired
        {
            get { return _isSignatureRequired; }
            set
            {
                if (_isSignatureRequired != value)
                {
                    ChangeTracker.RecordOriginalValue("IsSignatureRequired", _isSignatureRequired);
                    _isSignatureRequired = value;
                    OnPropertyChanged("IsSignatureRequired");
                }
            }
        }
        private bool _isSignatureRequired;
    
        [DataMember]
        public bool IsBlankOwner
        {
            get { return _isBlankOwner; }
            set
            {
                if (_isBlankOwner != value)
                {
                    ChangeTracker.RecordOriginalValue("IsBlankOwner", _isBlankOwner);
                    _isBlankOwner = value;
                    OnPropertyChanged("IsBlankOwner");
                }
            }
        }
        private bool _isBlankOwner;
    
        [DataMember]
        public bool IsNotifyCreator
        {
            get { return _isNotifyCreator; }
            set
            {
                if (_isNotifyCreator != value)
                {
                    ChangeTracker.RecordOriginalValue("IsNotifyCreator", _isNotifyCreator);
                    _isNotifyCreator = value;
                    OnPropertyChanged("IsNotifyCreator");
                }
            }
        }
        private bool _isNotifyCreator;
    
        [DataMember]
        public bool IsNotifyOwner
        {
            get { return _isNotifyOwner; }
            set
            {
                if (_isNotifyOwner != value)
                {
                    ChangeTracker.RecordOriginalValue("IsNotifyOwner", _isNotifyOwner);
                    _isNotifyOwner = value;
                    OnPropertyChanged("IsNotifyOwner");
                }
            }
        }
        private bool _isNotifyOwner;
    
        [DataMember]
        public string NotifySubject
        {
            get { return _notifySubject; }
            set
            {
                if (_notifySubject != value)
                {
                    ChangeTracker.RecordOriginalValue("NotifySubject", _notifySubject);
                    _notifySubject = value;
                    OnPropertyChanged("NotifySubject");
                }
            }
        }
        private string _notifySubject;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public ReleaseStatus InputReleaseStatus
        {
            get { return _inputReleaseStatus; }
            set
            {
                if (!ReferenceEquals(_inputReleaseStatus, value))
                {
                    var previousValue = _inputReleaseStatus;
                    _inputReleaseStatus = value;
                    FixupInputReleaseStatus(previousValue);
                    OnNavigationPropertyChanged("InputReleaseStatus");
                }
            }
        }
        private ReleaseStatus _inputReleaseStatus;
    
        [DataMember]
        public ReleaseStatus OutputReleaseStatus
        {
            get { return _outputReleaseStatus; }
            set
            {
                if (!ReferenceEquals(_outputReleaseStatus, value))
                {
                    var previousValue = _outputReleaseStatus;
                    _outputReleaseStatus = value;
                    FixupOutputReleaseStatus(previousValue);
                    OnNavigationPropertyChanged("OutputReleaseStatus");
                }
            }
        }
        private ReleaseStatus _outputReleaseStatus;
    
        [DataMember]
        public ReleaseWorkflow Workflow
        {
            get { return _workflow; }
            set
            {
                if (!ReferenceEquals(_workflow, value))
                {
                    var previousValue = _workflow;
                    _workflow = value;
                    FixupWorkflow(previousValue);
                    OnNavigationPropertyChanged("Workflow");
                }
            }
        }
        private ReleaseWorkflow _workflow;
    
        [DataMember]
        public TrackableCollection<ReleaseWorkflowTransitionRole> TransitionRoles
        {
            get
            {
                if (_transitionRoles == null)
                {
                    _transitionRoles = new TrackableCollection<ReleaseWorkflowTransitionRole>();
                    _transitionRoles.CollectionChanged += FixupTransitionRoles;
                }
                return _transitionRoles;
            }
            set
            {
                if (!ReferenceEquals(_transitionRoles, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_transitionRoles != null)
                    {
                        _transitionRoles.CollectionChanged -= FixupTransitionRoles;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (ReleaseWorkflowTransitionRole item in _transitionRoles)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _transitionRoles = value;
                    if (_transitionRoles != null)
                    {
                        _transitionRoles.CollectionChanged += FixupTransitionRoles;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (ReleaseWorkflowTransitionRole item in _transitionRoles)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("TransitionRoles");
                }
            }
        }
        private TrackableCollection<ReleaseWorkflowTransitionRole> _transitionRoles;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            InputReleaseStatus = null;
            OutputReleaseStatus = null;
            Workflow = null;
            TransitionRoles.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupInputReleaseStatus(ReleaseStatus previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.WorkflowTransitionsInput.Contains(this))
            {
                previousValue.WorkflowTransitionsInput.Remove(this);
            }
    
            if (InputReleaseStatus != null)
            {
                if (!InputReleaseStatus.WorkflowTransitionsInput.Contains(this))
                {
                    InputReleaseStatus.WorkflowTransitionsInput.Add(this);
                }
    
                InputReleaseStatusId = InputReleaseStatus.ReleaseStatusId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("InputReleaseStatus")
                    && (ChangeTracker.OriginalValues["InputReleaseStatus"] == InputReleaseStatus))
                {
                    ChangeTracker.OriginalValues.Remove("InputReleaseStatus");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("InputReleaseStatus", previousValue);
                }
                if (InputReleaseStatus != null && !InputReleaseStatus.ChangeTracker.ChangeTrackingEnabled)
                {
                    InputReleaseStatus.StartTracking();
                }
            }
        }
    
        private void FixupOutputReleaseStatus(ReleaseStatus previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.WorkflowTransitionsOutput.Contains(this))
            {
                previousValue.WorkflowTransitionsOutput.Remove(this);
            }
    
            if (OutputReleaseStatus != null)
            {
                if (!OutputReleaseStatus.WorkflowTransitionsOutput.Contains(this))
                {
                    OutputReleaseStatus.WorkflowTransitionsOutput.Add(this);
                }
    
                OutputReleaseStatusId = OutputReleaseStatus.ReleaseStatusId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("OutputReleaseStatus")
                    && (ChangeTracker.OriginalValues["OutputReleaseStatus"] == OutputReleaseStatus))
                {
                    ChangeTracker.OriginalValues.Remove("OutputReleaseStatus");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("OutputReleaseStatus", previousValue);
                }
                if (OutputReleaseStatus != null && !OutputReleaseStatus.ChangeTracker.ChangeTrackingEnabled)
                {
                    OutputReleaseStatus.StartTracking();
                }
            }
        }
    
        private void FixupWorkflow(ReleaseWorkflow previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Transitions.Contains(this))
            {
                previousValue.Transitions.Remove(this);
            }
    
            if (Workflow != null)
            {
                if (!Workflow.Transitions.Contains(this))
                {
                    Workflow.Transitions.Add(this);
                }
    
                ReleaseWorkflowId = Workflow.ReleaseWorkflowId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Workflow")
                    && (ChangeTracker.OriginalValues["Workflow"] == Workflow))
                {
                    ChangeTracker.OriginalValues.Remove("Workflow");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Workflow", previousValue);
                }
                if (Workflow != null && !Workflow.ChangeTracker.ChangeTrackingEnabled)
                {
                    Workflow.StartTracking();
                }
            }
        }
    
        private void FixupTransitionRoles(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ReleaseWorkflowTransitionRole item in e.NewItems)
                {
                    item.Transition = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TransitionRoles", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ReleaseWorkflowTransitionRole item in e.OldItems)
                {
                    if (ReferenceEquals(item.Transition, this))
                    {
                        item.Transition = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TransitionRoles", item);
                        // Delete the dependent end of this identifying association. If the current state is Added,
                        // allow the relationship to be changed without causing the dependent to be deleted.
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }

        #endregion

    }
}
