//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Inflectra.SpiraTest.DataModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RequirementStatus))]
    [KnownType(typeof(RequirementWorkflowTransitionRole))]
    [KnownType(typeof(RequirementWorkflow))]
    public partial class RequirementWorkflowTransition: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int WorkflowTransitionId
        {
            get { return _workflowTransitionId; }
            set
            {
                if (_workflowTransitionId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'WorkflowTransitionId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _workflowTransitionId = value;
                    OnPropertyChanged("WorkflowTransitionId");
                }
            }
        }
        private int _workflowTransitionId;
    
        [DataMember]
        public Nullable<int> RequirementWorkflowId
        {
            get { return _requirementWorkflowId; }
            set
            {
                if (_requirementWorkflowId != value)
                {
                    ChangeTracker.RecordOriginalValue("RequirementWorkflowId", _requirementWorkflowId);
                    if (!IsDeserializing)
                    {
                        if (Workflow != null && Workflow.RequirementWorkflowId != value)
                        {
                            Workflow = null;
                        }
                    }
                    _requirementWorkflowId = value;
                    OnPropertyChanged("RequirementWorkflowId");
                }
            }
        }
        private Nullable<int> _requirementWorkflowId;
    
        [DataMember]
        public int InputRequirementStatusId
        {
            get { return _inputRequirementStatusId; }
            set
            {
                if (_inputRequirementStatusId != value)
                {
                    ChangeTracker.RecordOriginalValue("InputRequirementStatusId", _inputRequirementStatusId);
                    if (!IsDeserializing)
                    {
                        if (InputRequirementStatus != null && InputRequirementStatus.RequirementStatusId != value)
                        {
                            InputRequirementStatus = null;
                        }
                    }
                    _inputRequirementStatusId = value;
                    OnPropertyChanged("InputRequirementStatusId");
                }
            }
        }
        private int _inputRequirementStatusId;
    
        [DataMember]
        public int OutputRequirementStatusId
        {
            get { return _outputRequirementStatusId; }
            set
            {
                if (_outputRequirementStatusId != value)
                {
                    ChangeTracker.RecordOriginalValue("OutputRequirementStatusId", _outputRequirementStatusId);
                    if (!IsDeserializing)
                    {
                        if (OutputRequirementStatus != null && OutputRequirementStatus.RequirementStatusId != value)
                        {
                            OutputRequirementStatus = null;
                        }
                    }
                    _outputRequirementStatusId = value;
                    OnPropertyChanged("OutputRequirementStatusId");
                }
            }
        }
        private int _outputRequirementStatusId;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    ChangeTracker.RecordOriginalValue("Name", _name);
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public bool IsExecuteByCreator
        {
            get { return _isExecuteByCreator; }
            set
            {
                if (_isExecuteByCreator != value)
                {
                    ChangeTracker.RecordOriginalValue("IsExecuteByCreator", _isExecuteByCreator);
                    _isExecuteByCreator = value;
                    OnPropertyChanged("IsExecuteByCreator");
                }
            }
        }
        private bool _isExecuteByCreator;
    
        [DataMember]
        public bool IsExecuteByOwner
        {
            get { return _isExecuteByOwner; }
            set
            {
                if (_isExecuteByOwner != value)
                {
                    ChangeTracker.RecordOriginalValue("IsExecuteByOwner", _isExecuteByOwner);
                    _isExecuteByOwner = value;
                    OnPropertyChanged("IsExecuteByOwner");
                }
            }
        }
        private bool _isExecuteByOwner;
    
        [DataMember]
        public bool IsSignatureRequired
        {
            get { return _isSignatureRequired; }
            set
            {
                if (_isSignatureRequired != value)
                {
                    ChangeTracker.RecordOriginalValue("IsSignatureRequired", _isSignatureRequired);
                    _isSignatureRequired = value;
                    OnPropertyChanged("IsSignatureRequired");
                }
            }
        }
        private bool _isSignatureRequired;
    
        [DataMember]
        public bool IsBlankOwner
        {
            get { return _isBlankOwner; }
            set
            {
                if (_isBlankOwner != value)
                {
                    ChangeTracker.RecordOriginalValue("IsBlankOwner", _isBlankOwner);
                    _isBlankOwner = value;
                    OnPropertyChanged("IsBlankOwner");
                }
            }
        }
        private bool _isBlankOwner;
    
        [DataMember]
        public bool IsNotifyCreator
        {
            get { return _isNotifyCreator; }
            set
            {
                if (_isNotifyCreator != value)
                {
                    ChangeTracker.RecordOriginalValue("IsNotifyCreator", _isNotifyCreator);
                    _isNotifyCreator = value;
                    OnPropertyChanged("IsNotifyCreator");
                }
            }
        }
        private bool _isNotifyCreator;
    
        [DataMember]
        public bool IsNotifyOwner
        {
            get { return _isNotifyOwner; }
            set
            {
                if (_isNotifyOwner != value)
                {
                    ChangeTracker.RecordOriginalValue("IsNotifyOwner", _isNotifyOwner);
                    _isNotifyOwner = value;
                    OnPropertyChanged("IsNotifyOwner");
                }
            }
        }
        private bool _isNotifyOwner;
    
        [DataMember]
        public string NotifySubject
        {
            get { return _notifySubject; }
            set
            {
                if (_notifySubject != value)
                {
                    ChangeTracker.RecordOriginalValue("NotifySubject", _notifySubject);
                    _notifySubject = value;
                    OnPropertyChanged("NotifySubject");
                }
            }
        }
        private string _notifySubject;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public RequirementStatus InputRequirementStatus
        {
            get { return _inputRequirementStatus; }
            set
            {
                if (!ReferenceEquals(_inputRequirementStatus, value))
                {
                    var previousValue = _inputRequirementStatus;
                    _inputRequirementStatus = value;
                    FixupInputRequirementStatus(previousValue);
                    OnNavigationPropertyChanged("InputRequirementStatus");
                }
            }
        }
        private RequirementStatus _inputRequirementStatus;
    
        [DataMember]
        public RequirementStatus OutputRequirementStatus
        {
            get { return _outputRequirementStatus; }
            set
            {
                if (!ReferenceEquals(_outputRequirementStatus, value))
                {
                    var previousValue = _outputRequirementStatus;
                    _outputRequirementStatus = value;
                    FixupOutputRequirementStatus(previousValue);
                    OnNavigationPropertyChanged("OutputRequirementStatus");
                }
            }
        }
        private RequirementStatus _outputRequirementStatus;
    
        [DataMember]
        public TrackableCollection<RequirementWorkflowTransitionRole> TransitionRoles
        {
            get
            {
                if (_transitionRoles == null)
                {
                    _transitionRoles = new TrackableCollection<RequirementWorkflowTransitionRole>();
                    _transitionRoles.CollectionChanged += FixupTransitionRoles;
                }
                return _transitionRoles;
            }
            set
            {
                if (!ReferenceEquals(_transitionRoles, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_transitionRoles != null)
                    {
                        _transitionRoles.CollectionChanged -= FixupTransitionRoles;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (RequirementWorkflowTransitionRole item in _transitionRoles)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _transitionRoles = value;
                    if (_transitionRoles != null)
                    {
                        _transitionRoles.CollectionChanged += FixupTransitionRoles;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (RequirementWorkflowTransitionRole item in _transitionRoles)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("TransitionRoles");
                }
            }
        }
        private TrackableCollection<RequirementWorkflowTransitionRole> _transitionRoles;
    
        [DataMember]
        public RequirementWorkflow Workflow
        {
            get { return _workflow; }
            set
            {
                if (!ReferenceEquals(_workflow, value))
                {
                    var previousValue = _workflow;
                    _workflow = value;
                    FixupWorkflow(previousValue);
                    OnNavigationPropertyChanged("Workflow");
                }
            }
        }
        private RequirementWorkflow _workflow;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            InputRequirementStatus = null;
            OutputRequirementStatus = null;
            TransitionRoles.Clear();
            Workflow = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupInputRequirementStatus(RequirementStatus previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.WorkflowTransitionsInput.Contains(this))
            {
                previousValue.WorkflowTransitionsInput.Remove(this);
            }
    
            if (InputRequirementStatus != null)
            {
                if (!InputRequirementStatus.WorkflowTransitionsInput.Contains(this))
                {
                    InputRequirementStatus.WorkflowTransitionsInput.Add(this);
                }
    
                InputRequirementStatusId = InputRequirementStatus.RequirementStatusId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("InputRequirementStatus")
                    && (ChangeTracker.OriginalValues["InputRequirementStatus"] == InputRequirementStatus))
                {
                    ChangeTracker.OriginalValues.Remove("InputRequirementStatus");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("InputRequirementStatus", previousValue);
                }
                if (InputRequirementStatus != null && !InputRequirementStatus.ChangeTracker.ChangeTrackingEnabled)
                {
                    InputRequirementStatus.StartTracking();
                }
            }
        }
    
        private void FixupOutputRequirementStatus(RequirementStatus previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.WorkflowTransitionsOutput.Contains(this))
            {
                previousValue.WorkflowTransitionsOutput.Remove(this);
            }
    
            if (OutputRequirementStatus != null)
            {
                if (!OutputRequirementStatus.WorkflowTransitionsOutput.Contains(this))
                {
                    OutputRequirementStatus.WorkflowTransitionsOutput.Add(this);
                }
    
                OutputRequirementStatusId = OutputRequirementStatus.RequirementStatusId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("OutputRequirementStatus")
                    && (ChangeTracker.OriginalValues["OutputRequirementStatus"] == OutputRequirementStatus))
                {
                    ChangeTracker.OriginalValues.Remove("OutputRequirementStatus");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("OutputRequirementStatus", previousValue);
                }
                if (OutputRequirementStatus != null && !OutputRequirementStatus.ChangeTracker.ChangeTrackingEnabled)
                {
                    OutputRequirementStatus.StartTracking();
                }
            }
        }
    
        private void FixupWorkflow(RequirementWorkflow previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Transitions.Contains(this))
            {
                previousValue.Transitions.Remove(this);
            }
    
            if (Workflow != null)
            {
                if (!Workflow.Transitions.Contains(this))
                {
                    Workflow.Transitions.Add(this);
                }
    
                RequirementWorkflowId = Workflow.RequirementWorkflowId;
            }
            else if (!skipKeys)
            {
                RequirementWorkflowId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Workflow")
                    && (ChangeTracker.OriginalValues["Workflow"] == Workflow))
                {
                    ChangeTracker.OriginalValues.Remove("Workflow");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Workflow", previousValue);
                }
                if (Workflow != null && !Workflow.ChangeTracker.ChangeTrackingEnabled)
                {
                    Workflow.StartTracking();
                }
            }
        }
    
        private void FixupTransitionRoles(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (RequirementWorkflowTransitionRole item in e.NewItems)
                {
                    item.Transition = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TransitionRoles", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (RequirementWorkflowTransitionRole item in e.OldItems)
                {
                    if (ReferenceEquals(item.Transition, this))
                    {
                        item.Transition = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TransitionRoles", item);
                        // Delete the dependent end of this identifying association. If the current state is Added,
                        // allow the relationship to be changed without causing the dependent to be deleted.
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }

        #endregion

    }
}
