IF OBJECT_ID ( 'VW_ATTACHMENT_VERSION_LIST', 'V' ) IS NOT NULL 
    DROP VIEW VW_ATTACHMENT_VERSION_LIST;
GO

CREATE VIEW VW_ATTACHMENT_VERSION_LIST
AS
	SELECT	ATV.*, 
			(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS AUTHOR_NAME,
			ATC.ATTACHMENT_TYPE_ID
	FROM	TST_ATTACHMENT_VERSION ATV INNER JOIN TST_USER_PROFILE USR
	ON		ATV.AUTHOR_ID = USR.USER_ID INNER JOIN TST_ATTACHMENT ATC
	ON		ATV.ATTACHMENT_ID = ATC.ATTACHMENT_ID
GO
