IF OBJECT_ID ( 'VW_EXECUTION_STATUS_ACTIVE', 'V' ) IS NOT NULL 
    DROP VIEW [VW_EXECUTION_STATUS_ACTIVE];
GO
CREATE VIEW [VW_EXECUTION_STATUS_ACTIVE]
AS
SELECT EXECUTION_STATUS_ID, NAME
FROM TST_EXECUTION_STATUS
WHERE EXECUTION_STATUS_ID <> 4 AND IS_ACTIVE = 1
GO
