IF OBJECT_ID ('VW_HISTORY_CHANGESET_NET_CHANGES_SQUASHED', 'V') IS NOT NULL 
    DROP VIEW [VW_HISTORY_CHANGESET_NET_CHANGES_SQUASHED];
GO

CREATE VIEW [dbo].[VW_HISTORY_CHANGESET_NET_CHANGES_SQUASHED]
AS
	SELECT
		BASELINE_ID,
		MAX(BASELINE_NAME) AS BASELINE_NAME,
		ARTIFACT_TYPE_ID,
		ARTIFACT_ID,
		MAX(CHANGESET_ID) AS CHANGESET_ID,
		MAX(USER_ID) AS USER_ID,
		MAX(CHANGE_DATE) AS CHANGE_DATE,
		PROJECT_ID,
		MAX(ARTIFACT_NAME) AS ARTIFACT_NAME,
		MAX(USER_NAME) AS USER_NAME,
		MAX(ARTIFACT_TYPE_NAME) AS ARTIFACT_TYPE_NAME,
		STUFF(
			(SELECT ',' + CHANGETYPE_NAME 
			 FROM VW_HISTORY_CHANGESET_NET_CHANGES INNR
				 WHERE
					INNR.ARTIFACT_TYPE_ID = OUTR.ARTIFACT_TYPE_ID AND
					INNR.ARTIFACT_ID = OUTR.ARTIFACT_ID AND
					INNR.BASELINE_ID = OUTR.BASELINE_ID
			 FOR XML PATH('')
		), 1,1,'') AS CHANGE_TYPES
	FROM VW_HISTORY_CHANGESET_NET_CHANGES OUTR
	GROUP BY
		ARTIFACT_TYPE_ID,
		ARTIFACT_ID,
		BASELINE_ID,
		PROJECT_ID
GO
