IF OBJECT_ID ( 'VW_NOTIFICATION_USER_SUBSCRIPTION_LIST', 'V' ) IS NOT NULL 
    DROP VIEW [VW_NOTIFICATION_USER_SUBSCRIPTION_LIST];
GO
CREATE VIEW [VW_NOTIFICATION_USER_SUBSCRIPTION_LIST]
AS
SELECT	NUS.*, REQ.NAME AS ARTIFACT_NAME, REQ.DESCRIPTION AS ARTIFACT_DESCRIPTION, REQ.LAST_UPDATE_DATE, REQ.PROJECT_ID, PRJ.NAME AS PROJECT_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
FROM	TST_NOTIFICATION_USER_SUBSCRIPTION NUS INNER JOIN TST_REQUIREMENT REQ
ON		NUS.ARTIFACT_ID = REQ.REQUIREMENT_ID INNER JOIN TST_PROJECT PRJ
ON		REQ.PROJECT_ID = PRJ.PROJECT_ID INNER JOIN TST_ARTIFACT_TYPE ART
ON		NUS.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID
WHERE	PRJ.IS_ACTIVE = 1 AND NUS.ARTIFACT_TYPE_ID = 1
UNION
SELECT	NUS.*, TST.NAME AS ARTIFACT_NAME, TST.DESCRIPTION AS ARTIFACT_DESCRIPTION, TST.LAST_UPDATE_DATE, TST.PROJECT_ID, PRJ.NAME AS PROJECT_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
FROM	TST_NOTIFICATION_USER_SUBSCRIPTION NUS INNER JOIN TST_TEST_CASE TST
ON		NUS.ARTIFACT_ID = TST.TEST_CASE_ID INNER JOIN TST_PROJECT PRJ
ON		TST.PROJECT_ID = PRJ.PROJECT_ID INNER JOIN TST_ARTIFACT_TYPE ART
ON		NUS.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID
WHERE	PRJ.IS_ACTIVE = 1 AND NUS.ARTIFACT_TYPE_ID = 2
UNION
SELECT	NUS.*, TSE.NAME AS ARTIFACT_NAME, TSE.DESCRIPTION AS ARTIFACT_DESCRIPTION, TSE.LAST_UPDATE_DATE, TSE.PROJECT_ID, PRJ.NAME AS PROJECT_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
FROM	TST_NOTIFICATION_USER_SUBSCRIPTION NUS INNER JOIN TST_TEST_SET TSE
ON		NUS.ARTIFACT_ID = TSE.TEST_SET_ID INNER JOIN TST_PROJECT PRJ
ON		TSE.PROJECT_ID = PRJ.PROJECT_ID INNER JOIN TST_ARTIFACT_TYPE ART
ON		NUS.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID
WHERE	PRJ.IS_ACTIVE = 1 AND NUS.ARTIFACT_TYPE_ID = 8
UNION
SELECT	NUS.*, INC.NAME AS ARTIFACT_NAME, INC.DESCRIPTION AS ARTIFACT_DESCRIPTION, INC.LAST_UPDATE_DATE, INC.PROJECT_ID, PRJ.NAME AS PROJECT_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
FROM	TST_NOTIFICATION_USER_SUBSCRIPTION NUS INNER JOIN TST_INCIDENT INC
ON		NUS.ARTIFACT_ID = INC.INCIDENT_ID INNER JOIN TST_PROJECT PRJ
ON		INC.PROJECT_ID = PRJ.PROJECT_ID INNER JOIN TST_ARTIFACT_TYPE ART
ON		NUS.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID
WHERE	PRJ.IS_ACTIVE = 1 AND NUS.ARTIFACT_TYPE_ID = 3
UNION
SELECT	NUS.*, TSK.NAME AS ARTIFACT_NAME, TSK.DESCRIPTION AS ARTIFACT_DESCRIPTION, TSK.LAST_UPDATE_DATE, TSK.PROJECT_ID, PRJ.NAME AS PROJECT_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
FROM	TST_NOTIFICATION_USER_SUBSCRIPTION NUS INNER JOIN TST_TASK TSK
ON		NUS.ARTIFACT_ID = TSK.TASK_ID INNER JOIN TST_PROJECT PRJ
ON		TSK.PROJECT_ID = PRJ.PROJECT_ID INNER JOIN TST_ARTIFACT_TYPE ART
ON		NUS.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID
WHERE	PRJ.IS_ACTIVE = 1 AND NUS.ARTIFACT_TYPE_ID = 6
UNION
SELECT	NUS.*, DOC.FILENAME AS ARTIFACT_NAME, DOC.DESCRIPTION AS ARTIFACT_DESCRIPTION, DOC.EDITED_DATE AS LAST_UPDATE_DATE, DOC.PROJECT_ID, PRJ.NAME AS PROJECT_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
FROM	TST_NOTIFICATION_USER_SUBSCRIPTION NUS INNER JOIN VW_PROJECT_ATTACHMENT_LIST DOC
ON		NUS.ARTIFACT_ID = DOC.ATTACHMENT_ID INNER JOIN TST_PROJECT PRJ
ON		DOC.PROJECT_ID = PRJ.PROJECT_ID INNER JOIN TST_ARTIFACT_TYPE ART
ON		NUS.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID
WHERE	PRJ.IS_ACTIVE = 1 AND NUS.ARTIFACT_TYPE_ID = 13
GO
