IF OBJECT_ID ( 'VW_PROJECT_ATTACHMENT_FOLDER_HIERARCHY', 'V' ) IS NOT NULL 
    DROP VIEW [VW_PROJECT_ATTACHMENT_FOLDER_HIERARCHY];
GO
CREATE VIEW [VW_PROJECT_ATTACHMENT_FOLDER_HIERARCHY]
AS
SELECT PROJECT_ATTACHMENT_FOLDER_ID AS PROJECT_ATTACHMENT_FOLDER_ID, PROJECT_ID, NAME, PARENT_PROJECT_ATTACHMENT_FOLDER_ID, HIERARCHY_LEVEL, INDENT_LEVEL
FROM TST_PROJECT_ATTACHMENT_FOLDER_HIERARCHY
GO
