IF OBJECT_ID ( 'VW_REQUIREMENT_LIST', 'V' ) IS NOT NULL 
    DROP VIEW [VW_REQUIREMENT_LIST];
GO
CREATE VIEW [VW_REQUIREMENT_LIST]
AS
	SELECT
		CAST (0 AS BIT) AS IS_EXPANDED,
		CAST (0 AS BIT) AS IS_VISIBLE,
		REQ.*
	FROM VW_REQUIREMENT_LIST_INTERNAL REQ
GO
