IF OBJECT_ID ( 'VW_RELEASE_LIST', 'V' ) IS NOT NULL 
    DROP VIEW [VW_RELEASE_LIST];
GO
CREATE VIEW [VW_RELEASE_LIST]
AS
	SELECT
		CAST (1 AS BIT) AS IS_EXPANDED,
		CAST (1 AS BIT) AS IS_VISIBLE,
		REL.*
	FROM VW_RELEASE_LIST_INTERNAL REL
GO
