IF OBJECT_ID ( 'VW_TESTRUNSTEP_LIST', 'V' ) IS NOT NULL 
    DROP VIEW [VW_TESTRUNSTEP_LIST];
GO
CREATE VIEW [VW_TESTRUNSTEP_LIST]
AS
	SELECT
		TRS.*,
		EXE.NAME AS EXECUTION_STATUS_NAME,
		INC.INCIDENT_COUNT
	FROM
		TST_TEST_RUN_STEP TRS
			LEFT JOIN (
				SELECT COUNT(INCIDENT_ID) AS INCIDENT_COUNT, TEST_RUN_STEP_ID
				FROM TST_TEST_RUN_STEP_INCIDENT
                GROUP BY TEST_RUN_STEP_ID
			) AS INC
			ON INC.TEST_RUN_STEP_ID = TRS.TEST_RUN_STEP_ID
		INNER JOIN TST_EXECUTION_STATUS AS EXE
			ON TRS.EXECUTION_STATUS_ID = EXE.EXECUTION_STATUS_ID
GO
