IF OBJECT_ID ( 'VW_TESTSET_FOLDER_RELEASE', 'V' ) IS NOT NULL 
    DROP VIEW [VW_TESTSET_FOLDER_RELEASE];
GO
CREATE VIEW [VW_TESTSET_FOLDER_RELEASE]
AS
	SELECT
		ISNULL(TSE.TEST_SET_FOLDER_ID, 0) AS TEST_SET_FOLDER_ID,
		ISNULL(REL.RELEASE_ID, 0) AS DISPLAY_RELEASE_ID,
		TSE.PARENT_TEST_SET_FOLDER_ID, TSE.PROJECT_ID,
		TSE.NAME, TSE.DESCRIPTION, TSE.ESTIMATED_DURATION, TSE.LAST_UPDATE_DATE,
		RTX.EXECUTION_DATE, RTX.ACTUAL_DURATION,
		ISNULL(RTX.COUNT_PASSED, 0) AS COUNT_PASSED,
		ISNULL(RTX.COUNT_FAILED, 0) AS COUNT_FAILED,
		ISNULL(RTX.COUNT_CAUTION, 0) AS COUNT_CAUTION,
		ISNULL(RTX.COUNT_BLOCKED, 0) AS COUNT_BLOCKED,
		ISNULL(RTX.COUNT_NOT_RUN, ISNULL(TSE.COUNT_PASSED + TSE.COUNT_FAILED + TSE.COUNT_CAUTION + TSE.COUNT_BLOCKED + TSE.COUNT_NOT_RUN + TSE.COUNT_NOT_APPLICABLE,0)) AS COUNT_NOT_RUN,
		ISNULL(RTX.COUNT_NOT_APPLICABLE, 0) AS COUNT_NOT_APPLICABLE,
		ISNULL(TSE.CREATION_DATE, GETDATE()) AS CREATION_DATE
	FROM
		TST_TEST_SET_FOLDER TSE
		CROSS JOIN TST_RELEASE REL
		FULL OUTER JOIN TST_RELEASE_TEST_SET_FOLDER RTX
			ON TSE.TEST_SET_FOLDER_ID = RTX.TEST_SET_FOLDER_ID
			AND REL.RELEASE_ID = RTX.RELEASE_ID		
GO
