IF OBJECT_ID ( 'VW_TESTRUNS_PENDING_LIST', 'V' ) IS NOT NULL 
    DROP VIEW [VW_TESTRUNS_PENDING_LIST];
GO
CREATE VIEW [VW_TESTRUNS_PENDING_LIST]
AS
SELECT	TRP.TEST_RUNS_PENDING_ID, TRP.PROJECT_ID, TRP.TEST_SET_ID, TRP.TESTER_ID, TRP.NAME,
		TRP.CREATION_DATE, TRP.LAST_UPDATE_DATE, TRP.COUNT_PASSED, TRP.COUNT_FAILED, TRP.COUNT_BLOCKED,
		TRP.COUNT_CAUTION, TRP.COUNT_NOT_RUN, TRP.COUNT_NOT_APPLICABLE, TSE.NAME AS TEST_SET_NAME, PRJ.NAME AS PROJECT_NAME,
		CAST(1 AS BIT) AS IS_PRIMARY_OWNER
FROM	TST_TEST_RUNS_PENDING TRP INNER JOIN TST_PROJECT PRJ
ON		TRP.PROJECT_ID = PRJ.PROJECT_ID LEFT JOIN TST_TEST_SET TSE
ON		TRP.TEST_SET_ID = TSE.TEST_SET_ID
WHERE	PRJ.IS_ACTIVE = 1
UNION
SELECT	TRP.TEST_RUNS_PENDING_ID, TRP.PROJECT_ID, TRP.TEST_SET_ID, TRN.TESTER_ID, TRP.NAME,
		TRP.CREATION_DATE, TRP.LAST_UPDATE_DATE, TRP.COUNT_PASSED, TRP.COUNT_FAILED, TRP.COUNT_BLOCKED,
		TRP.COUNT_CAUTION, TRP.COUNT_NOT_RUN, TRP.COUNT_NOT_APPLICABLE, TSE.NAME AS TEST_SET_NAME, PRJ.NAME AS PROJECT_NAME,
		CAST(0 AS BIT) AS IS_PRIMARY_OWNER
FROM	TST_TEST_RUNS_PENDING TRP INNER JOIN TST_PROJECT PRJ
ON		TRP.PROJECT_ID = PRJ.PROJECT_ID LEFT JOIN TST_TEST_SET TSE
ON		TRP.TEST_SET_ID = TSE.TEST_SET_ID INNER JOIN TST_TEST_RUN TRN
ON		TRN.TEST_RUNS_PENDING_ID = TRP.TEST_RUNS_PENDING_ID
WHERE	PRJ.IS_ACTIVE = 1
AND		TRN.TESTER_ID <> TRP.TESTER_ID
GO
