IF OBJECT_ID ( 'VW_TESTSTEP_INCIDENTS', 'V' ) IS NOT NULL 
    DROP VIEW [VW_TESTSTEP_INCIDENTS];
GO
CREATE VIEW [VW_TESTSTEP_INCIDENTS]
AS
SELECT	TRS.TEST_STEP_ID, INC.INCIDENT_ID, INC.DETECTED_RELEASE_ID, INC.RESOLVED_RELEASE_ID, INC.VERIFIED_RELEASE_ID, IST.IS_OPEN_STATUS
FROM	TST_TEST_RUN_STEP TRS INNER JOIN TST_TEST_RUN_STEP_INCIDENT TRI
ON		TRS.TEST_RUN_STEP_ID = TRI.TEST_RUN_STEP_ID INNER JOIN TST_INCIDENT INC
ON		TRI.INCIDENT_ID = INC.INCIDENT_ID INNER JOIN TST_INCIDENT_STATUS IST
ON		INC.INCIDENT_STATUS_ID = IST.INCIDENT_STATUS_ID
WHERE	TRS.TEST_STEP_ID IS NOT NULL
UNION
SELECT	ARL.SOURCE_ARTIFACT_ID AS TEST_STEP_ID, INC.INCIDENT_ID, INC.DETECTED_RELEASE_ID, INC.RESOLVED_RELEASE_ID, INC.VERIFIED_RELEASE_ID, IST.IS_OPEN_STATUS
FROM	TST_ARTIFACT_LINK ARL INNER JOIN TST_INCIDENT INC
ON		ARL.DEST_ARTIFACT_ID = INC.INCIDENT_ID INNER JOIN TST_INCIDENT_STATUS IST
ON		INC.INCIDENT_STATUS_ID = IST.INCIDENT_STATUS_ID
WHERE	ARL.SOURCE_ARTIFACT_TYPE_ID = 7 AND ARL.DEST_ARTIFACT_TYPE_ID = 3
UNION
SELECT	ARL.DEST_ARTIFACT_ID AS TEST_STEP_ID, INC.INCIDENT_ID, INC.DETECTED_RELEASE_ID, INC.RESOLVED_RELEASE_ID, INC.VERIFIED_RELEASE_ID, IST.IS_OPEN_STATUS
FROM	TST_ARTIFACT_LINK ARL INNER JOIN TST_INCIDENT INC
ON		ARL.SOURCE_ARTIFACT_ID = INC.INCIDENT_ID INNER JOIN TST_INCIDENT_STATUS IST
ON		INC.INCIDENT_STATUS_ID = IST.INCIDENT_STATUS_ID
WHERE	ARL.SOURCE_ARTIFACT_TYPE_ID = 3 AND ARL.DEST_ARTIFACT_TYPE_ID = 7
GO
