IF OBJECT_ID ( 'VW_TEST_SET_FOLDER_HIERARCHY', 'V' ) IS NOT NULL 
    DROP VIEW [VW_TEST_SET_FOLDER_HIERARCHY];
GO
CREATE VIEW [VW_TEST_SET_FOLDER_HIERARCHY]
AS
SELECT TEST_SET_FOLDER_ID AS TEST_SET_FOLDER_ID, PROJECT_ID, NAME, PARENT_TEST_SET_FOLDER_ID, HIERARCHY_LEVEL, INDENT_LEVEL
FROM TST_TEST_SET_FOLDER_HIERARCHY
GO
