IF OBJECT_ID ( 'VW_TESTRUNSTEP_INCIDENTS', 'V' ) IS NOT NULL 
    DROP VIEW [VW_TESTRUNSTEP_INCIDENTS];
GO
CREATE VIEW [VW_TESTRUNSTEP_INCIDENTS]
AS
SELECT	TRS.TEST_RUN_STEP_ID, INC.INCIDENT_ID, INC.DETECTED_RELEASE_ID, INC.RESOLVED_RELEASE_ID, INC.VERIFIED_RELEASE_ID, IST.IS_OPEN_STATUS
FROM	TST_TEST_RUN_STEP TRS INNER JOIN TST_TEST_RUN_STEP_INCIDENT TRI
ON		TRS.TEST_RUN_STEP_ID = TRI.TEST_RUN_STEP_ID INNER JOIN TST_INCIDENT INC
ON		TRI.INCIDENT_ID = INC.INCIDENT_ID INNER JOIN TST_INCIDENT_STATUS IST
ON		INC.INCIDENT_STATUS_ID = IST.INCIDENT_STATUS_ID
GO
