IF OBJECT_ID ('VW_USERHISTORYCHANGE_LIST', 'V') IS NOT NULL 
    DROP VIEW [VW_USERHISTORYCHANGE_LIST];
GO

CREATE VIEW [dbo].[VW_USERHISTORYCHANGE_LIST]
AS
	SELECT 
		HC.*,
		HT.CHANGE_NAME AS CHANGETYPE_NAME,
		(RTRIM(US.FIRST_NAME + ' ' + ISNULL(US.MIDDLE_INITIAL,'')) + ' ' + US.LAST_NAME) AS USER_NAME
		
	FROM [ValidationMasterAudit].dbo.TST_USER_HISTORY_CHANGESET_AUDIT AS HC
		INNER JOIN [ValidationMasterAudit].dbo.TST_ADMIN_SECTION_AUDIT AS AD ON HC.ADMIN_SECTION_ID = AD.ADMIN_SECTION_ID
		INNER JOIN TST_HISTORY_CHANGESET_TYPE AS HT ON HC.HISTORY_CHANGESET_TYPE_ID = HT.CHANGETYPE_ID
		INNER JOIN TST_USER_PROFILE AS US ON HC.USER_ID = US.USER_ID
GO