select * from TST_TEST_CASE_WORKFLOW_CUSTOM_PROPERTY

select * from TST_ARTIFACT_FIELD
where ARTIFACT_TYPE_ID = 2
AND ARTIFACT_FIELD_ID in (24,207)
order by LIST_DEFAULT_POSITION

select * from TST_ARTIFACT_FIELD
where ARTIFACT_TYPE_ID = 4
order by LIST_DEFAULT_POSITION

SELECT * FROM TST_TEST_CASE


SELECT * FROM TST_CUSTOM_PROPERTY
SELECT * FROM TST_CUSTOM_PROPERTY_LIST
--SELECT * FROM TST_CUSTOM_PROPERTY_DEPENDENCY
SELECT * FROM TST_CUSTOM_PROPERTY_OPTION
SELECT * FROM TST_CUSTOM_PROPERTY_OPTION_VALUE
--SELECT * FROM TST_CUSTOM_PROPERTY_TYPE
SELECT * FROM TST_TEST_CASE_TYPE

