IF OBJECT_ID ( 'RPT_RISK_IMPACTS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_RISK_IMPACTS];
GO
CREATE VIEW [RPT_RISK_IMPACTS]
AS
    SELECT	PROP.*, TEMP.NAME AS PROJECT_TEMPLATE_NAME
	FROM TST_RISK_IMPACT AS PROP
	INNER JOIN TST_PROJECT_TEMPLATE AS TEMP ON PROP.PROJECT_TEMPLATE_ID = TEMP.PROJECT_TEMPLATE_ID
    WHERE PROP.IS_ACTIVE = 1
GO
