IF OBJECT_ID ( 'RPT_TEST_CONFIGURATION_SETS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_TEST_CONFIGURATION_SETS];
GO
CREATE VIEW [RPT_TEST_CONFIGURATION_SETS]
AS
	SELECT TCS.*,
	PRJ.NAME AS PROJECT_NAME, PRJ.PROJECT_GROUP_ID
    FROM TST_TEST_CONFIGURATION_SET AS TCS
	INNER JOIN TST_PROJECT AS PRJ ON TCS.PROJECT_ID = PRJ.PROJECT_ID
GO
