IF OBJECT_ID ( 'RPT_USERS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_USERS];
GO
CREATE VIEW [RPT_USERS]
AS
	SELECT	USR.USER_ID, USR.USER_NAME, USR.EMAIL_ADDRESS, USR.IS_ACTIVE, USR.CREATION_DATE,
			USR.LDAP_DN, UPL.FIRST_NAME, UPL.LAST_NAME, UPL.MIDDLE_INITIAL, UPL.DEPARTMENT,
			UPL.LAST_UPDATE_DATE, UPL.TIMEZONE, UPL.LAST_OPENED_PROJECT_ID, USR.IS_APPROVED,
			USR.LAST_LOGIN_DATE, USR.LAST_ACTIVITY_DATE
	FROM TST_USER AS USR
		INNER JOIN TST_USER_PROFILE AS UPL ON USR.USER_ID = UPL.USER_ID
GO
