IF OBJECT_ID ( 'RPT_PROJECTTEMPLATES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_PROJECTTEMPLATES];
GO
CREATE VIEW [RPT_PROJECTTEMPLATES]
AS
	SELECT	PRT.*
	FROM TST_PROJECT_TEMPLATE AS PRT
	WHERE PRT.IS_ACTIVE = 1
GO
