IF OBJECT_ID ( 'RPT_EVENTS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_EVENTS];
GO
CREATE VIEW [RPT_EVENTS]
AS
	SELECT EVT.*, TYP.NAME AS EVENT_TYPE_NAME
    FROM TST_EVENT AS EVT
    INNER JOIN TST_EVENT_TYPE TYP ON EVT.EVENT_TYPE_ID = TYP.EVENT_TYPE_ID
GO
