IF OBJECT_ID ( 'RPT_PROJECTS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_PROJECTS];
GO
CREATE VIEW [RPT_PROJECTS]
AS
	SELECT	PRJ.*, PRG.NAME AS PROJECT_GROUP_NAME, PRG.DESCRIPTION AS PROJECT_GROUP_DESCRIPTION
			
	FROM TST_PROJECT AS PRJ
		INNER JOIN TST_PROJECT_GROUP AS PRG ON PRJ.PROJECT_GROUP_ID = PRG.PROJECT_GROUP_ID
	WHERE PRJ.IS_ACTIVE = 1
GO
