IF OBJECT_ID ( 'RPT_REQUIREMENT_TESTCASES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_REQUIREMENT_TESTCASES];
GO
CREATE VIEW [RPT_REQUIREMENT_TESTCASES]
AS
	SELECT RTC.*, REQ.NAME AS REQUIREMENT_NAME, TST.NAME AS TEST_CASE_NAME,
		REQ.PROJECT_ID, PRJ.NAME AS PROJECT_NAME
	FROM TST_REQUIREMENT_TEST_CASE RTC
		INNER JOIN TST_REQUIREMENT REQ ON RTC.REQUIREMENT_ID = REQ.REQUIREMENT_ID
		INNER JOIN TST_TEST_CASE TST ON RTC.TEST_CASE_ID = TST.TEST_CASE_ID
		INNER JOIN TST_PROJECT AS PRJ ON REQ.PROJECT_ID = PRJ.PROJECT_ID
GO
