IF OBJECT_ID ( 'RPT_BASELINES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_BASELINES];
GO
CREATE VIEW [RPT_BASELINES]
AS
	SELECT
		B.*,
		U1.USER_NAME BASELINE_CREATOR_LOGIN,
		S.USER_ID CHANGESET_CREATOR_ID,
		U2.USER_NAME CHANGESET_CREATOR_LOGIN,
		S.ARTIFACT_TYPE_ID ARTIFACT_TYPE_ID,
		A.NAME ARTIFACT_TYPE_NAME,
		S.CHANGE_DATE CHANGESET_DATE,
		S.CHANGETYPE_ID CHANGESET_TYPE_ID,
		T.CHANGE_NAME CHANGESET_TYPE_NAME
	FROM
		TST_PROJECT_BASELINE B
		INNER JOIN TST_HISTORY_CHANGESET AS S ON B.CHANGESET_ID = S.CHANGESET_ID
		INNER JOIN TST_ARTIFACT_TYPE AS A ON A.ARTIFACT_TYPE_ID = S.ARTIFACT_TYPE_ID
		INNER JOIN TST_USER AS U1 ON U1.USER_ID = B.CREATOR_USER_ID
		INNER JOIN TST_USER AS U2 ON U2.USER_ID = S.USER_ID
		INNER JOIN TST_HISTORY_CHANGESET_TYPE AS T ON T.CHANGETYPE_ID = S.CHANGETYPE_ID
GO
