IF OBJECT_ID ( 'RPT_TESTSET_FOLDERS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_TESTSET_FOLDERS];
GO
CREATE VIEW [RPT_TESTSET_FOLDERS]
AS
	SELECT
		TSF.*,
		PRJ.NAME AS PROJECT_NAME, PRJ.PROJECT_GROUP_ID
	FROM
		TST_TEST_SET_FOLDER TSF
		INNER JOIN TST_PROJECT AS PRJ ON TSF.PROJECT_ID = PRJ.PROJECT_ID
GO
