IF OBJECT_ID ( 'RPT_INCIDENT_SEVERITIES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_INCIDENT_SEVERITIES];
GO
CREATE VIEW [RPT_INCIDENT_SEVERITIES]
AS
    SELECT	PROP.*, TEMP.NAME AS PROJECT_TEMPLATE_NAME
	FROM TST_INCIDENT_SEVERITY AS PROP
	INNER JOIN TST_PROJECT_TEMPLATE AS TEMP ON PROP.PROJECT_TEMPLATE_ID = TEMP.PROJECT_TEMPLATE_ID
    WHERE PROP.IS_ACTIVE = 1
GO
