IF OBJECT_ID ( 'RPT_INCIDENT_TYPES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_INCIDENT_TYPES];
GO
CREATE VIEW [RPT_INCIDENT_TYPES]
AS
    SELECT	PROP.INCIDENT_TYPE_ID, PROP.PROJECT_TEMPLATE_ID, PROP.WORKFLOW_ID, PROP.NAME, PROP.IS_ACTIVE, PROP.IS_ISSUE, PROP.IS_DEFAULT, TEMP.NAME AS PROJECT_TEMPLATE_NAME
	FROM TST_INCIDENT_TYPE AS PROP
	INNER JOIN TST_PROJECT_TEMPLATE AS TEMP ON PROP.PROJECT_TEMPLATE_ID = TEMP.PROJECT_TEMPLATE_ID
    WHERE PROP.IS_ACTIVE = 1
GO
