IF OBJECT_ID ( 'RPT_TESTRUN_INCIDENTS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_TESTRUN_INCIDENTS];
GO
CREATE VIEW [RPT_TESTRUN_INCIDENTS]
AS
SELECT	TRN.TEST_RUN_ID, INC.INCIDENT_ID, INC.DETECTED_RELEASE_ID, INC.RESOLVED_RELEASE_ID, INC.VERIFIED_RELEASE_ID, IST.IS_OPEN_STATUS
FROM	TST_TEST_RUN TRN INNER JOIN TST_TEST_RUN_STEP TRS
ON		TRN.TEST_RUN_ID = TRS.TEST_RUN_ID INNER JOIN TST_TEST_RUN_STEP_INCIDENT TRI
ON		TRS.TEST_RUN_STEP_ID = TRI.TEST_RUN_STEP_ID INNER JOIN TST_INCIDENT INC
ON		TRI.INCIDENT_ID = INC.INCIDENT_ID INNER JOIN TST_INCIDENT_STATUS IST
ON		INC.INCIDENT_STATUS_ID = IST.INCIDENT_STATUS_ID
GO
