IF OBJECT_ID ( 'RPT_DOCUMENT_TYPES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_DOCUMENT_TYPES];
GO
CREATE VIEW [RPT_DOCUMENT_TYPES]
AS
    SELECT	PROP.*, TEMP.NAME AS PROJECT_TEMPLATE_NAME
	FROM TST_DOCUMENT_TYPE AS PROP
	INNER JOIN TST_PROJECT_TEMPLATE AS TEMP ON PROP.PROJECT_TEMPLATE_ID = TEMP.PROJECT_TEMPLATE_ID
    WHERE PROP.IS_ACTIVE = 1
GO
