IF OBJECT_ID ( 'RPT_PROJECT_RESOURCES_RELEASE', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_PROJECT_RESOURCES_RELEASE];
GO
CREATE VIEW [RPT_PROJECT_RESOURCES_RELEASE]
AS
SELECT  PRJ.PROJECT_ID, INC.OWNER_ID AS USER_ID, REL.RELEASE_ID,
		SUM(INC.ESTIMATED_EFFORT) AS INCIDENT_EFFORT, 0 AS TASK_EFFORT
FROM	TST_PROJECT PRJ INNER JOIN TST_INCIDENT INC
ON		INC.PROJECT_ID = PRJ.PROJECT_ID INNER JOIN TST_RELEASE REL
ON		INC.RESOLVED_RELEASE_ID = REL.RELEASE_ID
WHERE	INC.OWNER_ID IS NOT NULL
AND		INC.IS_DELETED = 0
GROUP BY INC.OWNER_ID, PRJ.PROJECT_ID, REL.RELEASE_ID
UNION
SELECT  PRJ.PROJECT_ID, TSK.OWNER_ID AS USER_ID, REL.RELEASE_ID,
		0 AS INCIDENT_EFFORT, SUM(TSK.ESTIMATED_EFFORT) AS TASK_EFFORT
FROM	TST_PROJECT PRJ INNER JOIN TST_TASK TSK
ON		TSK.PROJECT_ID = PRJ.PROJECT_ID INNER JOIN TST_RELEASE REL
ON		TSK.RELEASE_ID = REL.RELEASE_ID
WHERE	TSK.OWNER_ID IS NOT NULL
AND		TSK.IS_DELETED = 0
GROUP BY TSK.OWNER_ID, PRJ.PROJECT_ID, REL.RELEASE_ID
GO
