IF OBJECT_ID ( 'RPT_TEST_CONFIGURATION_ENTRIES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_TEST_CONFIGURATION_ENTRIES];
GO
CREATE VIEW [RPT_TEST_CONFIGURATION_ENTRIES]
AS
	SELECT TCE.*,
	TCS.NAME AS TEST_CONFIGURATION_SET_NAME,
	TCS.IS_ACTIVE AS IS_TEST_CONFIGURATION_SET_ACTIVE,
	CPV.CUSTOM_PROPERTY_VALUE_ID,
	TCP.NAME AS TEST_CASE_PARAMETER_NAME,
	CPV.NAME AS TEST_CASE_PARAMETER_VALUE,
	PRJ.NAME AS PROJECT_NAME, PRJ.PROJECT_GROUP_ID
    FROM TST_TEST_CONFIGURATION AS TCE
    INNER JOIN TST_TEST_CONFIGURATION_SET TCS ON TCE.TEST_CONFIGURATION_SET_ID = TCS.TEST_CONFIGURATION_SET_ID
	INNER JOIN TST_TEST_CONFIGURATION_SET_PARAMETER AS TSP ON TSP.TEST_CONFIGURATION_SET_ID = TCS.TEST_CONFIGURATION_SET_ID
	INNER JOIN TST_TEST_CASE_PARAMETER AS TCP ON TCP.TEST_CASE_PARAMETER_ID = TSP.TEST_CASE_PARAMETER_ID
    INNER JOIN TST_TEST_CONFIGURATION_PARAMETER_VALUE AS TPV ON
		TCE.TEST_CONFIGURATION_ID = TPV.TEST_CONFIGURATION_ID AND
		TCE.TEST_CONFIGURATION_SET_ID = TCS.TEST_CONFIGURATION_SET_ID AND
		TPV.TEST_CASE_PARAMETER_ID = TSP.TEST_CASE_PARAMETER_ID
	INNER JOIN TST_CUSTOM_PROPERTY_VALUE CPV ON TPV.CUSTOM_PROPERTY_VALUE_ID = CPV.CUSTOM_PROPERTY_VALUE_ID
	INNER JOIN TST_PROJECT AS PRJ ON TCS.PROJECT_ID = PRJ.PROJECT_ID
GO
