IF OBJECT_ID ( 'RPT_COMPONENTS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_COMPONENTS];
GO
CREATE VIEW [RPT_COMPONENTS]
AS
	SELECT CMP.*,
	PRJ.NAME AS PROJECT_NAME, PRJ.PROJECT_GROUP_ID
    FROM TST_COMPONENT AS CMP
	INNER JOIN TST_PROJECT AS PRJ ON CMP.PROJECT_ID = PRJ.PROJECT_ID
GO
