IF OBJECT_ID ( 'RPT_TESTRUNSTEPS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_TESTRUNSTEPS];
GO
CREATE VIEW [RPT_TESTRUNSTEPS]
AS
	SELECT	
	TRS.*,
	EXE.NAME AS EXECUTION_STATUS_NAME,
	TST.NAME AS TEST_CASE_NAME, TST.PROJECT_ID, 
	PRJ.NAME AS PROJECT_NAME, PRJ.PROJECT_GROUP_ID

    FROM TST_TEST_RUN_STEP AS TRS
		INNER JOIN TST_EXECUTION_STATUS AS EXE ON TRS.EXECUTION_STATUS_ID = EXE.EXECUTION_STATUS_ID
		INNER JOIN TST_TEST_RUN TRN ON TRS.TEST_RUN_ID = TRN.TEST_RUN_ID
		INNER JOIN TST_TEST_CASE AS TST ON TRN.TEST_CASE_ID = TST.TEST_CASE_ID
		INNER JOIN TST_PROJECT AS PRJ ON TST.PROJECT_ID = PRJ.PROJECT_ID
	WHERE PRJ.IS_ACTIVE = 1 AND TST.IS_DELETED = 0
GO
