IF OBJECT_ID ( 'RPT_ATTACHMENT_FOLDERS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_ATTACHMENT_FOLDERS];
GO
CREATE VIEW [RPT_ATTACHMENT_FOLDERS]
AS
	SELECT
		FOL.*,
		PRJ.NAME AS PROJECT_NAME, PRJ.PROJECT_GROUP_ID
	FROM
		TST_PROJECT_ATTACHMENT_FOLDER FOL
		INNER JOIN TST_PROJECT AS PRJ ON FOL.PROJECT_ID = PRJ.PROJECT_ID
GO
