//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inflectra.SpiraTest.Web
{


    public partial class ReleaseDetails
    {

        /// <summary>
        /// navReleaseList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.NavigationBar navReleaseList;

        /// <summary>
        /// btnBack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.HyperLinkEx btnBack;

        /// <summary>
        /// btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropMenu btnSave;

        /// <summary>
        /// DropMenuItem1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropMenuItem DropMenuItem1;

        /// <summary>
        /// DropMenuItem2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropMenuItem DropMenuItem2;

        /// <summary>
        /// DropMenuItem3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropMenuItem DropMenuItem3;

        /// <summary>
        /// btnRefresh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropMenu btnRefresh;

        /// <summary>
        /// btnCreate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropMenu btnCreate;

        /// <summary>
        /// btnDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropMenu btnDelete;

        /// <summary>
        /// btnTools control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropMenu btnTools;

        /// <summary>
        /// btnEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropMenu btnEmail;

        /// <summary>
        /// btnSubscribe control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropMenu btnSubscribe;

        /// <summary>
        /// pnlFolderPath control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlFolderPath;

        /// <summary>
        /// txtName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.UnityTextBoxEx txtName;

        /// <summary>
        /// imgReleaseIteration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.ImageEx imgReleaseIteration;

        /// <summary>
        /// ltrReleaseIteration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrReleaseIteration;

        /// <summary>
        /// lblReleaseVersionNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblReleaseVersionNumber;

        /// <summary>
        /// lblReleaseToken control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblReleaseToken;

        /// <summary>
        /// ddlTypeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx ddlTypeLabel;

        /// <summary>
        /// ddlType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.UnityDropDownListEx ddlType;

        /// <summary>
        /// lblReleaseStatusLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblReleaseStatusLabel;

        /// <summary>
        /// lblReleaseStatusValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblReleaseStatusValue;

        /// <summary>
        /// btnRevert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.HyperLinkEx btnRevert;

        /// <summary>
        /// ajxWorkflowOperations control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.WorkflowOperations ajxWorkflowOperations;

        /// <summary>
        /// eqlCompletionLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx eqlCompletionLabel;

        /// <summary>
        /// eqlCompletion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.Equalizer eqlCompletion;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.MessageBox lblMessage;

        /// <summary>
        /// tstEmailPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.UserControls.ArtifactEmail tstEmailPanel;

        /// <summary>
        /// ArtifactAddFollower control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.UserControls.ArtifactAddFollower ArtifactAddFollower;

        /// <summary>
        /// tclReleaseDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.TabControl tclReleaseDetails;

        /// <summary>
        /// tabOverview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.TabPage tabOverview;

        /// <summary>
        /// tabIncidents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.TabPage tabIncidents;

        /// <summary>
        /// tabTasks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.TabPage tabTasks;

        /// <summary>
        /// tabTestCases control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.TabPage tabTestCases;

        /// <summary>
        /// tabTestRuns control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.TabPage tabTestRuns;

        /// <summary>
        /// tabAttachments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.TabPage tabAttachments;

        /// <summary>
        /// tabBaseline control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.TabPage tabBaseline;

        /// <summary>
        /// tabHistory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.TabPage tabHistory;

        /// <summary>
        /// pnlOverview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlOverview;

        /// <summary>
        /// customFieldsUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl customFieldsUsers;

        /// <summary>
        /// ddlCreatorLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx ddlCreatorLabel;

        /// <summary>
        /// ddlCreator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.UnityDropDownUserList ddlCreator;

        /// <summary>
        /// ddlOwnerLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx ddlOwnerLabel;

        /// <summary>
        /// ddlOwner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.UnityDropDownUserList ddlOwner;

        /// <summary>
        /// customFieldsEstimates control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl customFieldsEstimates;

        /// <summary>
        /// plcPlannedEffort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder plcPlannedEffort;

        /// <summary>
        /// lblPlannedEffortLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblPlannedEffortLabel;

        /// <summary>
        /// lblPlannedEffort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblPlannedEffort;

        /// <summary>
        /// lblUtilizedEffortLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblUtilizedEffortLabel;

        /// <summary>
        /// lblUtilizedEffort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblUtilizedEffort;

        /// <summary>
        /// lblAvailableEffortLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblAvailableEffortLabel;

        /// <summary>
        /// lblAvailableEffort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblAvailableEffort;

        /// <summary>
        /// plcPlannedPoints control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder plcPlannedPoints;

        /// <summary>
        /// txtPlannedPointsLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx txtPlannedPointsLabel;

        /// <summary>
        /// txtPlannedPoints control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.UnityTextBoxEx txtPlannedPoints;

        /// <summary>
        /// customFieldsDefault control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl customFieldsDefault;

        /// <summary>
        /// txtVersionNumberLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx txtVersionNumberLabel;

        /// <summary>
        /// txtVersionNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.UnityTextBoxEx txtVersionNumber;

        /// <summary>
        /// Ul1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Ul1;

        /// <summary>
        /// periodReviewDateLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx periodReviewDateLabel;

        /// <summary>
        /// datPeriodicReviewDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.UnityDateControl datPeriodicReviewDate;

        /// <summary>
        /// ddlPeriodicReviewAlertTypeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx ddlPeriodicReviewAlertTypeLabel;

        /// <summary>
        /// ddlPeriodicAlertTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.UnityDropDownListEx ddlPeriodicAlertTypes;

        /// <summary>
        /// customFieldsDates control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl customFieldsDates;

        /// <summary>
        /// lblCreationDateLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblCreationDateLabel;

        /// <summary>
        /// lblCreationDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCreationDate;

        /// <summary>
        /// lblLastUpdateDateLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblLastUpdateDateLabel;

        /// <summary>
        /// lblLastUpdateDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLastUpdateDate;

        /// <summary>
        /// datStartDateLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx datStartDateLabel;

        /// <summary>
        /// datStartDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.UnityDateControl datStartDate;

        /// <summary>
        /// datEndDateLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx datEndDateLabel;

        /// <summary>
        /// datEndDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.UnityDateControl datEndDate;

        /// <summary>
        /// txtResourceCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx txtResourceCountLabel;

        /// <summary>
        /// txtResourceCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.UnityTextBoxEx txtResourceCount;

        /// <summary>
        /// txtNonWorkDaysLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx txtNonWorkDaysLabel;

        /// <summary>
        /// txtNonWorkDays control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.UnityTextBoxEx txtNonWorkDays;

        /// <summary>
        /// customFieldsRichText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl customFieldsRichText;

        /// <summary>
        /// txtDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.RichTextBoxJ txtDescription;

        /// <summary>
        /// pnlOverview_Builds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlOverview_Builds;

        /// <summary>
        /// lnkBuildRefresh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.HyperLinkEx lnkBuildRefresh;

        /// <summary>
        /// lnkBuildApplyFilter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.HyperLinkEx lnkBuildApplyFilter;

        /// <summary>
        /// lnkBuildClearFilter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.HyperLinkEx lnkBuildClearFilter;

        /// <summary>
        /// Localize2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize2;

        /// <summary>
        /// lblVisibleCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblVisibleCount;

        /// <summary>
        /// Localize3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize3;

        /// <summary>
        /// lblTotalCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalCount;

        /// <summary>
        /// Localize4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize4;

        /// <summary>
        /// lblFilterInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblFilterInfo;

        /// <summary>
        /// grdBuildList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.SortedGrid grdBuildList;

        /// <summary>
        /// lstComments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.CommentList lstComments;

        /// <summary>
        /// txtNewComment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.RichTextBoxJ txtNewComment;

        /// <summary>
        /// btnNewComment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.ButtonEx btnNewComment;

        /// <summary>
        /// pnlIncidents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlIncidents;

        /// <summary>
        /// divIncidentsMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.MessageBox divIncidentsMessage;

        /// <summary>
        /// ddlIncidentReleaseFilterType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropDownListEx ddlIncidentReleaseFilterType;

        /// <summary>
        /// lnkRefresh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.HyperLinkEx lnkRefresh;

        /// <summary>
        /// btnFilters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropMenu btnFilters;

        /// <summary>
        /// ddlShowHideIncidentColumns control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropDownListEx ddlShowHideIncidentColumns;

        /// <summary>
        /// Localize5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize5;

        /// <summary>
        /// lblIncidentVisibleCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblIncidentVisibleCount;

        /// <summary>
        /// Localize6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize6;

        /// <summary>
        /// lblIncidentTotalCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblIncidentTotalCount;

        /// <summary>
        /// Localize7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize7;

        /// <summary>
        /// lblIncidentFilterInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.LabelEx lblIncidentFilterInfo;

        /// <summary>
        /// grdIncidentList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.SortedGrid grdIncidentList;

        /// <summary>
        /// pnlTestRuns control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTestRuns;

        /// <summary>
        /// tstTestRunListPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.UserControls.TestRunListPanel tstTestRunListPanel;

        /// <summary>
        /// pnlTasks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTasks;

        /// <summary>
        /// tstRequirementTaskPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.UserControls.RequirementTaskPanel tstRequirementTaskPanel;

        /// <summary>
        /// pnlTestCases control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTestCases;

        /// <summary>
        /// tstTestCaseMapping control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.UserControls.AssociationsPanel tstTestCaseMapping;

        /// <summary>
        /// pnlAttachments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlAttachments;

        /// <summary>
        /// tstAttachmentPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.UserControls.AttachmentPanel tstAttachmentPanel;

        /// <summary>
        /// pnlHistory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlHistory;

        /// <summary>
        /// tstHistoryPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.UserControls.HistoryPanel tstHistoryPanel;

        /// <summary>
        /// pnlBaseline control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlBaseline;

        /// <summary>
        /// tstBaselinePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.UserControls.BaselinePanel tstBaselinePanel;

        /// <summary>
        /// ajxFormManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.AjaxFormManager ajxFormManager;

        /// <summary>
        /// ajxScriptManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.ScriptManagerProxyEx ajxScriptManager;
    }
}
