//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inflectra.SpiraTest.Web.UserControls {
    
    
    public partial class ArtifactAddFollower {
        
        /// <summary>
        /// pnlAddFollower control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DialogBoxPanel pnlAddFollower;
        
        /// <summary>
        /// msgAddFollower control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.MessageBox msgAddFollower;
        
        /// <summary>
        /// ddlAddProjUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.DropDownListEx ddlAddProjUser;
        
        /// <summary>
        /// lnkAddFollower control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.HyperLinkEx lnkAddFollower;
        
        /// <summary>
        /// lnkCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.HyperLinkEx lnkCancel;
        
        /// <summary>
        /// ajxScriptManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Inflectra.SpiraTest.Web.ServerControls.ScriptManagerProxyEx ajxScriptManager;
    }
}
