IF OBJECT_ID ( 'RPT_ARTIFACT_ASSOCIATION', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_ARTIFACT_ASSOCIATION];
GO
CREATE VIEW [RPT_ARTIFACT_ASSOCIATION]
AS
    SELECT	ARL.*,
			ART1.NAME AS SOURCE_ARTIFACT_TYPE_NAME,
			ART2.NAME AS DEST_ARTIFACT_TYPE_NAME,
    		(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME,
    		ALT.NAME AS ARTIFACT_LINK_TYPE_NAME
    FROM	TST_ARTIFACT_LINK ARL
    INNER JOIN TST_ARTIFACT_TYPE ART1 ON ARL.SOURCE_ARTIFACT_TYPE_ID = ART1.ARTIFACT_TYPE_ID
    INNER JOIN TST_ARTIFACT_TYPE ART2 ON ARL.DEST_ARTIFACT_TYPE_ID = ART2.ARTIFACT_TYPE_ID    
    LEFT JOIN TST_USER_PROFILE USR ON ARL.CREATOR_ID = USR.USER_ID
    INNER JOIN TST_ARTIFACT_LINK_TYPE ALT ON ARL.ARTIFACT_LINK_TYPE_ID = ALT.ARTIFACT_LINK_TYPE_ID
GO
