IF OBJECT_ID ( 'RPT_ARTIFACT_ATTACHMENT', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_ARTIFACT_ATTACHMENT];
GO
CREATE VIEW [RPT_ARTIFACT_ATTACHMENT]
AS
SELECT	(AAT.ARTIFACT_ID * 10 + AAT.ARTIFACT_TYPE_ID) AS ARTIFACT_LINK_ID, AAT.ARTIFACT_TYPE_ID, AAT.ARTIFACT_ID, ART.NAME AS ARTIFACT_TYPE_NAME, OBJ.NAME AS ARTIFACT_NAME, '' AS COMMENT, OBJ.AUTHOR_ID AS CREATOR_ID, OBJ.CREATION_DATE, (RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME,
		AAT.ATTACHMENT_ID, AAT.PROJECT_ID, STA.NAME AS ARTIFACT_STATUS_NAME
FROM	TST_ARTIFACT_ATTACHMENT AAT INNER JOIN TST_ARTIFACT_TYPE ART
ON		AAT.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID INNER JOIN TST_REQUIREMENT OBJ
ON		AAT.ARTIFACT_ID = OBJ.REQUIREMENT_ID INNER JOIN TST_USER_PROFILE USR
ON		OBJ.AUTHOR_ID = USR.USER_ID INNER JOIN TST_REQUIREMENT_STATUS STA
ON		OBJ.REQUIREMENT_STATUS_ID = STA.REQUIREMENT_STATUS_ID
WHERE	AAT.ARTIFACT_TYPE_ID = 1
UNION
SELECT	(AAT.ARTIFACT_ID * 10 + AAT.ARTIFACT_TYPE_ID) AS ARTIFACT_LINK_ID, AAT.ARTIFACT_TYPE_ID, AAT.ARTIFACT_ID, ART.NAME AS ARTIFACT_TYPE_NAME, OBJ.NAME AS ARTIFACT_NAME, '' AS COMMENT, OBJ.AUTHOR_ID AS CREATOR_ID, OBJ.CREATION_DATE, (RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME,
		AAT.ATTACHMENT_ID, AAT.PROJECT_ID, STA.NAME AS ARTIFACT_STATUS_NAME
FROM	TST_ARTIFACT_ATTACHMENT AAT INNER JOIN TST_ARTIFACT_TYPE ART
ON		AAT.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID INNER JOIN TST_TEST_CASE OBJ
ON		AAT.ARTIFACT_ID = OBJ.TEST_CASE_ID INNER JOIN TST_USER_PROFILE USR
ON		OBJ.AUTHOR_ID = USR.USER_ID INNER JOIN TST_EXECUTION_STATUS STA
ON		OBJ.EXECUTION_STATUS_ID = STA.EXECUTION_STATUS_ID
WHERE	AAT.ARTIFACT_TYPE_ID = 2
UNION
SELECT	(AAT.ARTIFACT_ID * 10 + AAT.ARTIFACT_TYPE_ID) AS ARTIFACT_LINK_ID, AAT.ARTIFACT_TYPE_ID, AAT.ARTIFACT_ID, ART.NAME AS ARTIFACT_TYPE_NAME, OBJ.NAME AS ARTIFACT_NAME, '' AS COMMENT, OBJ.OPENER_ID AS CREATOR_ID, OBJ.CREATION_DATE, (RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME,
		AAT.ATTACHMENT_ID, AAT.PROJECT_ID, STA.NAME AS ARTIFACT_STATUS_NAME
FROM	TST_ARTIFACT_ATTACHMENT AAT INNER JOIN TST_ARTIFACT_TYPE ART
ON		AAT.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID INNER JOIN TST_INCIDENT OBJ
ON		AAT.ARTIFACT_ID = OBJ.INCIDENT_ID INNER JOIN TST_USER_PROFILE USR
ON		OBJ.OPENER_ID = USR.USER_ID INNER JOIN TST_INCIDENT_STATUS STA
ON		OBJ.INCIDENT_STATUS_ID = STA.INCIDENT_STATUS_ID
WHERE	AAT.ARTIFACT_TYPE_ID = 3
UNION
SELECT	(AAT.ARTIFACT_ID * 10 + AAT.ARTIFACT_TYPE_ID) AS ARTIFACT_LINK_ID, AAT.ARTIFACT_TYPE_ID, AAT.ARTIFACT_ID, ART.NAME AS ARTIFACT_TYPE_NAME, OBJ.NAME AS ARTIFACT_NAME, '' AS COMMENT, OBJ.CREATOR_ID AS CREATOR_ID, OBJ.CREATION_DATE, (RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME,
		AAT.ATTACHMENT_ID, AAT.PROJECT_ID, '-' AS ARTIFACT_STATUS_NAME
FROM	TST_ARTIFACT_ATTACHMENT AAT INNER JOIN TST_ARTIFACT_TYPE ART
ON		AAT.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID INNER JOIN TST_RELEASE OBJ
ON		AAT.ARTIFACT_ID = OBJ.RELEASE_ID INNER JOIN TST_USER_PROFILE USR
ON		OBJ.CREATOR_ID = USR.USER_ID
WHERE	AAT.ARTIFACT_TYPE_ID = 4
UNION
SELECT	(AAT.ARTIFACT_ID * 10 + AAT.ARTIFACT_TYPE_ID) AS ARTIFACT_LINK_ID, AAT.ARTIFACT_TYPE_ID, AAT.ARTIFACT_ID, ART.NAME AS ARTIFACT_TYPE_NAME, OBJ.NAME AS ARTIFACT_NAME, '' AS COMMENT, OBJ.TESTER_ID AS CREATOR_ID, OBJ.START_DATE, (RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME,
		AAT.ATTACHMENT_ID, AAT.PROJECT_ID, STA.NAME AS ARTIFACT_STATUS_NAME
FROM	TST_ARTIFACT_ATTACHMENT AAT INNER JOIN TST_ARTIFACT_TYPE ART
ON		AAT.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID INNER JOIN TST_TEST_RUN OBJ
ON		AAT.ARTIFACT_ID = OBJ.TEST_RUN_ID INNER JOIN TST_USER_PROFILE USR
ON		OBJ.TESTER_ID = USR.USER_ID INNER JOIN TST_EXECUTION_STATUS STA
ON		OBJ.EXECUTION_STATUS_ID = STA.EXECUTION_STATUS_ID
WHERE	AAT.ARTIFACT_TYPE_ID = 5
UNION
SELECT	(AAT.ARTIFACT_ID * 10 + AAT.ARTIFACT_TYPE_ID) AS ARTIFACT_LINK_ID, AAT.ARTIFACT_TYPE_ID, AAT.ARTIFACT_ID, ART.NAME AS ARTIFACT_TYPE_NAME, OBJ.NAME AS ARTIFACT_NAME, '' AS COMMENT, ATC.AUTHOR_ID AS CREATOR_ID, OBJ.CREATION_DATE, (RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME,
		AAT.ATTACHMENT_ID, AAT.PROJECT_ID, STA.NAME AS ARTIFACT_STATUS_NAME
FROM	TST_ARTIFACT_ATTACHMENT AAT INNER JOIN TST_ARTIFACT_TYPE ART
ON		AAT.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID INNER JOIN TST_TASK OBJ
ON		AAT.ARTIFACT_ID = OBJ.TASK_ID INNER JOIN TST_ATTACHMENT ATC
ON		AAT.ATTACHMENT_ID = ATC.ATTACHMENT_ID INNER JOIN TST_USER_PROFILE USR
ON		ATC.AUTHOR_ID = USR.USER_ID INNER JOIN TST_TASK_STATUS STA
ON		OBJ.TASK_STATUS_ID = STA.TASK_STATUS_ID
WHERE	AAT.ARTIFACT_TYPE_ID = 6
UNION
SELECT	(AAT.ARTIFACT_ID * 10 + AAT.ARTIFACT_TYPE_ID) AS ARTIFACT_LINK_ID, AAT.ARTIFACT_TYPE_ID, AAT.ARTIFACT_ID, ART.NAME AS ARTIFACT_TYPE_NAME, ('Test Case ' + CAST(OBJ.TEST_CASE_ID AS NVARCHAR)+ ' Test Step ' + CAST(OBJ.POSITION AS NVARCHAR)) AS ARTIFACT_NAME, '' AS COMMENT, ATC.AUTHOR_ID AS CREATOR_ID, ATC.UPLOAD_DATE AS CREATION_DATE,
		(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME,
		AAT.ATTACHMENT_ID, AAT.PROJECT_ID, STA.NAME AS ARTIFACT_STATUS_NAME
FROM	TST_ARTIFACT_ATTACHMENT AAT INNER JOIN TST_ARTIFACT_TYPE ART
ON		AAT.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID INNER JOIN TST_TEST_STEP OBJ
ON		AAT.ARTIFACT_ID = OBJ.TEST_STEP_ID INNER JOIN TST_ATTACHMENT ATC
ON		AAT.ATTACHMENT_ID = ATC.ATTACHMENT_ID INNER JOIN TST_USER_PROFILE USR
ON		ATC.AUTHOR_ID = USR.USER_ID INNER JOIN TST_EXECUTION_STATUS STA
ON		OBJ.EXECUTION_STATUS_ID = STA.EXECUTION_STATUS_ID
WHERE	AAT.ARTIFACT_TYPE_ID = 7
UNION
SELECT	(AAT.ARTIFACT_ID * 10 + AAT.ARTIFACT_TYPE_ID) AS ARTIFACT_LINK_ID, AAT.ARTIFACT_TYPE_ID, AAT.ARTIFACT_ID, ART.NAME AS ARTIFACT_TYPE_NAME, OBJ.NAME AS ARTIFACT_NAME, '' AS COMMENT, OBJ.CREATOR_ID AS CREATOR_ID, OBJ.CREATION_DATE, (RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME,
		AAT.ATTACHMENT_ID, AAT.PROJECT_ID, STA.NAME AS ARTIFACT_STATUS_NAME
FROM	TST_ARTIFACT_ATTACHMENT AAT INNER JOIN TST_ARTIFACT_TYPE ART
ON		AAT.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID INNER JOIN TST_TEST_SET OBJ
ON		AAT.ARTIFACT_ID = OBJ.TEST_SET_ID INNER JOIN TST_USER_PROFILE USR
ON		OBJ.CREATOR_ID = USR.USER_ID INNER JOIN TST_TEST_SET_STATUS STA
ON		OBJ.TEST_SET_STATUS_ID = STA.TEST_SET_STATUS_ID
WHERE	AAT.ARTIFACT_TYPE_ID = 8
UNION
SELECT	(AAT.ARTIFACT_ID * 10 + AAT.ARTIFACT_TYPE_ID) AS ARTIFACT_LINK_ID, AAT.ARTIFACT_TYPE_ID, AAT.ARTIFACT_ID, ART.NAME AS ARTIFACT_TYPE_NAME, OBJ.NAME AS ARTIFACT_NAME, '' AS COMMENT, 1 AS CREATOR_ID, LAST_UPDATE_DATE AS CREATION_DATE, '-' AS CREATOR_NAME,
		AAT.ATTACHMENT_ID, AAT.PROJECT_ID, '-' AS ARTIFACT_STATUS_NAME
FROM	TST_ARTIFACT_ATTACHMENT AAT INNER JOIN TST_ARTIFACT_TYPE ART
ON		AAT.ARTIFACT_TYPE_ID = ART.ARTIFACT_TYPE_ID INNER JOIN TST_AUTOMATION_HOST OBJ
ON		AAT.ARTIFACT_ID = OBJ.AUTOMATION_HOST_ID
WHERE	AAT.ARTIFACT_TYPE_ID = 9
GO
