IF OBJECT_ID ( 'RPT_RISK_STATUSES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_RISK_STATUSES];
GO
CREATE VIEW [RPT_RISK_STATUSES]
AS
    SELECT	PROP.*, TEMP.NAME AS PROJECT_TEMPLATE_NAME
	FROM TST_RISK_STATUS AS PROP
	INNER JOIN TST_PROJECT_TEMPLATE AS TEMP ON PROP.PROJECT_TEMPLATE_ID = TEMP.PROJECT_TEMPLATE_ID
    WHERE PROP.IS_ACTIVE = 1
GO
