IF OBJECT_ID ( 'RPT_TASK_TYPES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_TASK_TYPES];
GO
CREATE VIEW [RPT_TASK_TYPES]
AS
    SELECT	PROP.TASK_TYPE_ID, PROP.PROJECT_TEMPLATE_ID, PROP.TASK_WORKFLOW_ID, PROP.NAME, PROP.POSITION, PROP.IS_ACTIVE, PROP.IS_DEFAULT, PROP.IS_PULL_REQUEST, TEMP.NAME AS PROJECT_TEMPLATE_NAME
	FROM TST_TASK_TYPE AS PROP
	INNER JOIN TST_PROJECT_TEMPLATE AS TEMP ON PROP.PROJECT_TEMPLATE_ID = TEMP.PROJECT_TEMPLATE_ID
    WHERE PROP.IS_ACTIVE = 1
GO
