IF OBJECT_ID ( 'RPT_REQUIREMENT_TESTSTEPS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_REQUIREMENT_TESTSTEPS];
GO
CREATE VIEW [RPT_REQUIREMENT_TESTSTEPS]
AS
	SELECT RTS.*, REQ.NAME AS REQUIREMENT_NAME, STP.POSITION, STP.DESCRIPTION AS STEP_DESCRIPTION, STP.EXPECTED_RESULT, STP.SAMPLE_DATA,
		REQ.PROJECT_ID, PRJ.NAME AS PROJECT_NAME
	FROM TST_REQUIREMENT_TEST_STEP RTS
		INNER JOIN TST_REQUIREMENT REQ ON RTS.REQUIREMENT_ID = REQ.REQUIREMENT_ID
		INNER JOIN TST_TEST_STEP STP ON RTS.TEST_STEP_ID = STP.TEST_STEP_ID
		INNER JOIN TST_PROJECT AS PRJ ON REQ.PROJECT_ID = PRJ.PROJECT_ID
GO
