IF OBJECT_ID ( 'RPT_TESTCASE_INCIDENTS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_TESTCASE_INCIDENTS];
GO
CREATE VIEW [RPT_TESTCASE_INCIDENTS]
AS
SELECT	TRN.TEST_CASE_ID, INC.INCIDENT_ID, INC.DETECTED_RELEASE_ID, INC.RESOLVED_RELEASE_ID, INC.VERIFIED_RELEASE_ID, IST.IS_OPEN_STATUS
FROM	TST_TEST_RUN TRN INNER JOIN TST_TEST_RUN_STEP TRS
ON		TRN.TEST_RUN_ID = TRS.TEST_RUN_ID INNER JOIN TST_TEST_RUN_STEP_INCIDENT TRI
ON		TRS.TEST_RUN_STEP_ID = TRI.TEST_RUN_STEP_ID INNER JOIN TST_INCIDENT INC
ON		TRI.INCIDENT_ID = INC.INCIDENT_ID INNER JOIN TST_INCIDENT_STATUS IST
ON		INC.INCIDENT_STATUS_ID = IST.INCIDENT_STATUS_ID
UNION
SELECT	TSP.TEST_CASE_ID AS TEST_CASE_ID, INC.INCIDENT_ID, INC.DETECTED_RELEASE_ID, INC.RESOLVED_RELEASE_ID, INC.VERIFIED_RELEASE_ID, IST.IS_OPEN_STATUS
FROM	TST_TEST_STEP TSP INNER JOIN TST_ARTIFACT_LINK ARL 
ON		TSP.TEST_STEP_ID = ARL.SOURCE_ARTIFACT_ID INNER JOIN TST_INCIDENT INC
ON		ARL.DEST_ARTIFACT_ID = INC.INCIDENT_ID INNER JOIN TST_INCIDENT_STATUS IST
ON		INC.INCIDENT_STATUS_ID = IST.INCIDENT_STATUS_ID
WHERE	ARL.SOURCE_ARTIFACT_TYPE_ID = 7 AND ARL.DEST_ARTIFACT_TYPE_ID = 3
UNION
SELECT	TSP.TEST_CASE_ID AS TEST_CASE_ID, INC.INCIDENT_ID, INC.DETECTED_RELEASE_ID, INC.RESOLVED_RELEASE_ID, INC.VERIFIED_RELEASE_ID, IST.IS_OPEN_STATUS
FROM	TST_TEST_STEP TSP INNER JOIN TST_ARTIFACT_LINK ARL 
ON		TSP.TEST_STEP_ID = ARL.DEST_ARTIFACT_ID INNER JOIN TST_INCIDENT INC
ON		ARL.SOURCE_ARTIFACT_ID = INC.INCIDENT_ID INNER JOIN TST_INCIDENT_STATUS IST
ON		INC.INCIDENT_STATUS_ID = IST.INCIDENT_STATUS_ID
WHERE	ARL.SOURCE_ARTIFACT_TYPE_ID = 3 AND ARL.DEST_ARTIFACT_TYPE_ID = 7
GO
