IF OBJECT_ID ( 'RPT_RELEASE_TESTCASES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_RELEASE_TESTCASES];
GO
CREATE VIEW [RPT_RELEASE_TESTCASES]
AS
	SELECT RTC.*, REL.NAME AS RELEASE_NAME, REL.VERSION_NUMBER AS RELEASE_VERSION_NUMBER, TST.NAME AS TEST_CASE_NAME,
		REL.RELEASE_TYPE_ID, REL.PROJECT_ID, PRJ.NAME AS PROJECT_NAME, RTY.NAME AS RELEASE_TYPE_NAME
	FROM TST_RELEASE_TEST_CASE RTC
		INNER JOIN TST_RELEASE REL ON RTC.RELEASE_ID = REL.RELEASE_ID
		INNER JOIN TST_TEST_CASE TST ON RTC.TEST_CASE_ID = TST.TEST_CASE_ID
		INNER JOIN TST_PROJECT AS PRJ ON REL.PROJECT_ID = PRJ.PROJECT_ID
		INNER JOIN TST_RELEASE_TYPE RTY ON REL.RELEASE_TYPE_ID = RTY.RELEASE_TYPE_ID
GO
