IF OBJECT_ID ( 'RPT_TESTCASE_FOLDERS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_TESTCASE_FOLDERS];
GO
CREATE VIEW [RPT_TESTCASE_FOLDERS]
AS
	SELECT
		TST.*,
		PRJ.NAME AS PROJECT_NAME, PRJ.PROJECT_GROUP_ID
	FROM
		TST_TEST_CASE_FOLDER TST
		INNER JOIN TST_PROJECT AS PRJ ON TST.PROJECT_ID = PRJ.PROJECT_ID
GO
