IF OBJECT_ID ( 'RPT_PROJECT_MEMBERSHIP', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_PROJECT_MEMBERSHIP];
GO
CREATE VIEW [RPT_PROJECT_MEMBERSHIP]
AS
	SELECT	PUSER.*, PRJ.NAME AS PROJECT_NAME, ROLE.NAME AS PROJECT_ROLE_NAME, USR.USER_NAME, UPL.FIRST_NAME, UPL.LAST_NAME, UPL.DEPARTMENT, UPL.IS_ADMIN AS IS_SYSTEM_ADMIN
	FROM TST_PROJECT_USER AS PUSER 
	LEFT JOIN TST_PROJECT PRJ ON PUSER.PROJECT_ID = PRJ.PROJECT_ID
	LEFT JOIN TST_PROJECT_ROLE ROLE ON PUSER.PROJECT_ROLE_ID = ROLE.PROJECT_ROLE_ID
	LEFT JOIN TST_USER USR ON PUSER.USER_ID = USR.USER_ID
	INNER JOIN TST_USER_PROFILE AS UPL ON USR.USER_ID = UPL.USER_ID
GO
