IF OBJECT_ID ( 'RPT_COMMENTS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_COMMENTS];
GO
CREATE VIEW [RPT_COMMENTS]
AS
	SELECT	ART.ARTIFACT_TYPE_ID, CMT.ARTIFACT_ID, CMT.CREATOR_ID, CMT.TEXT AS COMMENT_TEXT, CMT.CREATION_DATE,
			(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
	FROM TST_REQUIREMENT_DISCUSSION CMT
		INNER JOIN TST_USER_PROFILE USR ON USR.USER_ID = CMT.CREATOR_ID
		INNER JOIN TST_ARTIFACT_TYPE ART ON ART.ARTIFACT_TYPE_ID = 1
		WHERE CMT.IS_DELETED = 0
	UNION
	SELECT	ART.ARTIFACT_TYPE_ID, CMT.ARTIFACT_ID, CMT.CREATOR_ID, CMT.TEXT AS COMMENT_TEXT, CMT.CREATION_DATE,
			(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
	FROM TST_TEST_CASE_DISCUSSION CMT
		INNER JOIN TST_USER_PROFILE USR ON USR.USER_ID = CMT.CREATOR_ID
		INNER JOIN TST_ARTIFACT_TYPE ART ON ART.ARTIFACT_TYPE_ID = 2
		WHERE CMT.IS_DELETED = 0
	UNION
	SELECT	ART.ARTIFACT_TYPE_ID, CMT.INCIDENT_ID AS ARTIFACT_ID, CMT.CREATOR_ID, CMT.RESOLUTION AS COMMENT_TEXT, CMT.CREATION_DATE,
			(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
	FROM TST_INCIDENT_RESOLUTION CMT
		INNER JOIN TST_USER_PROFILE USR ON USR.USER_ID = CMT.CREATOR_ID
		INNER JOIN TST_ARTIFACT_TYPE ART ON ART.ARTIFACT_TYPE_ID = 3
	UNION
	SELECT	ART.ARTIFACT_TYPE_ID, CMT.ARTIFACT_ID, CMT.CREATOR_ID, CMT.TEXT AS COMMENT_TEXT, CMT.CREATION_DATE,
			(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
	FROM TST_RELEASE_DISCUSSION CMT
		INNER JOIN TST_USER_PROFILE USR ON USR.USER_ID = CMT.CREATOR_ID
		INNER JOIN TST_ARTIFACT_TYPE ART ON ART.ARTIFACT_TYPE_ID = 4
		WHERE CMT.IS_DELETED = 0
	UNION
	SELECT	ART.ARTIFACT_TYPE_ID, CMT.ARTIFACT_ID, CMT.CREATOR_ID, CMT.TEXT AS COMMENT_TEXT, CMT.CREATION_DATE,
			(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
	FROM TST_TASK_DISCUSSION CMT
		INNER JOIN TST_USER_PROFILE USR ON USR.USER_ID = CMT.CREATOR_ID
		INNER JOIN TST_ARTIFACT_TYPE ART ON ART.ARTIFACT_TYPE_ID = 6
		WHERE CMT.IS_DELETED = 0
	UNION
	SELECT	ART.ARTIFACT_TYPE_ID, CMT.ARTIFACT_ID, CMT.CREATOR_ID, CMT.TEXT AS COMMENT_TEXT, CMT.CREATION_DATE,
			(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
	FROM TST_TEST_SET_DISCUSSION CMT
		INNER JOIN TST_USER_PROFILE USR ON USR.USER_ID = CMT.CREATOR_ID
		INNER JOIN TST_ARTIFACT_TYPE ART ON ART.ARTIFACT_TYPE_ID = 8
		WHERE CMT.IS_DELETED = 0
	UNION
	SELECT	ART.ARTIFACT_TYPE_ID, CMT.ARTIFACT_ID, CMT.CREATOR_ID, CMT.TEXT AS COMMENT_TEXT, CMT.CREATON_DATE AS CREATION_DATE,
			(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
	FROM TST_DOCUMENT_DISCUSSION CMT
		INNER JOIN TST_USER_PROFILE USR ON USR.USER_ID = CMT.CREATOR_ID
		INNER JOIN TST_ARTIFACT_TYPE ART ON ART.ARTIFACT_TYPE_ID = 13
		WHERE CMT.IS_DELETED = 0
	UNION
	SELECT	ART.ARTIFACT_TYPE_ID, CMT.ARTIFACT_ID, CMT.CREATOR_ID, CMT.TEXT AS COMMENT_TEXT, CMT.CREATION_DATE,
			(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS CREATOR_NAME, ART.NAME AS ARTIFACT_TYPE_NAME
	FROM TST_RISK_DISCUSSION CMT
		INNER JOIN TST_USER_PROFILE USR ON USR.USER_ID = CMT.CREATOR_ID
		INNER JOIN TST_ARTIFACT_TYPE ART ON ART.ARTIFACT_TYPE_ID = 14
		WHERE CMT.IS_DELETED = 0
GO
