IF OBJECT_ID ( 'RPT_TESTSET_TESTCASES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_TESTSET_TESTCASES];
GO
CREATE VIEW [RPT_TESTSET_TESTCASES]
AS
	SELECT TSC.*, TSE.NAME AS TEST_SET_NAME, TST.NAME AS TEST_CASE_NAME,
		(RTRIM(USR.FIRST_NAME + ' ' + ISNULL(USR.MIDDLE_INITIAL,'')) + ' ' + USR.LAST_NAME) AS OWNER_NAME,
		TSE.PROJECT_ID, PRJ.NAME AS PROJECT_NAME
	FROM TST_TEST_SET_TEST_CASE TSC
		LEFT JOIN TST_USER_PROFILE USR ON TSC.OWNER_ID = USR.USER_ID
		INNER JOIN TST_TEST_SET TSE ON TSC.TEST_SET_ID = TSE.TEST_SET_ID
		INNER JOIN TST_TEST_CASE TST ON TSC.TEST_CASE_ID = TST.TEST_CASE_ID
		INNER JOIN TST_PROJECT AS PRJ ON TSE.PROJECT_ID = PRJ.PROJECT_ID
GO
