IF OBJECT_ID ( 'RPT_CUSTOM_LISTS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_CUSTOM_LISTS];
GO
CREATE VIEW [RPT_CUSTOM_LISTS]
AS
	SELECT	CPL.*, PRJ.PROJECT_ID, PRJ.NAME AS PROJECT_NAME, PRJ.IS_ACTIVE AS PROJECT_IS_ACTIVE
	FROM TST_CUSTOM_PROPERTY_LIST AS CPL
		INNER JOIN TST_PROJECT PRJ ON PRJ.PROJECT_TEMPLATE_ID = CPL.PROJECT_TEMPLATE_ID
GO
