IF OBJECT_ID ( 'RPT_RISK_MITIGATIONS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_RISK_MITIGATIONS];
GO
CREATE VIEW [RPT_RISK_MITIGATIONS]
AS
	SELECT	RSM.*,
			RSK.NAME AS RISK_NAME,
			RSK.REVIEW_DATE AS RISK_REVIEW_DATE,
			PRJ.IS_ACTIVE AS PROJECT_IS_ACTIVE,
			PRJ.PROJECT_GROUP_ID AS PROJECT_PROJECT_GROUP_ID,
			PRJ.NAME AS PROJECT_NAME
            			
    FROM TST_RISK_MITIGATION RSM
		INNER JOIN TST_RISK RSK ON RSM.RISK_ID = RSK.RISK_ID
		INNER JOIN TST_PROJECT PRJ ON RSK.PROJECT_ID = PRJ.PROJECT_ID
	WHERE PRJ.IS_ACTIVE = 1
GO
