IF OBJECT_ID ( 'RPT_BUILDS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_BUILDS];
GO
CREATE VIEW [RPT_BUILDS]
AS
	SELECT	BLD.*, REL.NAME AS RELEASE_NAME, REL.VERSION_NUMBER AS RELEASE_VERSION_NUMBER,
			PRJ.NAME AS PROJECT_NAME, PRJ.PROJECT_GROUP_ID	
	FROM TST_BUILD AS BLD
		INNER JOIN TST_RELEASE AS REL ON BLD.RELEASE_ID = REL.RELEASE_ID
		INNER JOIN TST_PROJECT AS PRJ ON BLD.PROJECT_ID = PRJ.PROJECT_ID
	WHERE PRJ.IS_ACTIVE = 1 AND REL.IS_DELETED = 0 AND BLD.IS_DELETED = 0
GO
