IF OBJECT_ID ( 'RPT_PROJECT_ROLES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_PROJECT_ROLES];
GO
CREATE VIEW [RPT_PROJECT_ROLES]
AS
    SELECT	ROLE.*, RLP.ARTIFACT_TYPE_ID, TYPE.NAME AS ARTIFACT, PRM.NAME AS PERMISSION
    FROM TST_PROJECT_ROLE AS ROLE
    LEFT JOIN TST_PROJECT_ROLE_PERMISSION AS RLP ON ROLE.PROJECT_ROLE_ID = RLP.PROJECT_ROLE_ID
    LEFT JOIN TST_ARTIFACT_TYPE AS TYPE ON RLP.ARTIFACT_TYPE_ID = TYPE.ARTIFACT_TYPE_ID
    INNER JOIN TST_PERMISSION AS PRM ON RLP.PERMISSION_ID = PRM.PERMISSION_ID
GO
