IF OBJECT_ID ( 'RPT_ARTIFACT_TYPES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_ARTIFACT_TYPES];
GO
CREATE VIEW [RPT_ARTIFACT_TYPES]
AS
	SELECT	ART.NAME, ART.ARTIFACT_TYPE_ID, ART.PREFIX
	FROM TST_ARTIFACT_TYPE AS ART
	WHERE ART.IS_GLOBAL_ITEM = 0
GO
