IF OBJECT_ID ( 'RPT_CUSTOM_PROPERTY_DEFINITIONS', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_CUSTOM_PROPERTY_DEFINITIONS];
GO
CREATE VIEW [RPT_CUSTOM_PROPERTY_DEFINITIONS]
AS
	SELECT	CPT.*, PRJ.PROJECT_ID, PRJ.NAME AS PROJECT_NAME, PRJ.IS_ACTIVE AS PROJECT_IS_ACTIVE, ART.NAME AS ARTIFACT_TYPE_NAME,
		CPY.NAME AS CUSTOM_PROPERTY_TYPE_NAME, CPL.NAME AS CUSTOM_PROPERTY_LIST_NAME
	FROM TST_CUSTOM_PROPERTY AS CPT
	INNER JOIN TST_PROJECT PRJ ON PRJ.PROJECT_TEMPLATE_ID = CPT.PROJECT_TEMPLATE_ID
	INNER JOIN TST_ARTIFACT_TYPE ART ON ART.ARTIFACT_TYPE_ID = CPT.ARTIFACT_TYPE_ID
	INNER JOIN TST_CUSTOM_PROPERTY_TYPE CPY ON CPY.CUSTOM_PROPERTY_TYPE_ID = CPT.CUSTOM_PROPERTY_TYPE_ID
	LEFT JOIN TST_CUSTOM_PROPERTY_LIST CPL ON CPT.CUSTOM_PROPERTY_LIST_ID = CPL.CUSTOM_PROPERTY_LIST_ID
GO
