IF OBJECT_ID ( 'RPT_TASK_PRIORITIES', 'V' ) IS NOT NULL 
    DROP VIEW [RPT_TASK_PRIORITIES];
GO
CREATE VIEW [RPT_TASK_PRIORITIES]
AS
    SELECT	PROP.*, TEMP.NAME AS PROJECT_TEMPLATE_NAME
	FROM TST_TASK_PRIORITY AS PROP
	INNER JOIN TST_PROJECT_TEMPLATE AS TEMP ON PROP.PROJECT_TEMPLATE_ID = TEMP.PROJECT_TEMPLATE_ID
    WHERE PROP.IS_ACTIVE = 1
GO
